### ISSUE TITLE
Record events for AppRTC and other demos 

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#12]
https://github.com/GoogleChrome/webrtc/issues/265

samdutton commented on Dec 4, 2014
For example, to record numbers for those who, having navigated to apprtc.appspot.com: 
• call gUM
• request a connection
• get a connection
• get errors
...

Could also add events for icon/button clicks on AppRTC and other demos.
Justin Ubertijuberti added the apprtc label on Dec 4, 2014
Philipp Hancke

fippo commented on Dec 5, 2014
FWIW, here is the list of events we use for talky with a short description.

videoConnected (calls) in remotestreamadded; type (video/screen)
videoDisconnected in remotestreamremoved I think. Called only about 50% of the time since browser is closed
iceConnected (calls, really connected) candidatePair, whether ipv6 is used, whether a local/remote IPv6 candidate is available, setup time (measured from checking->connected)
iceFailed cause (called with a 30s timeout sometimes), local/remote turn/ipv6 candidate availability
localMedia (GUM success)
localMediaError (GUM failure) name (error code)
shareScreen
mute / unmute with media type (audio/video)
Philipp Hanckefippo referenced this issue on Dec 6, 2014
 Open
figure out the local type preference of the active candidate #281
Sam Dutton
 Owner
 samdutton commented on Dec 8, 2014
Thanks Philipp – that's really useful.
…
Varun Singh

vr000m commented 25 days ago
In addition to those listed above we have:

iceDisconnected: if the interface disappears. If iceConnected again on the same or a different candidate pair, then we can pair disconnections and connections to calculate connectivity disruptions.

**Comment by KaptenJansson** [comment]
@juberti do we still want to do this?

**Comment by KaptenJansson** [comment]
Closing due to age.
