### ISSUE TITLE
AppRTC broken for Firefox

### ISSUE THREAD

**Issue by phoglund** [webrtc/apprtc#122]
The AppRTC interop test found that we can no longer bring up calls with a Firefox participant. When I run the test, the Firefox participant gets

'toJSON' called on an object that does not implement interface mozRTCSessionDescription.

on the last line of

function stringifyObject(object) {
  function deepCopy(src) {
    if (typeof src !== "object") {
      return src;
    }
    var dst = Array.isArray(src) ? [] : {};
    for (var property in src) {
      dst[property] = deepCopy(src[property]);
    }
    return dst;
  }
  return JSON.stringify(deepCopy(object));
}

I tried reproing with just connecting two Firefox tabs to apprtc.appspot.com; I couldn't see the error there but the call still didn't get up.

**Comment by phoglund** [comment]
Jiayang: please help with an owner.

You can run the test with out/Debug/browser_tests --gtest_filter="WebRtcApprtc*" --run-manual --gtest_also_run_disabled_tests (follow any instructions the test gives you), but it needs to download a bunch of things so I would not recommend that. You should be able to investigate this with just an apprtc instance and connecting with Firefox.

Also note the Firefox used in the test is a Nightly, so if you can't repro, try with the latest nightly Firefox.

**Comment by chuckhays** [comment]
This looks like a result of the fix I made for Chrome Canary on Monday, I'll take a look.

**Comment by chuckhays** [comment]
What is happening here is that mozRTCSessionDescription includes a toJSON method, which gets copied to the new object when the deep copy is made. When it gets executed by JSON.stringify, the implementation complains that the object isn't the right type.

**Comment by chuckhays** [comment]
Fix in master, should be fixed once deployed.
