### ISSUE TITLE
BYE and DEL messages are not sent when the tab is closed

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#128]
Start a call with tab to tab.
Close one tab, observe that the other tab shows frozen remote video, instead of hiding remote video and making local video center.

**Comment by jiayliu** [comment]
@marwahvikas

**Comment by jiayliu** [comment]
It seems the BYE message is not sent. The DEL to GAE is not sent either. Rejoining the room will fail.

**Comment by chuckhays** [comment]
I haven't been able to repro this, what browser/OS/server were you using?

**Comment by jiayliu** [comment]
Linux, Chrome M42 beta, prod/3-dot-apprtc.

On Fri, Mar 20, 2015 at 8:17 AM, Chuck Hays <notifications@github.com>
wrote:

> I haven't been able to repro this, what browser/OS/server were you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/128#issuecomment-84044034>.
>



-- 
Jiayang Liu

**Comment by chuckhays** [comment]
Can repro on M42 beta with apprtc.appspot.com as well. Can also repro on Canary/mac.

The issue seems to be that onbeforeunload is not getting called, but only in certain situations.
Ex:
Open tab 1, create new call
Open tab 2 to join same call

If you close tab 1, the call exits properly
If you close tab 2, this issue occurs

Still investigating.

**Comment by jiayliu** [comment]
It seems it only happens if the second tab is opened by clicking on the sharing link.

**Comment by chuckhays** [comment]
Wow, you are right. If I copy/paste to a new tab, it doesn't happen, if I click the link, it does.

**Comment by chuckhays** [comment]
Here is a minimal repro doc:
http://chuckhays.github.io/apprtc/index.html
Source:
https://github.com/chuckhays/apprtc/blob/gh-pages/index.html

**Comment by chuckhays** [comment]
Filed Chromium bug:
https://code.google.com/p/chromium/issues/detail?id=469293

**Comment by jiayliu** [comment]
Fixed in Chrome
