### ISSUE TITLE
#255 introduces csslint warnings due to "object-fit" is not in CSS3 spec

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#13]
https://github.com/GoogleChrome/webrtc/issues/263

KaptenJansson commented on Dec 4, 2014
Pull request #255 introduces the following warning:
WARNING: Unknown property 'object-fit'. Properties should be known (listed in CSS3 specification) or be a vendor-prefixed property. (known-properties) Browsers: All

See the original bug for full discussion.

**Comment by juberti** [comment]
I thought this was resolved by a csslint change?

**Comment by jiayliu** [comment]
Right, I don't see it from 'grunt' now.

**Comment by KaptenJansson** [comment]
Yes and also they fixed it and merged it to csslint/parser-lib but have not pushed a release to NPM yet.
