### ISSUE TITLE
TURN server integration

### ISSUE THREAD

**Issue by lokeshyv** [webrtc/apprtc#135]
Dear All,

I am able to deploy and run apprtc on a local server. However i cannot get the video conference working as page displays saying "No Turn servers" .  I have tried installing and running rfc5766-turn-server on the local server, but i am not very sure as how to go about integrating TURN server running on the local machine with apprtc. I do notice that there is  constants.py file in the SRC folder which needs to be modified to point to the new TURN URL ( running on the localmachine ). I have tried changing the URL but still end up with the "No TURN server" message.

When i run a check on all the running processes on the local server i do notice that the TURN server is running, but when i run the turn-prober.sh in the tools directory, the result is empty( no output). Does the script need any change. 

KIndly help.

**Comment by jiayliu** [comment]
You should modify the TURN url your own HTTP server that returns the list
of TURN servers and credentials.
See https://github.com/webrtc/apprtc/blob/master/src/web_app/js/util.js#L78
for what request and response are expected.

On Mon, Mar 30, 2015 at 2:20 AM, lokeshyv <notifications@github.com> wrote:

> Dear All,
>
> I am able to deploy and run apprtc on a local server. However i cannot get
> the video conference working as page displays saying "No Turn servers" . I
> have tried installing and running rfc5766-turn-server on the local server,
> but i am not very sure as how to go about integrating TURN server running
> on the local machine with apprtc. I do notice that there is constants.py
> file in the SRC folder which needs to be modified to point to the new TURN
> URL ( running on the localmachine ). I have tried changing the URL but
> still end up with the "No TURN server" message.
>
> When i run a check on all the running processes on the local server i do
> notice that the TURN server is running, but when i run the turn-prober.sh
> in the tools directory, the result is empty( no output). Does the script
> need any change.
>
> KIndly help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/135>.
>



-- 
Jiayang Liu
