### ISSUE TITLE
Move JS/CSS/HTML under src/app_engine

### ISSUE THREAD

**Issue by juberti** [webrtc/apprtc#14]
Since index.html is under app_engine, the other app files should move there too.

**Comment by jiayliu** [comment]
But they are shared with chrome_app.
I can look into ways to move index.html into html/ instead.

**Comment by juberti** [comment]
hmm... good point. maybe put it all, including chrome_app, under a webapp folder?

**Comment by jiayliu** [comment]
do you mean
src
---web_app
---------js/, html/, css/, images/, chrome_app/
---app_engine
?


On Tue, Feb 3, 2015 at 10:55 PM, Justin Uberti <notifications@github.com>
wrote:

> hmm... good point. maybe put it all, including chrome_app, under a webapp
> folder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/14#issuecomment-72800000>.
>



-- 
Jiayang Liu

**Comment by juberti** [comment]
yes

**Comment by jiayliu** [comment]
FYI @chuckhays @tkchin
