### ISSUE TITLE
Analytics page should validate request types.

### ISSUE THREAD

**Issue by milkypostman** [webrtc/apprtc#141]
The data types of the data sent from the client should be validated before getting to the analytics module.

**Comment by juberti** [comment]
Anything still needed here?

**Comment by milkypostman** [comment]
it hasn't been fixed yet. not high up on the list of things to do. should we leave it or close as wont fix?

**Comment by juberti** [comment]
Would we ever fix it, given that AppRTC is a demo app?

**Comment by milkypostman** [comment]
probably not.
