### ISSUE TITLE
Stealth joining AppRTC room possible by blocking camera

### ISSUE THREAD

**Issue by pbos** [webrtc/apprtc#142]
It looks like it's possible to stealth-join a room by blocking the camera. I run a local Chromium build where I use the camera, so it's blocked because it's used by another process (I assume).

Then I join an AppRTC room where Stefan is sitting, he has no idea I'm there. I've no local preview, but I can see him (but can't talk to him, probably because the other Chromium owns the mic as well).

My side:
![stealth-apprtc](https://cloud.githubusercontent.com/assets/95335/7182823/18a9f506-e454-11e4-9cb2-74b57eb7af34.png)

Stefan's side:
![stefan-remote-side](https://cloud.githubusercontent.com/assets/95335/7182854/45640cee-e454-11e4-9b5a-1ace302992d1.png)

Does this possibly happen because we only flip to remote video on receiving the first frame? If that's the case we should really fall back to showing a fake avatar or something else if we don't receive a frame within the first n seconds.

**Comment by KaptenJansson** [comment]
I believe this is due to checking the [readyState >= 2](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/appcontroller.js#L263) of the videoElement before doing the transition. readyState >= 2 will never be reached on the remote side due to the user blocking the camera and mic will not be sending a stream.

**Comment by pbos** [comment]
You could also display a bubble that says that you are sending but that nothing's been received from the remote side yet, until the remote side eventually connects. This could pop up about one second after the call has started if it's not by then in readyState >= 2. Does that make sense?

**Comment by KaptenJansson** [comment]
Closing due to age.
