### ISSUE TITLE
Unable to establish a loopback call in a new room after leaving a loopback call

### ISSUE THREAD

**Issue by tednakamura** [webrtc/apprtc#143]
Repro steps:
1) Go to https://apprtc.appspot.com/?debug=loopback, click Join
2) Click the Hangup button
3) Click the "New Room" button
4) Enter a new room name (if one isn't already present), then click Join

Issue: I'm stuck in the "waiting for someone to join this room" state

js console shows these errors:
Room server join error: Registration error: FULL
WebSocket register error: Registration error: FULL

Note that depending on the version of Chrome you're using, if in step 3), you instead click on Rejoin, the loopback call will be established correctly, but audio will fail. That's currently tracked in Chrome bug http://crbug.com/477434.

**Comment by jiayliu** [comment]
It's due to not cleaning up the even listeners and joining the room twice. I'll work on a fix.

**Comment by jiayliu** [comment]
@marwahvikas 
Can you push to AppRTC?
