### ISSUE TITLE
Use own server

### ISSUE THREAD

**Issue by n0per** [webrtc/apprtc#146]
Hi all, 

I got the app running fine, but I realized I was not in control of the relay server. I want to be able to run the server on my own box. Does anyone know where I can get the same server that is being used to relay the messages. Any help will highly be appreciated. 

Thanks.

**Comment by jiayliu** [comment]
You can build your own TURN server from
https://code.google.com/p/rfc5766-turn-server/

On Thu, Apr 23, 2015 at 4:39 PM, n0per <notifications@github.com> wrote:

> Hi all,
>
> I got the app running fine, but I realized I was not in control of the
> relay server. I want to be able to run the server on my own box. Does
> anyone know where I can get the same server that is being used to relay the
> messages. Any help will highly be appreciated.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/146>.
>



-- 
Jiayang Liu
