### ISSUE TITLE
Room Server Join Error

### ISSUE THREAD

**Issue by rohit1290** [webrtc/apprtc#147]
I have followed all the instruction on the page and have deployed the app on Google app engine. Whenever I try to connect with someone, there is an error on the screen for the second person joining the conversation stating the following:

Room server join error: Failed to join the room: Status=500, response=

Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.

WebSocket register error: Failed to join the room: Status=500, response=

Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.

Version:    
gitHash:    1f81f1f3990d615ed84aed6be02406e8c0fdaca7
branch:     master
time:       Fri Apr 17 11:43:14 2015 -0700

Kindly help.

**Comment by chuckhays** [comment]
Can you check the app engine logs for the join request? There may be useful information there about why the 2nd person joining the room fails.

**Comment by vremenno** [comment]
Any update on this issue? I am getting the same error on GAE, but works fine on our development server.

**Comment by KaptenJansson** [comment]
What is your development server? Could it be some connection issue, i.e. your GAE instance does not have the same access?

**Comment by vremenno** [comment]
We've setup AppRTC on several CentOS 6.7 servers and it works perfect with Google App Engine SDK for Python + our coturn server, it also works without any issues on my desktop, however, when deploying same code to GAE instance I get the following:

1. One person creates a room and waits for another person to join - no issues here, clean log.
2. Second person tries to join (or I just open another browser window) and enter the room number to join, I get the following error:

===================================on the screen =========================
Room server join error: Failed to join the room: Status=500, response=

Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.

WebSocket register error: Failed to join the room: Status=500, response=

Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.

========================================================================

=================================== console =========================

POST https://[instance-name].appspot.com/join/138985552 500 (OK)
(anonymous function)	@	apprtc.debug.js:2255
sendUrlRequest	@	apprtc.debug.js:2236
sendAsyncUrlRequest	@	apprtc.debug.js:2233
(anonymous function)	@	apprtc.debug.js:1051
Call.joinRoom_	@	apprtc.debug.js:1046
Call.connectToRoom_	@	apprtc.debug.js:935
Call.start	@	apprtc.debug.js:798
AppController.finishCallSetup_	@	apprtc.debug.js:523
(anonymous function)	@	apprtc.debug.js:514
RoomSelection.loadRoom_	@	apprtc.debug.js:1713
RoomSelection.onJoinButton_	@	apprtc.debug.js:1702
 
 Room server join error: Failed to join the room: Status=500, response=

========================================================================

Would be helpful if someone points us to the right direction to resolve this issue.

**Comment by KaptenJansson** [comment]
Have you setup collder, the websocket signalling server and made it
reachable by the GAE instance?

**Comment by KaptenJansson** [comment]
Link: https://github.com/webrtc/apprtc/tree/master/src/collider

**Comment by vremenno** [comment]
yes, I tried to use that exact collider and received the same error I stated above. Currently I use apprtc-ws.webrtc.org:443 and it works on the server, should work on GAE instance too, unless apprtc-ws.webrtc.org is blocking such connections.

**Comment by KaptenJansson** [comment]
Yes, you have to setup your own, it's not for public use.

**Comment by vremenno** [comment]
Kapten, I was not aware of that, I'll give it another try with our collider and see if there any issues.

**Comment by vremenno** [comment]
All right, I went back to our collider and tested again - same error. First person who created the room has no issues and checks at our collider just fine, the other person gets 500 join error before even reaching the collider server. Seems to me that the collider is not the issue here. Any thoughts Kapten?

**Comment by KaptenJansson** [comment]
I will try this locally myself and see if I can figure it out, do not know if I have time this week though.

**Comment by vremenno** [comment]
Kapten, have you had a chance to check this issue?

**Comment by KaptenJansson** [comment]
One thing I forgot to ask is google app engine logs for the join request as asked by Chuck in the first comment. Could you post them here? It's working for me.

**Comment by vremenno** [comment]
here it is

E 2016-01-08 01:16:14.796  500       0 B   87 ms I 01:16:14.818 I 01:16:14.819 I 01:16:14.821 E 01:16:14.880 E 01:16:14.881 /join/testroom123
  ***.11.***.111 - - [07/Jan/2016:22:16:14 -0800] "POST /join/testroom123 HTTP/1.1" 500 - - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36" "[***GAE-NAME***].appspot.com" ms=87 cpu_ms=20 cpm_usd=6.8619e-05 instance=00c61b117cc153e5aded6635030002f3cd6dffbd app_engine_release=1.9.30 trace_id=a7fcc3e879c21319c859b06c378a338e
    I 01:16:14.818 Added client 61068866 in room testroom123, retries = 0
    I 01:16:14.819 Event: {'rows': [{'json': {u'timestamp': '2016-01-08T06:16:14.819230', u'host': '[***GAE-NAME***].appspot.com', u'room_id': 'testroom123', u'event_type': u'ROOM_SIZE_2'}}]}
    I 01:16:14.821 URL being requested: https://www.googleapis.com/bigquery/v2/projects/[***GAE-NAME***]/datasets/prod/tables/analytics/insertAll?alt=json
    E 01:16:14.880 <HttpError 404 when requesting https://www.googleapis.com/bigquery/v2/projects/[***GAE-NAME***]/datasets/prod/tables/analytics/insertAll?alt=json returned "Not found: Dataset [***GAE-NAME***]:prod">
      Traceback (most recent call last):
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
          rv = self.handle_exception(request, response, e)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
          rv = self.router.dispatch(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
          return route.handler_adapter(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
          return handler.dispatch()
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
          return self.handle_exception(e, self.app.debug)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
          return method(*args, **kwargs)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/apprtc.py", line 517, in post
          result = add_client_to_room(self.request, room_id, client_id, is_loopback)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/apprtc.py", line 388, in add_client_to_room
          host=request.host)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/analytics.py", line 126, in report_event
          analytics.report_event(*args, **kwargs)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/analytics.py", line 101, in report_event
          body=obj).execute()
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/third_party/oauth2client/util.py", line 132, in positional_wrapper
          return wrapped(*args, **kwargs)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/third_party/apiclient/http.py", line 723, in execute
          raise HttpError(resp, content, uri=self.uri)
      HttpError: <HttpError 404 when requesting https://www.googleapis.com/bigquery/v2/projects/[***GAE-NAME***]/datasets/prod/tables/analytics/insertAll?alt=json returned "Not found: Dataset [***GAE-NAME***]:prod">
    E 01:16:14.881 Traceback (most recent call last):
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
          result = handler(dict(self._environ), self._StartResponse)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1519, in __call__
          response = self._internal_error(e)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
          rv = self.handle_exception(request, response, e)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
          rv = self.router.dispatch(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
          return route.handler_adapter(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
          return handler.dispatch()
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
          return self.handle_exception(e, self.app.debug)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
          return method(*args, **kwargs)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/apprtc.py", line 517, in post
          result = add_client_to_room(self.request, room_id, client_id, is_loopback)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/apprtc.py", line 388, in add_client_to_room
          host=request.host)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/analytics.py", line 126, in report_event
          analytics.report_event(*args, **kwargs)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/analytics.py", line 101, in report_event
          body=obj).execute()
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/third_party/oauth2client/util.py", line 132, in positional_wrapper
          return wrapped(*args, **kwargs)
        File "/base/data/home/apps/s~[***GAE-NAME***]/1.389763660769578521/third_party/apiclient/http.py", line 723, in execute
          raise HttpError(resp, content, uri=self.uri)
      HttpError: <HttpError 404 when requesting https://www.googleapis.com/bigquery/v2/projects/[***GAE-NAME***]/datasets/prod/tables/analytics/insertAll?alt=json returned "Not found: Dataset [***GAE-NAME***]:prod">
      
      
      
      
      
      W 2016-01-08 01:16:01.705  200   3.33 KB   26 ms I 01:16:01.727 I 01:16:01.728 W 01:16:01.729 /r/testroom123
  ***.11.***.111 - - [07/Jan/2016:22:16:01 -0800] "GET /r/testroom123 HTTP/1.1" 200 3405 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36" "[***GAE-NAME***].appspot.com" ms=26 cpu_ms=10 cpm_usd=0.000380538 instance=00c61b117cc153e5aded6635030002f3cd6dffbd app_engine_release=1.9.30 trace_id=a5deb9953a76b3be948c04ea6503fee2
    I 01:16:01.727 Room testroom123 has state ['12302455']
    I 01:16:01.728 Applying media constraints: {'audio': True, 'video': {'optional': [{'minWidth': '1280'}, {'minHeight': '720'}], 'mandatory': {}}}
    W 01:16:01.729 Invalid or no value returned from memcache, using fallback: null

**Comment by KaptenJansson** [comment]
It seems like the machine you host on does not have access to the [GAE-NAME] GAE instance:

HttpError: / HttpError 404 when requesting https://www.googleapis.com/bigquery/v2/projects/[***GAE-NAME***]/datasets/prod/tables/analytics/insertAll?alt=json returned "Not found: Dataset [GAE-NAME]:prod">

Have you setup a google app engine project and are you using it's name where you have redacted with [GAE-NAME] ?

**Comment by vremenno** [comment]
I host the app at Google cloud platform and I do use Project ID instead of [GAE-NAME]

**Comment by vremenno** [comment]
The issue is resolved now. Turned out that BigQuery was not enabled. If any one has a similar issue, make sure you do the following:

1. Enable BigQuery API
2. Create Billing
3. Create BigQuery table according to the apprtc instructions (bq mk -t prod.analytics bigquery/analytics_schema.json)

Thank you for your help Kapten

Happy coding!

**Comment by KaptenJansson** [comment]
Awesome, thanks for sharing the solution!

**Comment by zhangzhy2000** [comment]
> The issue is resolved now. Turned out that BigQuery was not enabled. If any one has a similar issue, make sure you do the following:
> 
> 1. Enable BigQuery API
> 2. Create Billing
> 3. Create BigQuery table according to the apprtc instructions (bq mk -t prod.analytics bigquery/analytics_schema.json)
> 
> Thank you for your help Kapten
> 
> Happy coding!

This works for me too. Thanks!!

**Comment by bhatiaravi** [comment]
@vremenno solution works
Alternately if you wish to skip using Bigquery, just comment out following from apprtc.py:
#import analytics
#analytics.report_event....
