### ISSUE TITLE
AppRTC websocket in local server

### ISSUE THREAD

**Issue by AdamWorld** [webrtc/apprtc#149]
Hi!
I tried to implement apprtc working locally without using external server.
But in apprtc, it uses another server like following.
- wss://apprtc-ws.webrtc.org:443/ws
- https://apprtc-ws.webrtc.org:443

What are those servers and how can i implement them in local server?

Thank you,'
Kind Regards,

**Comment by jiayliu** [comment]
The source code for that is here:
https://github.com/webrtc/apprtc/tree/master/src/collider

See the README for details.

On Tue, May 12, 2015 at 5:59 AM, AdamWorld <notifications@github.com> wrote:

> Hi!
> I tried to implement apprtc working locally without using external server.
> But in apprtc, it uses another server like following.
>
>    - wss://apprtc-ws.webrtc.org:443/ws
>    - https://apprtc-ws.webrtc.org:443
>
> What are those servers and how can i implement them locally?
>
> Thank you,'
> Kind Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/149>.
>



-- 
Jiayang Liu

**Comment by roygwsidev** [comment]
Anyone have this server code in node.js?

**Comment by markos92i** [comment]
https://github.com/ISBX/apprtc-node-server here i found a port for the apprtc server and this is a port for the apprtc collider https://github.com/jrstv/collider.js

Hope this helps you.

**Comment by NeelamParmar** [comment]
Helo, 
Coud anyone tell me, did this above links worked ?

I tried for [ https://github.com/jrstv/collider.js](url) , but faced error while npm install.

And [https://github.com/ISBX/apprtc-node-server](url) uses  WSS_HOST_PORT_PAIRS: ['apprtc-ws.webrtc.org:443', 'apprtc-ws-2.webrtc.org:443'],. So again it's same.

and also tried [https://github.com/webrtc/apprtc/tree/master/src/collider](url), but faced websocket connection issue, while connecting using collider url for WSS_HOST_POST_PAIRS.

Could anyone help me please. I am stucked.

Thanks
