### ISSUE TITLE
Collider does not detect WebSocket disconnection in some situations

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#15]
https://github.com/GoogleChrome/webrtc/issues/234

jiayliu commented on Nov 21, 2014
There is no heartbeat or ping in the go.net WebSocket impl, so the WebSocket server cannot detect connection drop in some situations, e.g. user network down.

We can switch to a different WebSocket library that supports ping like https://github.com/gorilla/websocket, or implement our own application level ping.

**Comment by VinceOPS** [comment]
Hi @jiayliu 
This thread is quite old but I was wondering if the issue still remains?

I plan to use AppRTC in production for one of my projects, and would love to contribute to improve it.
I made few (small) [commits](https://github.com/VinceOPS/apprtc/commits/master) on my own fork. Not all of them are good for a general use, but still, it may interest the maintainers of the project.

Thanks

**Comment by KaptenJansson** [comment]
I believe this is still an issue since we have not added anything on an application level or changed the websocket library.

**Comment by KaptenJansson** [comment]
But feel free to contribute :=)

**Comment by KaptenJansson** [comment]
Closing due to age.
