### ISSUE TITLE
Dash "-" cannot be used in the room name

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/apprtc#151]
Dash "-" cannot be used in the room name anymore. Most likely happened when the URL format changed from r= to r/.

Might be more characters that are not supported but do not have time to test them all.

**Comment by KaptenJansson** [comment]
E.g.
https://apprtc.appspot.com/r/indexing-sre

**Comment by chuckhays** [comment]
The routing uses the \w character class, which in ASCII matches [A-Za-z0-9_]

https://github.com/webrtc/apprtc/blob/master/src/app_engine/apprtc.py#L571

**Comment by KaptenJansson** [comment]
This was fixed in #208
