### ISSUE TITLE
Getting the dreaded WebSocket open error: WebSocket error

### ISSUE THREAD

**Issue by GQAdonis** [webrtc/apprtc#154]
I am self hosting the AppRtc demo, and I am getting the red banner with the WebSocket open error.  My constants.py has the host pairs set to [my-domain-name]:443.

What am I missing?  I am using Nginx to reverse proxy and simply run the Python script on Ubuntu 14.04 at port 8080.   All WebSocket proxy configuration for Nginx is correct.

Is there another setting I need?

Travis

**Comment by jiayliu** [comment]
Are you hosting the WebSocket server on your domain? If not, you need to
build from https://github.com/webrtc/apprtc/tree/master/src/collider and
run it on your host following the README instructions.

On Fri, May 22, 2015 at 3:54 AM, Travis James <notifications@github.com>
wrote:

> I am self hosting the AppRtc demo, and I am getting the red banner with
> the WebSocket open error. My constants.py has the host pairs set to
> [my-domain-name]:443.
>
> What am I missing? I am using Nginx to reverse proxy and simply run the
> Python script on Ubuntu 14.04 at port 8080. All WebSocket proxy
> configuration for Nginx is correct.
>
> Is there another setting I need?
>
> Travis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/154>.
>



-- 
Jiayang Liu

**Comment by moxiaotong** [comment]
@jiayliu Hello I want you to publish the https://github.com/webrtc/apprtc this webrtc demo extracting good but after the release of Google App Engine SDK this demo you can not find the from apiclient import discovery
ImportError: No module named apiclient

how to fix ?????

**Comment by chuckhays** [comment]
@moxiaotong your question looks like a separate issue, can you create a new issue to discuss it?

**Comment by juberti** [comment]
Closing as obsolete.
