### ISSUE TITLE
Keyboard shortcuts do not update button status

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/apprtc#157]
Try video or audio mute ("c" and "m") and look at the buttons, no change. You can clearly see/hear that the shortcuts work (it's also printed in the console).

**Comment by samdutton** [comment]
Thanks for heads-up – will fix in the next couple of days.

**Comment by samdutton** [comment]
In #66, but looks like I already have commits outstanding for adding robots.txt handler.

@jiayliu PTAL to make sure I've done the icon toggle the right way.

**Comment by juberti** [comment]
Anything more to be done here?

**Comment by samdutton** [comment]
> Anything more to be done here?

No. 

Pressing C or M keys mute video/audio and change the button icons as expected.

**Comment by KaptenJansson** [comment]
Thanks for fixing!
