### ISSUE TITLE
Investigate CEOD errors for latest master revision (65a51d75b7eb4afe41e4006e8d317a69fecf6b41)

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/apprtc#158]
The last two pull request (#155 and #156) were meant to reduce false CEOD alerts but after deploying those CEOD alerts started appearing, if they are false or not I'm not sure but I've reverted back to the previous version for now until we can we can determine if CEOD alerts are true or false.

**Comment by jiayliu** [comment]
The push did reduce the frequency of the false alert:

With the new code, from 5/25 5:30am to 5/26 12:30am (~19hr), 4 alerts were
sent to apprtc-alert@.

After the revert, from 5/26 12:30am to 5/27 12:00am (~24hr), 26 alerts were
sent to apprtc-monitor@.

I think we should revert the revert.


On Tue, May 26, 2015 at 1:38 AM, Christoffer Jansson <
notifications@github.com> wrote:

> Assigned #158 <https://github.com/webrtc/apprtc/issues/158> to @jiayliu
> <https://github.com/jiayliu>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/158#event-313543646>.
>



-- 
Jiayang Liu

**Comment by KaptenJansson** [comment]
Done, latest Master is serving on GAE now.
