### ISSUE TITLE
Add new stream and constrains to the webrtc sesion

### ISSUE THREAD

**Issue by juliankmazo** [webrtc/apprtc#159]
Hi, this is not an issue. I just want to know how can I add new streams to the session.

I'm using https://www.webrtc-experiment.com/getScreenId/ and I want to add this new stream to the webrtc session.

I also would like to know how can I update the constrains (resolution) in the middle of a session.

Thanks

**Comment by juberti** [comment]
Please ask general WebRTC questions on the discuss-webrtc@googlegroups.com mailing list.
