### ISSUE TITLE
Handle AppRTC user network disconnection without rejoining the room (ICE Restart)

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#16]
https://github.com/GoogleChrome/webrtc/issues/232

jiayliu commented on Nov 21, 2014
When the connection is temporarily interrupted, the client should initiate ICE restart and reconnect to the signalling server.

**Comment by juberti** [comment]
Didn't realize we never implemented ICE restarts. I just hit this today in an AppRTC call.

**Comment by KaptenJansson** [comment]
Closing due to age.
