### ISSUE TITLE
What is the use of Room Server, WSS and WSS Post URLs?

### ISSUE THREAD

**Issue by ngchengpiaw** [webrtc/apprtc#160]
Can we completed them into one URL?

**Comment by ngchengpiaw** [comment]
Sorry, I mean 'Can we combined them into one URL?

**Comment by chuckhays** [comment]
Room server is the signaling server that coordinates the clients. WSS is the web socket server, and wssposturl is used to send messages to the websocket if it isn't fully opened/connected yet, as well as deleting the web socket when it is done.

They could plausibly be combined, but the way the servers are currently implemented it would be difficult.

**Comment by aktywnitu** [comment]
I don't use GAE. Can I use this serwers - apprtc-ws.webrtc.org:443 and  stun.l.google.com:19302?
Please let me know how implement my custom servers to start in production to be compatibile with apprtc code. I think that I can'not simly use for example https://github.com/andyet/signalmaster node server or other, becouse of protocol differences.

**Comment by juberti** [comment]
You can use stun.l.google.com, but not apprtc-ws.
