### ISSUE TITLE
WebSocket.CONNECTING is not standard

### ISSUE THREAD

**Issue by ibc** [webrtc/apprtc#163]
The [WebSocket API](http://www.w3.org/TR/2011/WD-websockets-20110419/) does not define `WebSocket.CONNECTING` at all. Instead `CONNECTING`, `OPEN` , etc are read properties of a WebSocket instance.

So instead of `this.readyState = WebSocket.CONNECTING;` do `this.readyState = this.websocket_.CONNECTING;` and so on.

**Comment by KaptenJansson** [comment]
@jiayliu FYI

**Comment by KaptenJansson** [comment]
Closing due to age.
