### ISSUE TITLE
Custom signaling server

### ISSUE THREAD

**Issue by aktywnitu** [webrtc/apprtc#165]
Hi,

Can you write some instructions how implement custom  signaling server?

For TURN and STUN server should be no problem - it don't depend from apprtc code, right?
So I am going to use http://code.google.com/p/rfc5766-turn-server/

Apprtc code use some communication protocol to comunicate beetwen peers and google signaling server.
Can you document this protocol?

**Comment by juberti** [comment]
The protocol is fairly simple, and should be possible to reverse-engineer from the code.
