### ISSUE TITLE
Failed to set local answer sdp - error from yesterday

### ISSUE THREAD

**Issue by aktywnitu** [webrtc/apprtc#166]
States:     
Signaling:  stable
Gathering:  complete
Connection: new
Local:      host:2 relay:6
Remote:     host:4 srflx:8 relay:12

Stats:      
Call time:  01:20
Setup time: 0 ms
Audio Tx:   , - bps, - pps
Video Tx:   VP8, 0p0, - bps, - pps
setLocalDescription: Failed to set local answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to add send stream ssrc: 1663072100.

Version:    
gitHash:    65a51d75b7eb4afe41e4006e8d317a69fecf6b41
branch:     master
time:       Fri May 22 09:40:39 2015 -0700

Initiator: Chrome Version 43.0.2357.81
Guest: Chromium Version 37.0.2062.120 Built on Debian 7.6, running on Debian 7.8

I tested app successfully from one week, but from yesterday i see this error.

**Comment by aktywnitu** [comment]
Connecting from the same browser process works - initiator and guest in different broswer tabs.
Also works when:
Initiator is: Iceweasel 31.7.0
Guest is: Chrome  43.0.2357.81

**Comment by KaptenJansson** [comment]
Most likely Chrome version 37 had something to do with it, a good rule of
thumb: always try the latest stable Chrome release when trying these things
out.

**Comment by aktywnitu** [comment]
Yes, I can see the same error in other broswers combinations.
If I will see it in edge versions I will notice.

**Comment by juberti** [comment]
Closing as obsolete.
