### ISSUE TITLE
Error getting user media - initiator chrome, guest firefox

### ISSUE THREAD

**Issue by aktywnitu** [webrtc/apprtc#167]
Connecting from the same browser process works - initiator and guest in different broswer tabs.
Also works when:
Initiator is: Iceweasel 31.7.0
Guest is: Chrome  43.0.2357.81

When I try in oposite way:
Initiator is: Chrome  43.0.2357.81
Guest is:  Iceweasel 31.7.0

I see in Iceweasel error:
"5.403: Error getting user media: undefined" apprtc.debug.js.pagespeed.jm.le-GO32eTq56uECGa3-X.js:1
"5.406: getUserMedia error: Failed to get access to local media. Error name was undefined. Continuing without sending a stream." apprtc.debug.js.pagespeed.jm.le-GO32eTq56uECGa3-X.js:1

The same problem is where I use Firefox Developer Edition 39.0a2 instead Iceweasel.
Maby it is becouse of camera i used by other browser, but when a guest is Chrome all works properly.

**Comment by KaptenJansson** [comment]
Yes, if the camera is in use by a different process it will be unattainable for other processes.
