### ISSUE TITLE
DataChannel implementation

### ISSUE THREAD

**Issue by Ponsen** [webrtc/apprtc#168]
Hello,

I've been trying to implement datachannel functionality with the help of some tutotials, but unfortunately nothing worked so far. As a standalone project I have successfully enabled the channel. How can I implement the datachannel into this project?

**Comment by aktywnitu** [comment]
I am aslo interested.

**Comment by KaptenJansson** [comment]
Maybe the datachannels [samples](https://github.com/webrtc/samples/tree/master/src/content/datachannel) in the samples/ repo can be of some help?
