### ISSUE TITLE
TURN_BASE_URL

### ISSUE THREAD

**Issue by bigrender** [webrtc/apprtc#169]
I setup python version && nodejs server .
Both are running well..
but when i try to  http://128.199.104.57:3000/
Response " NO TURN SERVER "
Maybe TURN_BASE_URL make some this problem.

 TURN_BASE_URL: 'https://computeengineondemand.appspot.com',
  TURN_URL_TEMPLATE: '%s/turn?username=%s&key=%s',
  CEOD_KEY: '4080218913',

This is not work at all.

another sample. I referece . 

http://io.diveinedu.com/2015/02/05/%E7%AC%AC%E5%85%AD%E7%AB%A0-WebRTC%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%90%AD%E5%BB%BA.html

TURN_BASE_URL = 'http://apprtc.diveinedu.com'
TURN_URL_TEMPLATE = '%s/turn?username=%s&key=%s'
CEOD_KEY = 'diveinedu'

this is working well..

I would like to use  https://computeengineondemand.appspot.com or own custom webserver.

If someone know how to fix this issue. 

let me know thanks.

**Comment by KaptenJansson** [comment]
Why do don't you setup your own turn server as mentioned in the article you
linked? It provides instructions for how to install and setup a turn
server. Try that and host it on your own server.

**Comment by aktywnitu** [comment]
Hi bigrender,

Are some infos in browser console with " „Same Origin Policy” sentence?
Possibly, that your app and server are on different domains.

**Comment by narutoinfo** [comment]
http://apprtc.diveinedu.com/turn.php?username=048645111&key=diveinedu
{
	"username":"1436436296:048645111",
	"password":"MzFiMTU3MGM1NDExNTVlZjNhNDk0NjYwODk3MzNmMjA0NzhjODA4Mw==",
	"uris":[
		"stun:faq.quduiba.com:4478",
		"turn:faq.quduiba.com:4478"
		]
}
for get this

**Comment by eskalera** [comment]
Hi everyone,

I'm stuck in the same problem. Can anyone help?

narutoinfo, I've reached that example from diveinedu a thousand times from different places, but it's in japanese. Is it a free TURN server ready to use?

**Comment by KaptenJansson** [comment]
I assume you have to setup it on your own hosted server, i.e. software is most likely free but it's not hosted publicly for free use.

**Comment by juberti** [comment]
CEOD is not provided as a free TURN resource. You'll need to run your own instance (or have someone run one for you, e.g. feixiao's comment)
