### ISSUE TITLE
Fix glitches detected by Page Speed Insights

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#17]
https://github.com/GoogleChrome/webrtc/issues/223

samdutton commented on Nov 18, 2014
Page Speed Insights suggests a few fairly simple changes for apprtc.appspot.com.

We should implement these fixes.

**Comment by jiayliu** [comment]
The remaining issuses are:
1. Loading css blocks page rendering. I don't think we can fix this since our css file is pretty large and not suitable to inline.
2. Set expiration time for static files. It seems we are already doing it, e.g. the css has a 1y expiration time.

So I don't think there is anything actionable right now.

**Comment by samdutton** [comment]
We could inline the CSS during the build process, but I'm not convinced
this is worth it. I did a test for this a while back - I'll dig out the
email.

**Comment by juberti** [comment]
Closing.
