### ISSUE TITLE
STUN instead TURN server

### ISSUE THREAD

**Issue by aktywnitu** [webrtc/apprtc#174]
How can I set STUN server url?
I see only TURN_BASE_URL in constants and ts in GET params.

And other question: I see in my console "Same origin policy" error, when i test apprtc in localhost, which is normal.  So i need set Access-Control-Allow-Origin to my domain in turn/stun server response header, right?

So it is possible test some servers from below public list?
https://gist.github.com/yetithefoot/7592580

**Comment by juberti** [comment]
See http://gingertech.net/2014/03/19/apprtc-googles-webrtc-test-app-and-its-parameters/
(ss= parameter)
