### ISSUE TITLE
Access-Control-Allow-Origin Problem in Fetching TurnServer

### ISSUE THREAD

**Issue by santhosh-kumar** [webrtc/apprtc#175]
I have copied the apprtc code to host it on my own GAE server (Python). I see the following error on the Javascript console. How do I fix this?

XMLHttpRequest cannot load https://computeengineondemand.appspot.com/turn?username=781166553&key=4080218913. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://<my-server-name>.appspot.com' is therefore not allowed access.

I have tried the following in my response handler:
self.response.headers ['Access-Control-Allow-Origin'] = "*"

But I still have a problem. Any suggestion?

**Comment by aktywnitu** [comment]
You must artr your own TURN server like coturn.
You must not use google server bandwitch so request is blocked from other domains.

**Comment by santhosh-kumar** [comment]
Thanks for the response. Is there a list of components that one has to service on their own to support apprtc on their own server? For example,

1) TURN Server (Could use coturn, does google app engine support it?)
2) ?

Appreciate your help!

**Comment by KaptenJansson** [comment]
You need:
1. Host the AppRTC web app on a Google App Engine instance
2. Host a signalling solution, e.g. Collider a websocket based signal server running on Google Compute Engine.
3. Host a turn server like [Coturn](https://github.com/coturn/coturn) or [rfc5766-turn-server](https://github.com/coturn/rfc5766-turn-server/). E.g. Coturn has instructions on how to install it [here](https://github.com/coturn/coturn/blob/master/INSTALL), then just find a hosting solution that can host an environment that it supports.

**Comment by GaetanoCarlucci** [comment]
As workaround, in Chrome,  you can use this extension: https://chrome.google.com/webstore/detail/cors-toggle/omcncfnpmcabckcddookmnajignpffnh?hl=en
