### ISSUE TITLE
Flip the video tag/canvas upon a successful connection, not when video is streaming.

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/apprtc#177]
Currently apprtc flips the video tag once video is flowing from the other side, if the other side is not sending a video stream for some reason it never flips yet the call is connected, audio is flowing in both directions and video is sent to the other participant.

I think we should flip the video tag/canvas (have not checked what we exactly "flip") when the connection is established to indicate when the call is established regardless of the video state.

**Comment by juberti** [comment]
We should time out and flip if no video arrives, but I think it's important not to transition to what appears to be the fully-connected state until the call is fully live. I think there is another bug open on the no-video-stream case.
