### ISSUE TITLE
How is the apprtc signaling implemented and deployed?

### ISSUE THREAD

**Issue by santhosh-kumar** [webrtc/apprtc#179]
I see that Go based collider software is also included as part of the project. Is that used for signaling? If so, how and where is it deployed?

Thanks.

**Comment by KaptenJansson** [comment]
Yes, [Collider](https://github.com/webrtc/apprtc/tree/master/src/collider) is a websocket based signalling server written in Go. It's currently hosted on [Google Compute Engine](https://cloud.google.com/compute/?utm_source=google&utm_medium=cpc&utm_campaign=2015-q1-cloud-emea-gce-bkws-freetrial-en) as a VM instance.
