### ISSUE TITLE
Json error seen in a two way apprtc call and the loopback apprtc call

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/apprtc#181]
1. Join a two way apprtc call between any chrome device and the desktop
2. Check to see the errors or warnings in the js console of the chrome device user
3. Join a loopback apprtc call in any of the chrome devices
4. Check again to see the errors or warnings in the js console of the chrome device user

Expected Result:
There should be no errors or warnings or any JSON errors seen

Actual Result: 
There is the error message as seen in the screenshot, but there is no problem with the audio and video functionality
![screenshot 2015-07-28 at 2 32 08 pm 1](https://cloud.githubusercontent.com/assets/9001606/8944590/6d8ac680-3536-11e5-9256-e275b171c6c5.png)

**Comment by KaptenJansson** [comment]
This is partly fixed, the handler has been added however as you can see the URL is incorrect, manifest.json should not be requested from `https://apprtc.appspot.com/r/manifest.json`, rather `https://apprtc.appspot.com/manifest.json`

**Comment by KaptenJansson** [comment]
@samdutton FYI

**Comment by KaptenJansson** [comment]
This is now fixed, closing issue. Please let me know how you still have issues.

**Comment by selavazhagan** [comment]
When i tried to do a two way apprtc call between Jaq and the desktop, i wasn't able to see any console logs in the Desktop nor the device Jaq.   The error message in Jaq is seen as in the screenshot attachment. 
![screenshot 2015-08-10 at 1 22 39 pm](https://cloud.githubusercontent.com/assets/9001606/9183286/0af238aa-3f63-11e5-9eeb-73f2e3d1be5e.png)

**Comment by selavazhagan** [comment]
The above comment was entered based on the results seen in the device Jaq using the build 46.0.2472.0/7349.0.0 dev

**Comment by KaptenJansson** [comment]
Thanks for reporting, I will create a new bug for this as it's a different error.

**Comment by samdutton** [comment]
Attempted fix in #188.
