### ISSUE TITLE
Update reference to websocket

### ISSUE THREAD

**Issue by fredlebel** [webrtc/apprtc#184]
`collider.go` still references the old `code.google.com` repo which hasn't been updated since Dec 4th.

A fix was merged recently for handling PONG frames which fixes a compatibility issue with IE11 and WinJS.

**Comment by KaptenJansson** [comment]
https://golang.org/doc/go1 still references `code.google.com/p/go.net/websocket` for import however https://godoc.org/golang.org/x/net/websocket references `golang.org/x/net/websocket`. 

I guess we can update the reference and import a newer version if there are added benefits, need to take a look.

I'm curious, why do you specifically mention a fix for IE11 and WinJS in this project?

**Comment by fredlebel** [comment]
There's a fix for handling unsolicited pong messages in a websocket.

See: https://github.com/golang/go/issues/6377

**Comment by fredlebel** [comment]
Any chance this can get done soon?

**Comment by fredlebel** [comment]
Now mid-October.  Where do we stand on this fix?

**Comment by KaptenJansson** [comment]
Sorry for letting this slip.

Will this do:
`import (
	"code.google.com/p/go.net/websocket"` > `import (
	"golang.org/x/net/websocket"`

**Comment by fredlebel** [comment]
It expect it would.  Once it's committed and goes live we'll test the fix against the public server.

Thank you

**Comment by KaptenJansson** [comment]
Please try this out and let me know.

**Comment by fredlebel** [comment]
Thank you.  Any idea as to when the public AppRTC server will pick up these changes?

**Comment by KaptenJansson** [comment]
It's now being served, please give it a try and let me know how it works out.

**Comment by fredlebel** [comment]
Now it's working fine.  Thank you.  That fixed it.

**Comment by KaptenJansson** [comment]
Excellent!
