### ISSUE TITLE
Server response 404 error is seen in the test.webrtc.org run

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/apprtc#186]
Environment: 46.0.2472.0/7338.0.0 dev in Peppy
![screenshot from 2015-08-10 15 29 18](https://cloud.githubusercontent.com/assets/9001606/9186012/ebd0931e-3f75-11e5-9e5b-d76bc0cc5ee9.png)

Steps:
1. Go to https://test.webrtc.org and click on Start
2. Look for the results

Expected Results:
There should not be any errors seen in the console logs, when the run is complete, but instead i do see the error message as seen in the screenshot

**Comment by KaptenJansson** [comment]
Wrong repo, should be filed under testrtc repo. Filed as https://github.com/webrtc/testrtc/issues/113.
