### ISSUE TITLE
Add GAE push-to-deploy for AppRTC

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#19]
https://github.com/GoogleChrome/webrtc/issues/101

juberti commented on Sep 16, 2014
I would like to be able to automatically push master to AppRTC prod, instead of having to use appcfg.
See https://developers.google.com/cloud/devtools/repo/push-to-deploy.
Vikas Marwahamarwahvikas was assigned by juberti on Sep 16, 2014
Vikas Marwaha
 Owner
marwahvikas commented on Sep 16, 2014
Okay will start looking into it.
Justin Ubertijuberti added the apprtc label on Oct 16, 2014
Vikas Marwahamarwahvikas removed their assignment on Oct 28, 2014
Sam Duttonsamdutton was assigned by marwahvikas on Oct 28, 2014
Vikas Marwaha
 Owner
marwahvikas commented on Oct 28, 2014
Hi Justin/Sam
So in apprtc i have setup a release pipeline. I have connected the apprtc project in google developer console to the github webrtc project. See here :-
https://console.developers.google.com/project/apprtc/clouddev/pipelines?authuser=0

Now if i understand correctly it should trigger the release pipeline if we push anything to master. 
As per the doc(https://cloud.google.com/tools/repo/push-to-deploy) :
If you are pushing to the repository via a repository on GitHub, use the following:
git push 'remote' master
where 'remote' is the remote name for the repository on GitHub.
I have not tested if the release pipeline is actually working. Do you guys want to give it a try?

/Vikas
Sam Dutton
 Owner
 samdutton commented on Oct 29, 2014
Excellent! This seems like a very sensible way to deploy apprtc.
…
André Susano Pinto
 Owner
andresusanopinto commented on Oct 29, 2014
This seems to use a different mechanism than the app-engine push to deploy. Would it be possible to set up a release pipeline for test-rtc as well?
Vikas Marwaha
 Owner
marwahvikas commented on Oct 29, 2014
hi andre, thats right. Do we have test-rtc as a project in google developer's console? https://console.developers.google.com/project?authuser=0

**Comment by KaptenJansson** [comment]
@MirkoBonadei maybe this is something we can look at in the next quarter?

**Comment by KaptenJansson** [comment]
Closing due to age.
