### ISSUE TITLE
Is there any way to always allow camera and mic in Chrome?

### ISSUE THREAD

**Issue by AdamWorld** [webrtc/apprtc#190]
Hi.
When i enter https://localserver:8080/r/room_id, Chrome always asks permission for the use of camera and mic.
Is there any way to always allow them?

Thank you,
Regards,

**Comment by maxzeroedge** [comment]
It asks once for a domain hoated on web, but each time for domain hosted on
localhost

**Comment by AdamWorld** [comment]
it asks everytime for global ip (amazon server).

**Comment by KaptenJansson** [comment]
HTTPS is sticky while HTTP is not. 

Check chrome://settings/contentExceptions#media-stream-camera and chrome://settings/contentExceptions#media-stream-mic to see that the permissions are set to allow (for HTTPS) for the domains your are using,

**Comment by AdamWorld** [comment]
yes, https asks only once but http asks permission every time and no way to include exception.

**Comment by KaptenJansson** [comment]
That's by design.

**Comment by KaptenJansson** [comment]
Actually, getUserMedia will only be available via HTTPS in some point I believe. You can already see a warning about it in Chrome.

**Comment by AdamWorld** [comment]
thank you very much.
