### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by hdavy2002** [webrtc/apprtc#196]
When I do 'build grunt', it gives me these error. Installing Java does not help. I am using Ubuntu 14.10

The only change I made away from your tutorial was:
a) When I installed nodejs using **sudo apt-get install nodejs.** It did not install npm. So I manually installed npm via **apt-get install npm**

That is the only difference, the rest I followed to the point.

admin@circledisk:~/apprtc-master$ sudo grunt build
Running "shell:buildAppEnginePackage" (shell) task
[Errno 2] No such file or directory
[Errno 2] No such file or directory

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/adapter.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Fatal error: **Java is not available, neither the bundled nor a global one.**
admin@circledisk:~/apprtc-master$ 

**UPDATE**
I managed to fix the Java path etc. 

Then it asked me to use force, so I used **grunt --force build**

Then it said finished but with these errors. Not sure if it is fatal. Please check.

admin@circledisk:~/apprtc-master$ sudo grunt --force build
Running "shell:buildAppEnginePackage" (shell) task
[Errno 2] No such file or directory
[Errno 2] No such file or directory

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/adapter.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: Error: Unable to access jarfile /home/admin/apprtc-master/node_modules/grunt-closurecompiler/node_modules/closurecompiler/compiler/compiler.jar
 Used --force, continuing.

Running "grunt-chrome-build:apprtc" (grunt-chrome-build) task
Chrome packaged app build.
Deleting buildDir: out/chrome_app
>> Cannot delete nonexistent file.
Creating empty buildDir: out/chrome_app
Copying resources to buildDir: out/chrome_app
src/web_app/chrome_app/manifest.json-->out/chrome_app/manifest.json
out/app_engine/js/loopback.js-->out/chrome_app/js/loopback.js
out/app_engine/css/main.css-->out/chrome_app/css/main.css
out/app_engine/images/apprtc-128.png-->out/chrome_app/images/apprtc-128.png
out/app_engine/images/apprtc-16.png-->out/chrome_app/images/apprtc-16.png
out/app_engine/images/apprtc-22.png-->out/chrome_app/images/apprtc-22.png
out/app_engine/images/apprtc-32.png-->out/chrome_app/images/apprtc-32.png
out/app_engine/images/apprtc-48.png-->out/chrome_app/images/apprtc-48.png
src/web_app/js/background.js-->out/chrome_app/js/background.js
src/web_app/js/appwindow.js-->out/chrome_app/js/appwindow.js

Running "grunt-chrome-build-transform" task
Transforming files using jinja.

Running "jinja:chrome-build" (jinja) task
Using context web_app/html/index_template
File "out/chrome_app/appwindow.html" created.

Running "grunt-chrome-build-compress" task
Creating zip file:out/chrome_app/apprtc.zip

Running "compress:chrome-build" (compress) task
Created out/chrome_app/apprtc.zip (28611 bytes)

Running "grunt-chrome-build-package" task
Skipping creation of Chrome package.

Done, but with warnings.
admin@circledisk:~/apprtc-master$ 

**Second Update**

Cannot run it. This is what I get.

admin@circledisk:~/google_appengine$ /home/admin/google_appengine/dev_appserver.py ./out/app_engine
Traceback (most recent call last):
  File "/home/admin/google_appengine/dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "/home/admin/google_appengine/dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/home/admin/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in <module>
    main()
  File "/home/admin/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1026, in main
    dev_server.start(options)
  File "/home/admin/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 752, in start
    options.config_paths, options.app_id)
  File "/home/admin/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 795, in __init__
    module_configuration = ModuleConfiguration(config_path, app_id)
  File "/home/admin/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 123, in __init__
    self._config_path)
  File "/home/admin/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 391, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: './out/app_engine'
admin@circledisk:~/google_appengine$

**Comment by phoglund** [comment]
What solved the problem? :)
