### ISSUE TITLE
apprtc doesn't flip local view window on firefox 

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#20]
https://github.com/GoogleChrome/webrtc/issues/51

marwahvikas commented on May 29, 2014
Moving issue 1380 (https://code.google.com/p/webrtc/issues/detail?id=1380) to github.

**Comment by juberti** [comment]
@marwahvikas can you retest this? I think this has been resolved.

**Comment by marwahvikas** [comment]
Sure Justin, let me give it a try.

**Comment by marwahvikas** [comment]
Tested on FF 34.05 on Mac with apprtc demo the local preview seems to be flipping similar as it happens in chrome. Looks fine to me.
