### ISSUE TITLE
Mute/UnMute Audio/Video option enabled for "Video only"/"Audio only" call respectively

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#202]
Description:
When the user makes an appRTC call with "audio=false&video=true" (or "audio=true&video=false") parameters, he/she sees that the "Mute audio" / "Mute Video" icon can be toggled on/off respectively.

Steps to reproduce:
1. Append "audio=false&video=true" (or "audio=true&video=false") parameters to an appRTC call and click Join.
2. Hover over the "Mute audio" / "Mute Video" icons and toggle them on/off 
Sample Test page - https://apprtc.appspot.com/r/862942399?audio=false&video=true

Actual results:
The user is able to mute/unmute Audio on a "Video only" call (and/or) mute/unmute Video on an "Audio only" call  

Expected results:
- Audio icon should be disabled/invisible for a Video only call
- Video icon should be disabled/invisible for an Audio only call

**Comment by KaptenJansson** [comment]
Thanks for reporting this!

**Comment by KaptenJansson** [comment]
@samdutton is this something you want to take a look at?

**Comment by samdutton** [comment]
Sure — I can take a look.
