### ISSUE TITLE
Add notification when apprtc ignores unrecognized URL parameters

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#204]
Steps to reproduce:
1. Start an apprtc call with "?debug=loopbck" (the spelling error is intended). 
2. Click on Join

Actual results:
It allows the user to join the room and waits for someone else to join. 
Screenshot: https://drive.google.com/a/google.com/file/d/0BzGe6sHDtMDKQTBYMU13d0FfMVE/view?usp=sharing

Expected result:
It'll be nice to have something shown in the UI or console error message, when such unrecognized parameters are being ignored.

**Comment by KaptenJansson** [comment]
Closing due to age.
