### ISSUE TITLE
Merge latest adapter.js release

### ISSUE THREAD

**Issue by tednakamura** [webrtc/apprtc#209]
Note that this is dependent on https://github.com/webrtc/adapter/issues/148

**Comment by tednakamura** [comment]
Reopening because I'm still seeing older Chrome detection logic in the version of adapter.js used by apprtc.
https://github.com/webrtc/apprtc/blob/master/src/web_app/js/adapter.js#L230 currently shows:
```
} else if (navigator.webkitGetUserMedia && !!window.chrome) {
  webrtcUtils.log('This appears to be Chrome');
```

While the same lines in the [v0.2.5 adapter.js release](https://github.com/webrtc/adapter/blob/v0.2.5/adapter.js) shows (emphasis added)
```
} else if (navigator.webkitGetUserMedia && window.webkitRTCPeerConnection) {
  webrtcUtils.log('This appears to be Chrome');
```

As a result, WebView requests to apprtc are still failing to be detected as Chrome.

**Comment by niklasenbom** [comment]
I still get "Browser does not appear to be WebRTC-capable" when running WebView browser

**Comment by KaptenJansson** [comment]
This is due to window.RTCPeerconnection does not exist in WebView. https://github.com/webrtc/adapter/blob/master/adapter.js#L234
