### ISSUE TITLE
SyntaxError when both "hd" and "video" URL parameters are present

### ISSUE THREAD

**Issue by tednakamura** [webrtc/apprtc#211]
Repro steps:
1) Try to start an apprtc call where both the "hd" and "video" URL parameters are set. Example: https://apprtc.appspot.com/?debug=loopback&video=googNoiseReduction=true&hd=true
2) Open the js console

Expected result:
Call starts, though console shows the warning message "The "hd" parameter has overridden video=$video_params"

Actual result:
Call doesn't start, console shows "Uncaught SyntaxError: Unexpected string" 
Clicking that console line entry takes me to a source code listing that looks something like:

`<script type="text/javascript">var loadingParams={errorMessages:[u'The "hd" parameter has overridden video=googNoiseReduction=true'],isLoopback:true,mediaConstraints:{"audio":true,"video":{"optional":[],"mandatory":{"minWidth":"1280","minHeight":"720"}}},offerConstraints:{"optional":[],"mandatory":{}},peerConnectionConfig:{"iceServers":[]},peerConnectionConstraints:{"optional":[{"DtlsSrtpKeyAgreement":false}]},` (remaining text snipped)

**Comment by tednakamura** [comment]
Reopening because https://apprtc.appspot.com/?debug=loopback&video=googNoiseReduction=true&hd=true still doesn't result in a successful call. I still get an effectively blank screen, and the js console has the same error "Uncaught SyntaxError: Unexpected string." This time, that error points to this line in the js source:
```      errorMessages: [u'The "hd" parameter has overridden video=googNoiseReduction=true'],```

**Comment by KaptenJansson** [comment]
Sorry, it's fixed but not pushed yet. Will close once pushed.

**Comment by tednakamura** [comment]
Offline, @KaptenJansson confirmed that the fix was pushed. I then confirmed that https://apprtc.appspot.com/?debug=loopback&video=googNoiseReduction=true&hd=true now establishes a call. And since that still results in a warning about the "hd" parameter overriding the "video" parameter, I also confirmed that the equivalent URL https://apprtc.appspot.com/?debug=loopback&video=mandatory:googNoiseReduction=true,minHeight=720,minWidth=1280 also works. Thank you, @KaptenJansson!
