### ISSUE TITLE
Loopback apprtc console logs shows the error message as seen in the screenshot

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/apprtc#216]
Steps:
1. Join a loopback apprtc call in the device Alex with the build 48.0.2555.0/7614.0.0 dev
2. Check for the errors in the console log

Expected result:  
There should be no errors seen

Actual result:
Call is connected properly, audio and video functions as expected, but i am seeing the error message as seen in the screen shot attached.
![screenshot 2015-11-05 at 11 33 27 am](https://cloud.githubusercontent.com/assets/9001606/10979610/436fbba6-83b2-11e5-9635-d375bee93969.png)

**Comment by KaptenJansson** [comment]
Thanks for reporting!

@samdutton have you changed anything yet on computengineondemand?

**Comment by KaptenJansson** [comment]
Jiayang fixed it by reverting a computeengineondemand push.
