### ISSUE TITLE
Route requests for help.html and params.html to the /html subdir 

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#22]
From juberti's last comment in https://github.com/GoogleChrome/webrtc/issues/315#issuecomment-72776850:

#362 moves params.html to the /html subdir, which is already publicly served. But perhaps we should just update app.yaml to route requests for help.html and params.html to the /html subdir (and move all the html files there)

**Comment by jiayliu** [comment]
This is already done:
http://apprtc.appspot.com/html/params.html
And see app.yaml:
handlers:
- url: /html
  static_dir: html

**Comment by juberti** [comment]
The goal here is to have /params.html serve this (i.e. without the /html/ path)

**Comment by jiayliu** [comment]
fixed
