### ISSUE TITLE
www.appr.tc, apprtc.net, should redirect to appr.tc

### ISSUE THREAD

**Issue by juberti** [webrtc/apprtc#221]
Otherwise, they will have different permissions, cookies, etc.

**Comment by KaptenJansson** [comment]
@samdutton Tis is purely a code change right (no domain owner etc needed)? I assume here https://github.com/webrtc/apprtc/blob/master/src/app_engine/apprtc.py#L535. If so I could take a look in case you do not have cycles to spare.

**Comment by juberti** [comment]
I think we probably want to do this via DNS (and remove that apprtc.net hack), but if for some reason we can't do that, we could do it as you suggest.

@samdutton, can you try the DNS changes first?

**Comment by samdutton** [comment]
I tried DNS changes yesterday — seems broken now for apprtc.net, am chasing
with the domain host.

**Comment by samdutton** [comment]
...and for www.appr.tc, I also tried DNS changes and came up against
problems. Will try again.

**Comment by juberti** [comment]
OK. Maybe we should just have a table in the code and redirect accordingly. We'll need to do this for apprtc.appspot.com anyway.

e.g. REDIRECT_DOMAINS = ['apprtc.appspot.com', 'apprtc.net', 'www.apprtc.net', 'apprtc.webrtc.org', 'www.appr.tc']

**Comment by KaptenJansson** [comment]
I've basically just copied your suggestion, I've not actually tried it yet ;).

**Comment by samdutton** [comment]
Long story short (a lot of support chats with the domain hosting
company...) I have finally, apparently, managed to get www.apprtc.net and
apprtc.net redirecting to https://appr.tc.

Please let me know if any problems with this.

**Comment by KaptenJansson** [comment]
Awesome! Any chance of adding apprtc.appspot.com to that list? ;) Or do we have to use the redirect hack for that?

**Comment by samdutton** [comment]
I think apprtc.appspot.com may have to go in the Python...
