### ISSUE TITLE
bugs.appr.tc should redirect to the issue tracker (similar to bugs.webrtc.org)

### ISSUE THREAD

**Issue by juberti** [webrtc/apprtc#222]
https://github.com/webrtc/apprtc/issues

**Comment by KaptenJansson** [comment]
@samdutton do you think you can fix this? (since you are the owner of the domain).

**Comment by KaptenJansson** [comment]
and maybe #221 at the same time?

**Comment by samdutton** [comment]
Yes. I had a go at this, but got stuck. I'll get back onto it...

**Comment by juberti** [comment]
Sam, did you have a chance to wire this up?

**Comment by juberti** [comment]
While you're messing with DNS, would be good to add this.

**Comment by KaptenJansson** [comment]
@samdutton is this something that the ISP can redirect like you did for the others?

**Comment by samdutton** [comment]
Just to double check — is this the correct destination for bugs.appr.tc?:

bugs.chromium.org/p/webrtc/issues/list

**Comment by KaptenJansson** [comment]
It should be https://github.com/webrtc/apprtc/issues.

**Comment by samdutton** [comment]
Ah — of course.

Onto it.

**Comment by KaptenJansson** [comment]
Ping

**Comment by KaptenJansson** [comment]
We now have redirect in place for https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py#L11. What's the latest on the ISP @samdutton ?

**Comment by KaptenJansson** [comment]
Ping

**Comment by KaptenJansson** [comment]
Closing due to age.
