### ISSUE TITLE
Make VP9 default video codec

### ISSUE THREAD

**Issue by mflodman** [webrtc/apprtc#224]
Chrome M48 contains VP9 support without a flag, we should make VP9 the default apprtc video codec for apprtc and browsers supporting VP9.

**Comment by mflodman** [comment]
Current URL parameter to select VP9:
vsc=101 VP9/90000

**Comment by KaptenJansson** [comment]
Hmm I forgot about this, also do we need to check if it's Chrome?

@andresusanopinto was a bit quick reviewing your PR:(

**Comment by andresusanopinto** [comment]
No need to check it is chrome, it simply moves VP9 to be the first on the list if the codec is present. e.g. ?vsc=VPN-does-not-exists-lala" would still work and fallback to browser default (i.e. VP8).
