### ISSUE TITLE
iframe-apprtc page connects to apprtc.appspot.com rather than appr.tc 

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#225]
Steps to reproduce:
1. Start an apprtc call and join a room in https://appr.tc/ (ex: https://appr.tc/r/Srividya)
2. Open up the iframe-apprtc test page https://test.webrtc.org/manual/iframe-apprtc/
3. Enter the room name (as in step 1) in the iframe window and Join

Actual results:
Notice that the 2-way apprtc call does not get through (the iframe-apprtc page still points to apprtc.appspot.com)

Expected results:
All apprtc.appspot.com calls should be redirected to appr.tc

**Comment by KaptenJansson** [comment]
Thanks for reporting!

FYI this should have been filed in the [testrtc repository](https://github.com/webrtc/testrtc).

**Comment by srnarayanan** [comment]
oops, sorry! and thanks for fixing real quick!
