### ISSUE TITLE
Android WebView Video Keyart

### ISSUE THREAD

**Issue by gauntface** [webrtc/apprtc#226]
Hi all,

I was just updating the sample for this demo: https://github.com/GoogleChrome/chromium-webview-samples

At the moment in https://appr.tc/ there is a div with id videos and at the moment that is sat on top of all content which is an issue on the Android WebView because a piece of key art is added and this results in: 

![device-2015-12-03-170118](https://cloud.githubusercontent.com/assets/139760/11567574/843c1a6a-99df-11e5-8d52-3e1306ececf8.png)

I can get around this in DevTools by applying Opacity: 0 until the video connects.

**Comment by nateridderman** [comment]
This does not happen in Chrome M46 on Android, but I looked at some of the javascript and CSS and it was not clear to me what was different.

**Comment by gauntface** [comment]
I think the difference is simply in how WebView and Chrome handle video media. WebView (to the best of my knowledge) will fallback to the Android Video View while Chrome has it's own media stack.

**Comment by KaptenJansson** [comment]
This is a webview issue/side effect, not AppRTC.

**Comment by gauntface** [comment]
Is there any reason for excluding support for WebView though? The fix is to set an opacity of the view before the webrtc session is set up.

**Comment by KaptenJansson** [comment]
Not at all, PR's are welcome ;).

**Comment by zaxy78** [comment]
@gauntface , can u elaborate on that?
I have a WebRTC app that runs in the Mobile Chrome but not on my app inside a WebView.
The newtowrk connection and streams seems to work, but the video simply wont stream inside the video. I wonder what I'm missing..

**Comment by cjkarande** [comment]
@zaxy78 , even i am facing similar issue. Both Remote video & audio streams are not getting played in the Android Webview. However the Mobile Webview's  streams (Video+Audio) are playing on the remote desktop without any issue.

Requesting WebRTC team to provide a resolution at their earliest as its a Showtopper for Android Webview based use cases.

**Comment by nAkhmedov** [comment]
I have faced this issue(webview is not rendering video) as well, any ideas,

**Comment by nAkhmedov** [comment]
I called `mediaPlaybackRequiresUserGesture` after setting javaScriptEnabled , it works

`        settings.apply {
            javaScriptEnabled = true
            mediaPlaybackRequiresUserGesture = false
        }
`

**Comment by rajesh98** [comment]
```
WebSettings settings = mWebRTCWebView.getSettings();
settings.setJavaScriptEnabled(true);
settings.setMediaPlaybackRequiresUserGesture(false);
```
**It works.**
