### ISSUE TITLE
AppRTC: URL param stereo=true does not result in stereo due to APM still enabled

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#23]
https://github.com/GoogleChrome/webrtc/issues/220#issuecomment-72776788

KaptenJansson commented on Nov 17, 2014
The URL param Stereo=true does not enable stereo all the way (just sets the stereo=1 in the SDP) in chrome unless echoCancellation=false is sent in as an optional gUM constraint.

This is due to the APM does not handle stereo hence it's down-mixed to mono. 
The URL params &stereo=true, audio=echoCancellation=false will result in stereo.

If the intention of stereo=true is to enable proper stereo (not just setting the SDP attribute) it should also pass the audio=echoCancellation=false gum constraint.

juberti commented 15 days ago
Is AEC the only thing that doesn't tolerate stereo? Or does all APM processing have to be disabled? @KaptenJansson can you check with Tina?
Christoffer Jansson
 Owner
 KaptenJansson commented 14 days ago
I believe the APM converts to mono before processing the audio hence it
affects all processing. But I will double check with Tina.
…

**Comment by jiayliu** [comment]
What should be the next step for this?

**Comment by juberti** [comment]
I think it's a little surprising that stereo=1 would disable AEC, so I would perhaps add an infobox warning message saying that stereo=1 also requires audio=echoCancellation=false.

**Comment by longsleep** [comment]
When setting {echoCancellation: false} as audio optional constraint, stereo works. No further constraints required.

**Comment by KaptenJansson** [comment]
Indeed, but the stereo=1 sets the SDP attribute as well (apprtc modifies the SDP).

**Comment by KaptenJansson** [comment]
Closing this as no one else has mentioned this.
