### ISSUE TITLE
Periodic TURN outage at exactly 4pm PST

### ISSUE THREAD

**Issue by juberti** [webrtc/apprtc#239]
12/9 and 12/10, I was in an AppRTC call that died at exactly 4PM (ICE disconnected -> failed). I was using the WebRTC Network Limiter extension to force use of TURN (UDP), so I am pretty sure this is a failure on the TURN server.

I was not able to re-establish the call for several minutes afterwards either.

**Comment by juberti** [comment]
[webrtc_internals_dump (1).txt](https://github.com/webrtc/apprtc/files/58900/webrtc_internals_dump.1.txt)

**Comment by juberti** [comment]
Relevant info from the dump:

 {
     "time": "12/10/2015, 3:58:39 PM",
     "type": "addIceCandidate",
     "value": "sdpMid: , sdpMLineIndex: 0, candidate: candidate:3554690354 1 udp 16785151 104.196.16.66 57246 typ relay raddr 104.132.51.94 rport 40111 generation 0"
    },
    {
     "time": "12/10/2015, 3:58:40 PM",
     "type": "iceConnectionStateChange",
     "value": "ICEConnectionStateConnected"
    },
    {
     "time": "12/10/2015, 3:58:40 PM",
     "type": "iceGatheringStateChange",
     "value": "ICEGatheringStateComplete"
    },
    {
     "time": "12/10/2015, 3:58:49 PM",
     "type": "iceConnectionStateChange",
     "value": "ICEConnectionStateCompleted"
    },
    {
     "time": "12/10/2015, 4:00:04 PM",
     "type": "iceConnectionStateChange",
     "value": "ICEConnectionStateDisconnected"
    },
    {
     "time": "12/10/2015, 4:00:14 PM",
     "type": "iceConnectionStateChange",
     "value": "ICEConnectionStateFailed"
    }

**Comment by KaptenJansson** [comment]
AFAIK there are no actionable items in this issue. Closing.
