### ISSUE TITLE
reconnect to room with the same client id?

### ISSUE THREAD

**Issue by ic5y** [webrtc/apprtc#242]
is it possible to reconnect to the same room with the same client id? tried to hack with the code, with no success :(

**Comment by KaptenJansson** [comment]
Have you tried removing the check at https://github.com/webrtc/apprtc/blob/3168981efed7629fabee731a5ee74d3716b50652/src/web_app/js/signalingchannel.js#L87? Could you eloborate on what you have tried and what you are trying to do?

**Comment by ic5y** [comment]
we added a simple chat functionality to a webcall, and we want to handle a situtaion when a user is disconnected, rejoined then want to use the same client id for messaging. tried to modifying the endpoints so i can get post a client id in the url, then it uses that it get_room_parameters but not actually worked

**Comment by KaptenJansson** [comment]
I see, then you have to modify the Collider server as well, I guess you can start here: https://github.com/webrtc/apprtc/blob/master/src/collider/collider/roomTable.go#L83. I'm not sure of all the places you have to modify in order to achieve this but it should be doable.
