### ISSUE TITLE
Room bug with lost internet connection

### ISSUE THREAD

**Issue by iveusss** [webrtc/apprtc#251]
Hello. AppRTC has a bug with reconnecting to the same room.
If i disconnect the internet while talking with my opponent, i can't reconnect to the same room again, but having a message that room is full. The same bug i experience using android, just closing the mozilla or chrome app.
Note: Preferable, I should be the second who connects to the room.
WSS, STUN AND TURN servers using from repo.
I can give some debug information if needed.

Could you add a possibility to disconnect user, if it is not online, or connection timeout please?
Thank you.

**Comment by vremenno** [comment]
I experience the same issue with my setup. I suspect that it can happen due to the turn server not being able to close the session properly or maybe need more time to do so? As far as I know, this never happened at appr.tc, it works just fine. I plan to do more testing on this problem when I get a chance. iveusss, check the TURN server log and see if it works properly.

**Comment by iveusss** [comment]
Appr.tc seems to have the same bug. 

111.888: Signaling state changed to: stable
apprtc.debug.js:38 111.899: Set remote session description success.
apprtc.debug.js:38 111.899: Waiting for remote video.
apprtc.debug.js:38 111.899: Remote stream added.
apprtc.debug.js:38 111.899: ICE connection state changed to: checking
apprtc.debug.js:38 111.909: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:4090310242 1 udp 2122260223 192.168.1.119 41825 typ host generation 0\"}","error":""}
apprtc.debug.js:38 111.914: Remote candidate added successfully.
apprtc.debug.js:38 111.959: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:1921329366 1 udp 1686052607 46.***.***.*** 41825 typ srflx raddr 192.168.1.119 rport 41825 generation 0\"}","error":""}
apprtc.debug.js:38 111.961: Remote candidate added successfully.
apprtc.debug.js:38 112.039: ICE connection state changed to: completed
apprtc.debug.js:38 112.039: ICE complete time: 108744ms.
apprtc.debug.js:38 112.039: ICE connection state changed to: completed
apprtc.debug.js:38 112.040: ICE complete time: 108744ms.
apprtc.debug.js:38 112.066: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:49227043 1 udp 41885439 23.251.129.26 56261 typ relay raddr 46.***.***.*** rport 41825 generation 0\"}","error":""}
apprtc.debug.js:38 112.067: Remote candidate added successfully.
apprtc.debug.js:38 112.072: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:49227043 1 udp 41885439 23.251.129.26 53603 typ relay raddr 46.***.***.*** rport 41825 generation 0\"}","error":""}
apprtc.debug.js:38 112.073: Remote candidate added successfully.
apprtc.debug.js:38 112.128: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:49227043 1 udp 25108223 23.251.129.26 61286 typ relay raddr 46.***.***.*** rport 39535 generation 0\"}","error":""}
apprtc.debug.js:38 112.131: Remote candidate added successfully.
apprtc.debug.js:38 112.207: Remote video started; currentTime: 0.059
apprtc.debug.js:38 112.207: Call setup time: 108912ms.
apprtc.debug.js:38 112.207: reattachMediaStream: blob:https%3A//appr.tc/3e984063-b7f6-46d2-8a84-96b1987ef1d7
apprtc.debug.js:38 123.032: ICE connection state changed to: disconnected
apprtc.debug.js:38 132.995: ICE connection state changed to: failed

**Comment by KaptenJansson** [comment]
My guess there is a timeout here before the client is deregistered from the room, in fact I believe it's 30 seconds. What happens if you try and wait a little longer?

**Comment by KaptenJansson** [comment]
The log above indicates Ice failure, not that the room is full. iceRestart could perhaps help in that case.

**Comment by iveusss** [comment]
Waiting for 30 seconds or longer does not kick the second opponent. By reconnecting to the room from second opponent gives 
Messages:
Room server join error: Registration error: FULL
WebSocket register error: Registration error: FULL

Same problem on appr.tc and apprtc.blogspot.com.

**Comment by KaptenJansson** [comment]
I see, for some reason the client id does not get deregistered after a timeout. Looks like a collider issue.

**Comment by mftaha** [comment]
Team, 
Can't we do something like remove_client(self, client_id), if occupancy = 2 and client exists in the clients list (in add_client)?, then continue re-adding it?

**Comment by TheChuckster** [comment]
I've received FULL messages as well. My solution has been to renegotiate a new room between both peers if it's full.

**Comment by GiacomoSilli** [comment]
Hi guys, any news about this bug?

**Comment by abalibardin** [comment]
Hey guys,

Could you please provide status of this issue ?

**Comment by GiacomoSilli** [comment]
From console log
Here i open the new room:
```
INFO     2016-10-13 15:57:43,062 apprtc.py:551] User 17904196 joined room 11111
INFO     2016-10-13 15:57:43,062 apprtc.py:552] Room 11111 has state ['17904196']
INFO     2016-10-13 15:57:43,067 module.py:788] default: "POST /join/11111 HTTP/1.1" 200 1135
INFO     2016-10-13 15:57:43,631 apprtc.py:476] Saved message for client 17904196:{True, 1} in room 11111, retries=0
INFO     2016-10-13 15:57:43,635 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,649 apprtc.py:476] Saved message for client 17904196:{True, 2} in room 11111, retries=0
INFO     2016-10-13 15:57:43,659 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,673 apprtc.py:476] Saved message for client 17904196:{True, 3} in room 11111, retries=0
INFO     2016-10-13 15:57:43,680 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,684 apprtc.py:476] Saved message for client 17904196:{True, 4} in room 11111, retries=0
INFO     2016-10-13 15:57:43,690 apprtc.py:476] Saved message for client 17904196:{True, 5} in room 11111, retries=1
INFO     2016-10-13 15:57:43,695 apprtc.py:476] Saved message for client 17904196:{True, 6} in room 11111, retries=1
INFO     2016-10-13 15:57:43,698 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,700 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,703 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,712 apprtc.py:476] Saved message for client 17904196:{True, 7} in room 11111, retries=0
INFO     2016-10-13 15:57:43,715 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,732 apprtc.py:476] Saved message for client 17904196:{True, 8} in room 11111, retries=0
INFO     2016-10-13 15:57:43,735 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,754 apprtc.py:476] Saved message for client 17904196:{True, 9} in room 11111, retries=0
INFO     2016-10-13 15:57:43,757 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,779 apprtc.py:476] Saved message for client 17904196:{True, 10} in room 11111, retries=0
INFO     2016-10-13 15:57:43,786 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,793 apprtc.py:476] Saved message for client 17904196:{True, 11} in room 11111, retries=0
INFO     2016-10-13 15:57:43,797 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,800 apprtc.py:476] Saved message for client 17904196:{True, 12} in room 11111, retries=1
INFO     2016-10-13 15:57:43,804 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,809 apprtc.py:476] Saved message for client 17904196:{True, 13} in room 11111, retries=0
INFO     2016-10-13 15:57:43,812 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,914 apprtc.py:476] Saved message for client 17904196:{True, 14} in room 11111, retries=0
INFO     2016-10-13 15:57:43,919 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:43,923 apprtc.py:476] Saved message for client 17904196:{True, 15} in room 11111, retries=0
INFO     2016-10-13 15:57:43,925 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,046 apprtc.py:476] Saved message for client 17904196:{True, 16} in room 11111, retries=0
INFO     2016-10-13 15:57:44,051 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,052 apprtc.py:476] Saved message for client 17904196:{True, 17} in room 11111, retries=0
INFO     2016-10-13 15:57:44,055 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,166 apprtc.py:476] Saved message for client 17904196:{True, 18} in room 11111, retries=0
INFO     2016-10-13 15:57:44,174 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,179 apprtc.py:476] Saved message for client 17904196:{True, 19} in room 11111, retries=1
INFO     2016-10-13 15:57:44,184 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,212 apprtc.py:476] Saved message for client 17904196:{True, 20} in room 11111, retries=0
INFO     2016-10-13 15:57:44,217 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,221 apprtc.py:476] Saved message for client 17904196:{True, 21} in room 11111, retries=0
INFO     2016-10-13 15:57:44,224 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,294 apprtc.py:476] Saved message for client 17904196:{True, 22} in room 11111, retries=0
INFO     2016-10-13 15:57:44,299 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,312 apprtc.py:476] Saved message for client 17904196:{True, 23} in room 11111, retries=0
INFO     2016-10-13 15:57:44,315 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,323 apprtc.py:476] Saved message for client 17904196:{True, 24} in room 11111, retries=0
INFO     2016-10-13 15:57:44,326 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
INFO     2016-10-13 15:57:44,428 apprtc.py:476] Saved message for client 17904196:{True, 25} in room 11111, retries=0
INFO     2016-10-13 15:57:44,431 module.py:788] default: "POST /message/11111/17904196 HTTP/1.1" 200 21
```
I join with my device:
```
INFO     2016-10-13 15:58:32,028 apprtc.py:408] Added client 34719596 in room 11111, retries = 0
INFO     2016-10-13 15:58:32,029 analytics.py:95] Event: {'rows': [{'json': {u'room_id': '11111', u'event_type': u'ROOM_SIZE_2', u'host': '51.254.115.249:8083', u'timestamp': '2016-10-13T15:58:32.029377'}}]}
INFO     2016-10-13 15:58:32,029 apprtc.py:92] Applying media constraints: {'audio': True, 'video': True}
WARNING  2016-10-13 15:58:32,032 apprtc.py:136] Invalid or no value returned from memcache, using fallback: null
INFO     2016-10-13 15:58:32,033 apprtc.py:551] User 34719596 joined room 11111
INFO     2016-10-13 15:58:32,033 apprtc.py:552] Room 11111 has state ['34719596', '17904196']
INFO     2016-10-13 15:58:32,037 module.py:788] default: "POST /join/11111 HTTP/1.1" 200 6742
```
Then i disconnect my device, console show nothing, then i try to reconnect:
```
INFO     2016-10-13 15:59:32,092 apprtc.py:545] Error adding client to room: FULL, room_state=['34719596', '17904196']
INFO     2016-10-13 15:59:32,097 module.py:788] default: "POST /join/11111 HTTP/1.1" 200 46
INFO     2016-10-13 15:59:36,799 module.py:788] default: "POST /bye/11111/34719596 HTTP/1.1" 404 52
```

**Comment by GiacomoSilli** [comment]
Any news?

**Comment by KaptenJansson** [comment]
How do you disconnect? It looks like the disconnect message does not reach the room server.

**Comment by GiacomoSilli** [comment]
I honestly do not remember, but if I'm not mistaken I changed the network or I set the phone to Offline mode

Please log console does not say anything, I tried several times.

Even if you exit and re-enter the room several times, suddenly it breaks down, and it seems full

**Comment by KaptenJansson** [comment]
Disconnecting without an explicit "leave" (e.g. press the leave room button) means you will not send a leave request hence you hit the timeout scenario which is 30 mins.

Exiting and re-entering the room several times might be a race condition issue where the leave request has not had a chance to be processed.

**Comment by GiacomoSilli** [comment]
How can I make sure that the room is closed before the 30 minutes, when I get disconnected unexpectedly?

**Comment by GiacomoSilli** [comment]
I created some rooms 5-6 days ago, and not used anymore, it is still "full"
Any idea how to fix it?

**Comment by KaptenJansson** [comment]
Not sure when I will have time to look at this. But also keep in mind that anyone can create any room hence they could have been created by someone else as well.

**Comment by GiacomoSilli** [comment]
Thanks for your interest, I wait your news,
I have not yet published the app , no one could have created the room these days.
I'm the only one working on it

**Comment by KaptenJansson** [comment]
So you have setup your own AppRTC and Collider instance?

**Comment by GiacomoSilli** [comment]
yes, following your instructions i've installed coturn and collider.
its working good wifi/3g/4g with no problem.
I've only this issue

**Comment by galileomd** [comment]
+1 same issue - my rooms are generated with random characters.. disconnection without explicit leave issued leaves the room 'full'

**Comment by abalibardin** [comment]
+1 the same issue

**Comment by abalibardin** [comment]
Our team have been setup own Collider/Coturn instances, integrate with iOS/Android applications, but the FULL ROOM issue is a blocker for now.
How we can workaround this issue? Please, let me know you thoughts.

**Comment by KaptenJansson** [comment]
Can you describe how your clients disconnect from the room?

**Comment by KaptenJansson** [comment]
I will try to look at this more closely as I know there are cases where Collider does the wrong thing but I would like to understand how clients disconnects when encountering this issue.

Not ETA as of yet though.

**Comment by abalibardin** [comment]
**Positive case:** client disconnects by user action, send a leave request - everything works well
**Negative case:** connection lost, client disconnects without send a leave request, try to reconnect  - fool room issue. 

From point of view, If we will have a chance to send a leave request once connection will be restored it will be great. Clients will be monitor leave requests and will send leave request after reconnect if needed.

**Comment by GiacomoSilli** [comment]
@KaptenJansson 
I would help you with some logs, 
In addition to those I have already posted here, I do not know what to do.
Tell me if you have any specific request
And tell me how to do

**Comment by jorgelp94** [comment]
Hi, any updates on this issue? Does anyone know how to fix this?

**Comment by microblue** [comment]
this is looks a bug.  room server handle is leave: ('/leave/([a-zA-Z0-9-_]+)/([a-zA-Z0-9-_]+)', LeavePage),  however in collider call  roomSrvUrl/bye/xxx/xxx,   I am tring modify collider bye to leave. 

Anyway,  apprtc room server is ugly.   collider looks better!

**Comment by KaptenJansson** [comment]
Closing due to age.

**Comment by lucazin** [comment]
Someone find this solution ?

**Comment by KanwalKhan-20** [comment]
close the peer connection will resolve this issue upto some extent.
i was facing same issue but after closing peerconnection now i can join the same room after 3 or 4 calls
