### ISSUE TITLE
PCMU selected as audio codec for first person in a room

### ISSUE THREAD

**Issue by tednakamura** [webrtc/apprtc#252]
Repro steps with Chrome:
1) Start any apprtc call (i.e. don't join an existing call, and don't have anyone else join the same room)
2) Open chrome://webrtc-internals
3) Expand the ssrc_$num_send section for the outbound audio stream
4) Look at the googCodecName

Expected: Opus
Actual: PCMU

Not sure if this is a real bug or not because
a) sLD clearly shows that Opus is preferred
`m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 126`
...
`a=rtpmap:111 opus/48000/2`
...
`a=rtpmap:0 PCMU/8000`

b) as soon as someone else joins (or if you run a loopback call instead), googCodecName correctly shows Opus

**Comment by KaptenJansson** [comment]
Just tried quickly on M47 Linux and it does not show a codec in send until another joins the room, then it shows opus.

**Comment by tednakamura** [comment]
Ah, I should have mentioned that I was using a Canary channel build (49.0.2620.1?). I'm not sure if what I'm seeing is a Chrome issue, or a quirk of apprtc.

**Comment by KaptenJansson** [comment]
It's not an AppRTC quirk (unless an indirect consequence of some other codec selection or SDP manipulation which should not happen anymore unless a codec is specified ) as there is no "pcmu" in the code (except for in a test).

**Comment by KaptenJansson** [comment]
Closing this as this must be a Chrome issue. Cannot currently reproduce this.
