### ISSUE TITLE
turn/tcp on port 3479 does not work

### ISSUE THREAD

**Issue by fippo** [webrtc/apprtc#253]
it takes quite a while for ice gathering to complete on apprtc. Looks like turn:104.196.16.66:3479?transport=tcp does not work (check e.g. via telnet or use the trickle-ice sample) which makes Chrome wait for a timeout.

UDP on both 3478 and 3479 works as well as TCP on 3478

@KaptenJansson h/t

**Comment by juberti** [comment]
Will be resolved by #219
