### ISSUE TITLE
getting black window after including the libraries

### ISSUE THREAD

**Issue by umar-emo** [webrtc/apprtc#255]
Hi,
Download this code and place this code in my local server wampp/www/file_here
After running that it gives me blank pages please help me.
Thanks in advance.

![capturesaaaaa](https://cloud.githubusercontent.com/assets/10205592/12614732/8a7c79c8-c523-11e5-880c-f2ced004e4fe.PNG)
![captusare](https://cloud.githubusercontent.com/assets/10205592/12614736/8da5980a-c523-11e5-9626-b55af0cb450d.PNG)

**Comment by KaptenJansson** [comment]
Hi,

AppRTC requires Google App Engine in order to run, PTAL at the instructions here https://github.com/webrtc/apprtc/blob/master/README.md.
