### ISSUE TITLE
SSL Implementation

### ISSUE THREAD

**Issue by charbelhass** [webrtc/apprtc#257]
Hello,
I followed your steps in order to run the server.
How can I add an ssl certificate to this server. What i have understood is that google chrome can't run camera and microphone unless the website is https.

Thanks in advance
Regards

**Comment by KaptenJansson** [comment]
It should work as long as you run it on http://localhost:8080.

You have to setup a Stunnel4 instance in front of it.

I will take a look and see if we can create a SSL proxy using node's SSL modules, not sure when I will have time though....

**Comment by charbelhass** [comment]
Hey,
thanks @KaptenJansson for your reply
I successfully implemented Stunnel and it worked
but now i have another issue, an error occurs while accessing the website with https.
Messages:  
Failed to start signaling: Failed to execute 'pushState' on 'History': A history state object with URL 'http://192.168.20.135/r/769453476' cannot be created in a document with origin 'https://192.168.20.135'.

Any idea on how to fix it.
Thanks in advance!

**Comment by KaptenJansson** [comment]
aha we update the URL of the browser after joining the room in AppRTC, this is hard (if possible) when going through a proxy.....

Not sure how to solve that one. But as I said, you should be able to use AppRTC in Chrome and Firefox on http as long as you serve it on localhost:8080 (gum should work).

**Comment by KaptenJansson** [comment]
Closing this for now as I do not have time for this.

But as mentioned, it does work as long as you run the GAE instance on http://localhost:8080.

**Comment by appunnicer13** [comment]
Why don't we make it client level change rather than passing full url and trying to push 
Why can't we pass just room id  in the json instead of room link. I think then updating url won't cause this error . I hope this clears up soon. I haven't poked around in the files yet . But I am sure it won't be a big change.

**Comment by KaptenJansson** [comment]
Feel free to submit a PR, this application is designed for GAE and we have not considered using a development server (that's what dev_appserver.py is) as a production hosting solution.
