### ISSUE TITLE
Add support for EC certs using generateCertificates

### ISSUE THREAD

**Issue by juberti** [webrtc/apprtc#258]
This should modestly improve startup performance.

When creating the peerconnection, should be able to check for the existence of the generateCertificate API, and if present, generate a new EC cert for the PC to use.

**Comment by juberti** [comment]
Henrik B can provide more details.

**Comment by henbos** [comment]
You can do something like this, tell me if you need any help.
```
webkitRTCPeerConnection.generateCertificate({name:"ECDSA",namedCurve:"P-256"}).then(
    // On success
    function(cert) {
      // Create RTCPeerConnection, add "certificates: [ cert ]" to the
      // constructor's parameter (to the RTCConfiguration).
    },
    // On failure
    function() {
      // This will never happen during normal circumstances, crashing here would be fine.
    })
```

**Comment by juberti** [comment]
Looks like an easy addition to PeerConnectionClient in peerconnectionclient.js.

**Comment by juberti** [comment]
There's a bug in this code that causes it to continue to use RSA certs. I blame the reviewer.

**Comment by juberti** [comment]
Ping @KaptenJansson

**Comment by KaptenJansson** [comment]
I'm currently working on it, trickier than I thought due to generateCertificate is using promises (and has return a promise first before creating a peerConnection) while the logic in peerconnectionclient and Call does not. Should be done shortly though.

**Comment by juberti** [comment]
looks good
