### ISSUE TITLE
build collider failed

### ISSUE THREAD

**Issue by TaoistKing** [webrtc/apprtc#267]
Hi, i get the latest version, and i got an error when building collider, please take a look:

rwang@rwang:~/server/apprtc$ go get collidermain
# collider
../collider_root/src/collider/collider.go:55: undefined: tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
../collider_root/src/collider/collider.go:59: undefined: tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**Comment by KaptenJansson** [comment]
I think you might be running an old version of go, check using `go version`. Pretty sure you need 1.4 or higher (I tested with 1.5.3 and it works fine).

**Comment by TaoistKing** [comment]
Thanks @KaptenJansson , I updated  to version 1.6, and the error was gone.
