### ISSUE TITLE
cannot find package "golang.org/x/net/websocket"

### ISSUE THREAD

**Issue by shanglt** [webrtc/apprtc#271]
**cannot find package "golang.org/x/net/websocket"**
when i run the code go get collidermain
it print:
/usr/local/go/src/collider/collider.go:11:2: cannot find package "golang.org/x/net/websocket" in any of:
	/usr/local/go/src/vendor/golang.org/x/net/websocket (vendor tree)
	/usr/local/go/src/golang.org/x/net/websocket (from $GOROOT)
	/usr/local/go/bin/src/golang.org/x/net/websocket (from $GOPATH)

**Comment by KaptenJansson** [comment]
Sorry did not have time to look at this, did it all work out for you? Issues like these are usually an environment issue where Go prerequisites have not been setup properly.

**Comment by supersebek** [comment]
I have the same.

**Comment by abelorian** [comment]
`go get -v golang.org/x/net/websocket`
