### ISSUE TITLE
run collider with tls failed

### ISSUE THREAD

**Issue by TaoistKing** [webrtc/apprtc#272]
Hello,
I'm building a signal service with collider, when i run 
collider_root/bin/collidermain -port=8089 -tls=true,
 it says:
Run: http2: TLSConfig.CipherSuites index 4 contains an HTTP/2-approved cipher suite (0xc030), but it comes after unapproved cipher suites. With this configuration, clients that don't support previous, approved cipher suites may be given an unapproved one and reject the connection.

then it stops. plz help.

**Comment by KaptenJansson** [comment]
Have you tried updating go?

**Comment by zhangyashen** [comment]
Hi,
I comes with the same error, have you resolved it?

**Comment by KaptenJansson** [comment]
What version of Go are you using?

What happens if you remove https://github.com/webrtc/apprtc/blob/master/src/collider/collider/collider.go#L58 and then run it again?

**Comment by michaelluk** [comment]
@zhangyashen @TaoistKing I've got the same issue when I was using Go 1.6. Switch to 1.5.3 and problem solved.

**Comment by KaptenJansson** [comment]
I see, most likely means they are deprecating less secure cipher suits. These were added for iOS i believe, @jiayliu @tkchin do you know if we can remove the cipher suites Go 1.6 complains about?

**Comment by tkchin** [comment]
We can remove unapproved cipher suite as long as all clients support remaining suites. On iOS:

https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html

We care about this line: 

The negotiated TLS connection cipher suite must support forward secrecy (FS) and be one of the following:
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

**Comment by mechazod** [comment]
@TaoistKing , can you help me install on my machine the collider or websocket?

**Comment by mechazod** [comment]
@michaelluk @KaptenJansson I've got the same issue for http2 running on ubuntu server, please help.

**Comment by mechazod** [comment]
It works on any go version but it require one cipher which is "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

And there's a list of bad ciphers that we will avoid https://github.com/bradfitz/http2/blob/b6255645465a25b25f804acb9b3a54009e80c2a4/server.go#L228-L302

**Comment by KaptenJansson** [comment]
@TaoistKing does it work for you using the cipher above?

**Comment by ritaaoun** [comment]
Hello, has this been resolved? I'm having the same issue.

I tried playing around with the order of these lines https://github.com/webrtc/apprtc/blob/master/src/collider/collider/collider.go#L55-61 . Also tried commenting out some of them based on the above conversation... nothing seems to change. Even when I put the 4th line in the first place I got the same message:

Run: http2: TLSConfig.CipherSuites index 1 contains an HTTP/2-approved cipher suite (0xc02c), but it comes after unapproved cipher suites. With this configuration, clients that don't support previous, approved cipher suites may be given an unapproved one and reject the connection.

So I have the line that affects the index... just don't know what to do with that.

**Comment by zhangyashen** [comment]
@ritaaoun  i solved it, following is what i do with my {collider_root}/src/collider/collider.go file:
`        if useTls {
//              config := &tls.Config {
//                      // Only allow ciphers that support forward secrecy for iOS9 compatibility:
//                      // https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/
//                      CipherSuites: []uint16 {
//                              tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
//                              tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
//                              tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
//                              tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
//                              tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
//                              tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
//                              tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
//                      },
//                      PreferServerCipherSuites: true,
//              }
                //server := &http.Server{ Addr: pstr, Handler: nil, TLSConfig: config }

                e = http.ListenAndServeTLS(":8089","/cert/cert.pem", "/cert/key.pem",nil)
                //e = server.ListenAndServeTLS("/cert/cert.pem", "/cert/key.pem")
        } else {
                e = http.ListenAndServe(pstr, nil)
        }

`
and my go version is 1.6

**Comment by ritaaoun** [comment]
Hey @zhangyashen thanks for answering so quickly!
I tried to run what you suggested (commented the import crypto/tls after getting the message " imported and not used: "crypto/tls""), and got: "Run: open /cert/cert.pem: no such file or directory" Do you have any idea why?
I've been following the steps at https://github.com/webrtc/apprtc/tree/master/src/collider#building . Do I need to have certificates? Sorry for probably sounding clueless...
My go version is also 1.6

**Comment by zhangyashen** [comment]
hi ,  @ritaaoun 
Yes ,ofcourse you need a certificate. You can use openssl to create it just  like this:
  openssl req -x509 -newkey rsa:2048 -keyout   /cert/key.pem -out /cert/cert.pem -days 99999 -nodes

**Comment by ritaaoun** [comment]
Thank you @zhangyashen !! Problem finally solved :)
