### ISSUE TITLE
Desktop Chrome and AppRTCDemo doesn't connect

### ISSUE THREAD

**Issue by njovy** [webrtc/apprtc#274]
**Browsers and versions affected**
Chrome Version 48.0.2564.116 (64-bit)

**Description**
I was able to join a room with AppRTCDemo built from latest trunk on two android devices. However, if one peer uses a desktop chrome, it doesn't connect.

**Steps to reproduce**
1. Join a room using desktop Chrome
2. Join the room using AppRTCDemo on Android

**Expected results**
AppRTCDemo should create an Answer and peers should be able to video chat.

**Actual results**
AppRTCDemo creates an Offer while the peer using desktop Chrome is waiting in the same room.

**Comment by KaptenJansson** [comment]
I've now rolled back the new release of AppRTC hence this should now work again. Sorry for the inconvenience Will make sure to test with iOS and Android AppRTC demo clients next time.
