### ISSUE TITLE
fallback to stun server when querying TURN servers fails

### ISSUE THREAD

**Issue by fippo** [webrtc/apprtc#278]
when querying the TURN servers fails (i.e. when https://networktraversal.googleapis.com/v1alpha/iceconfig?key=none return a 404 error) currently everything breaks down and no ice servers are used. In that case, at least the "google stun server" could be used as a fallback.

@KaptenJansson

**Comment by KaptenJansson** [comment]
Made a mistake push, have fixed it. Will add some mechanism to prevent that from happening in the future. Filed #279 to keep track of this.

**Comment by mechazod** [comment]
@fippo Is there a possibilities that we can avail to access the "https://networktraversal.googleapis.com/v1alpha/iceconfig?key=none"?
