### ISSUE TITLE
Access via public network.

### ISSUE THREAD

**Issue by freevital** [webrtc/apprtc#280]
Hello.
I have a few questions:
1) How can I use apprtc via public network (on customer server)?
2) How and where can I get API key?
```
ICE server request error: Status=400, response={
"error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console",
            "url": "https://console.developers.google.com"
          }
        ]
      }
    ]
  }
}
```

**Comment by KaptenJansson** [comment]
1) Yes you can use AppRTC via public networks but you need a TURN (STUN will be suffient in some cases) server for that most likely.

2) This is not a public-ally available ICE server provider service, you need to host your own. I've made a PR [here](https://github.com/webrtc/apprtc/pull/268) where this information is provided. It's still in progress but should have it done soon, the instructions still apply though. Please let me know if anything is unclear.

**Comment by freevital** [comment]
@KaptenJansson All clear. Thanks for your answer.

**Comment by freevital** [comment]
@KaptenJansson  If I use my TURN server, when I should set the options of it?

**Comment by iouss** [comment]
Hi Freevital,

you can just hard code your turn servers directly here : https://github.com/webrtc/apprtc/blob/master/src/web_app/js/call.js#L382

vi apprtc/src/web_app/js/call.js

I put this code in the L374 :
**### `// var turnPromise = null;
var turnPromise = '{"username": "1457776531:396939639", "password": "uWw3UdTYtcFskr6xr6FFn6ub1q4=", "uris": ["turn:@IP of turn server:3478?transport=udp", "turn:@IP of turn server:3478?transport=tcp"]}';


  /*if (shouldRequestTurnServers) {
    var requestUrl = this.params_.turnRequestUrl;
    turnPromise =
        requestTurnServers(requestUrl, this.params_.turnTransports).then(
        function(turnServers) {
         var iceServers = this.params_.peerConnectionConfig.iceServers;
               this.params_.peerConnectionConfig.iceServers =
              iceServers.concat(turnServers);
        }.bind(this)).catch(function(error) {
          if (this.onstatusmessage) {
            // Error retrieving TURN servers.
            var subject =
                encodeURIComponent('AppRTC demo TURN server not working');
            this.onstatusmessage(
                'No TURN server; unlikely that media will traverse networks. ' +
                'If this persists please ' +
                '<a href="mailto:discuss-webrtc@googlegroups.com?' +
                'subject=' + subject + '">' +
                'report it to discuss-webrtc@googlegroups.com</a>.');
          }
          trace(error.message);
        }.bind(this));
  } else {
    turnPromise = Promise.resolve();
  }*/
  return turnPromise;
};
`**
I hope that's right what I did

Regards,
Oussama

**Comment by freevital** [comment]
@iouss Hi. I didn't quite understand. I replaced this line:
[https://github.com/webrtc/apprtc/blob/master/src/web_app/js/call.js#L382](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/call.js#L382)
to this:
`var servers = {"username": "workhint", "password": "workhint", "uris": ["turn:workhint.com:3478?transport=tcp"]};`

And I still get error:
```
ICE server request error: Status=400, response={
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console",
            "url": "https://console.developers.google.com"
          }
        ]
      }
    ]
  }
}
```

**Comment by KaptenJansson** [comment]
The code has changed a little since then, it's probably better to change it [here](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/util.js#L94) instead. Instead of connecting to the iceServerRequestUrl, just hard code the iceServerRequest response like the example in the comments above the `requestIceServers` function linked above.

**Comment by freevital** [comment]
The errors displays in Chrome (Ubuntu). On Windows OS it works, but it doesn't work with HTTPS (via stunnel).

**Comment by KaptenJansson** [comment]
Yes that is a different issue since the logic is built upon it being served on the same URL.

You should not need to use HTTPS for getUserMedia as long as you serve it on localhost:8080.

**Comment by freevital** [comment]
I understand. I don't use localhost, I want to use it on public IP.

**Comment by KaptenJansson** [comment]
Then you need to follow the steps [here](https://cloud.google.com/appengine/docs/python/console/using-custom-domains-and-ssl).
