### ISSUE TITLE
[/src/collider] failed get & install

### ISSUE THREAD

**Issue by mechazod** [webrtc/apprtc#283]
**Description**
Problem on setting up collider on my machine

**Steps to reproduce**
on terminal: go get | install collidermain

**Actual results**
non-standard import "golang.org/x/net/websocket" in standard package "collider"

**Comment by KaptenJansson** [comment]
What version of go are you using? Please try 1.5 and see if it resolves the issue. If it does we might have to look into what's changed.

**Comment by mechazod** [comment]
![screen shot 2016-04-07 at 7 07 53 pm](https://cloud.githubusercontent.com/assets/16739905/14349862/886a826c-fcf8-11e5-8b11-45aba66c60b2.png)

**Comment by mechazod** [comment]
@KaptenJansson I've got the same issue with 1.6 to 1.5, can you share the steps on how to setup collider?

**Comment by mechazod** [comment]
@KaptenJansson  go the issue of my package..
