### ISSUE TITLE
Configuring TURN Server For Apprtc and using it with compute engine

### ISSUE THREAD

**Issue by santhosh-kumar** [webrtc/apprtc#284]
Hello,

I am using coturn with long-term credential (from secure_relay_secret.sh):

PATH="./bin/:../bin/:../../bin/:${PATH}" ../../../bin/turnserver -v --syslog -a -L 127.0.0.1 -L ::1 -E 127.0.0.1 -E ::1 --max-bps=3000000 -f -m 3 --min-port=32355 --max-port=65535 --use-auth-secret --static-auth-secret=logen --realm=north.gov --cert=turn_server_cert.pem --pkey=turn_server_pkey.pem --log-file=stdout -q 100 -Q 300 --cipher-list=ALL $@

I see that that JS is making a request to compute-engine (https://computeengineondemand.appspot.com/turn?username=787340420&key=4080218913) and fetching turn details. 

**Question 1:**

What is the webservice contract between apprtc client and the computeengineondemand.appspot.com/turn? (I am trying to figure out what needs to be done, If I need to implement by myself)

**Question 2 :**

I found that the latest version is making the following web-request:

https://networktraversal.googleapis.com/v1alpha/iceconfig?key=None

What is the use of this? Is this used instead of computeengineondemand.appspot.com/turn? If so, what is the contract to make it work?

**Question 3:**

I know AppRTCDemo (Android example by webrtc) is a different project, however, how is the contract maintained by AppRtc (this project) with them for turn_url?

Thanks.

**Comment by KaptenJansson** [comment]
You need to provide your own ICE server provider like CEOD or network traversal. It replies with a JSON containing TURN servers.

**Comment by sagivo** [comment]
@KaptenJansson i think what @santhosh-kumar is asking is - can we count on this this api for other use than development? can we use these ICE servers in production? same with sockets in  `https://apprtc-ws.webrtc.org`

**Comment by KaptenJansson** [comment]
networktraversal and https://apprtc-ws.webrtc.org are google only API/services sorry.

**Comment by sabaleroshan** [comment]
Hello All,

We have to go through your article and its fantastic... !!

We have already setup STUN and TURN as well as Signalling server on my server, but we got issues related to the connection.

We require your help to set up my servers for voice and video calling.

Please revert on this if you can help us to create the servers on our demands, and please share the price for setting up all the servers

Thanks & Regards,
Roshan.
