### ISSUE TITLE
npm warning & grunt build fail.

### ISSUE THREAD

**Issue by yousky** [webrtc/apprtc#285]
2016-04-07
clean virtual pc (virtualbox)
ubuntu-14.04.4 install

sudo apt-get install nodejs
sudo apt-get install npm
sudo npm install -g npm
sudo apt-get install nodejs-legacy
sudo npm -g install grunt-cli

sudo apt-get install python-webtest

sudo apt-get install git
cd /usr/local/src/
git clone https://github.com/webrtc/apprtc.git
cd apprtc/
npm install
......
npm WARN grunt-htmlhint@0.9.12 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-contrib-compress@0.13.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-closurecompiler@0.9.9 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-jinja@0.3.0 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-contrib-jshint@0.10.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-jstestdriver-phantomjs@0.0.7 requires a peer of grunt@~0.4.0 but none was installed.
......

grunt build
......
src/web_app/chrome_app/manifest.json-->out/chrome_app/manifest.json
Warning: Arguments to path.join must be strings Use --force to continue.
**Aborted due to warnings.**
....

**Fix**
npm cache clean
rm -rf node_modules
rm -rf out
npm install grunt@0.4.1
npm install grunt-htmlhint@0.9.12
vi package.json
"grunt": ">=0.4.5"    to    "grunt": ">=**0.4.1**"
npm install
grunt build
......
**Done, without errors.**
......

**Comment by mechazod** [comment]
@yousky , try to make this command
$ sudo npm install
$ sudo grunt build

It works fine with me, and now my problem was the collider to run signaling

**Comment by yousky** [comment]
Ok now. It is fixed.
Thanks.

**Comment by radhey1994** [comment]
intel@pnp-server-2:~/apprtc$ sudo npm install --proxy https://proxy-chain.intel.com:911

> closurecompiler@1.6.1 install /home/intel/apprtc/node_modules/closurecompiler
> npm run-script configure


> closurecompiler@1.6.1 configure /home/intel/apprtc/node_modules/closurecompiler
> node scripts/configure.js

Configuring ClosureCompiler.js 1.6.1 ...

  Downloading https://dl.google.com/closure-compiler/compiler-latest.tar.gz ...
  ✖ Download failed: Error: connect ETIMEDOUT 172.217.31.46:80

  ✖ Unfortunately, ClosureCompiler.js could not be configured.
    See: https://github.com/dcodeIO/ClosureCompiler.js (create an issue maybe)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! closurecompiler@1.6.1 configure: `node scripts/configure.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the closurecompiler@1.6.1 configure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/intel/.npm/_logs/2018-01-09T07_13_10_192Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! closurecompiler@1.6.1 install: `npm run-script configure`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the closurecompiler@1.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



getting the same error..
Please do the needful help...

**Comment by rizaldimaulidia** [comment]
Hi, Please help I got an error when execute `grunt build`
Error message :
Running "shell:buildAppEnginePackage" (shell) task
Traceback (most recent call last):
  File "./build/build_app_engine_package.py", line 12, in <module>
    import requests
ImportError: No module named requests
Warning: Command failed: python ./build/build_app_engine_package.py src out/app_engine
Traceback (most recent call last):
  File "./build/build_app_engine_package.py", line 12, in <module>
    import requests
ImportError: No module named requests
 Use --force to continue.

Aborted due to warnings.
