### ISSUE TITLE
Bitrate parameters (vsibr, vsbr) don't work.

### ISSUE THREAD

**Issue by taylor-b** [webrtc/apprtc#289]
These parameters result in the SDP being munged, adding fmtp parameters for the VP8 codec. But if the codec used isn't VP8 (it's currently VP9 by default), this doesn't do anything.

**Comment by KaptenJansson** [comment]
vsbr is added as `b=AS`, that works due to being added to the media section but `vsibr` is added to the codec section and in this case for VP8 and is not carried over. 

Thanks for filing!
