### ISSUE TITLE
WebRTC between Chrome and Firefox 

### ISSUE THREAD

**Issue by jonasantonelli** [webrtc/apprtc#290]
**Browsers and versions affected**
Chrome: 49.0
Firefox: 45.0.1

**Description**
WebRTC App is working between chrome to chrome, but when I try between chrome and firefox or vice verse doesn't work. Between firefox to firefox work too!

**Comment by KaptenJansson** [comment]
Could you try Chrome M50 and latest FF? Works for me.

Also could you attach Javascript logs and a dump from chrome://webrtc-internals and about:webrtc in Firefox?

Thanks!
