### ISSUE TITLE
AppRTC doesn't relay media using TCP (or TLS)

### ISSUE THREAD

**Issue by tsahilevi** [webrtc/apprtc#292]
[lumpy-salt-1-webrtc_internals_dump.txt](https://github.com/webrtc/apprtc/files/230450/lumpy-salt-1-webrtc_internals_dump.txt)

[lumpy-salt-1-browser_logs.txt](https://github.com/webrtc/apprtc/files/230455/lumpy-salt-1-browser_logs.txt)

When using AppRTC and limiting the firewalls of both browsers to pass only TCP and TLS traffic, AppRTC doesn't work as advertised and doesn't get the media connected.

I am attaching the browser logs and webrtc-internals dump of one of the two browsers used for this scenario.

**Comment by KaptenJansson** [comment]
Could it be [this](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/peerconnectionclient.js#L333)?
