### ISSUE TITLE
Please add clear documentation and/or a central location for setting default appRTC parameters

### ISSUE THREAD

**Issue by cdcv** [webrtc/apprtc#299]
It is currently very confusing to figure out how to set default parameters for the app (in the code, not in a URL).  Also, it is not clear what the units are for the parameters, or how to set them.  

I would like to request that you please include examples of how to set each parameter, along with units and expected behavior (e.g. to set bitrate, what are the units of the number being passed? kbps? mbps? kilometers/hour?).

Please see:
http://stackoverflow.com/questions/37092046/where-are-apprtc-default-parameters-specified

AppRTC, the webRTC demo app, includes a long list of parameters. These can be set in the URL, as explained: https://apprtc.appspot.com/params.html

Where/how are the default parameters set programmatically within the code?

For example, if we want to change the default timeout (tt) or the default send bitrate (vrbr), where in the appRTC code is this done? It turns out that finding where the parameters are set in the code is not as trivial as it sounds. There doesn't seem to be a central location for parameter defaults, and the logic of where to change default values is not clear even with some code analysis. The parameters are set and reset many times and can be set in many ways, and they are passed via HTTP through different codebases on multiple machines.

I am not in a position to submit a PR for this -- a number of days among several codes still hasn't made it clear.

Thank you.

**Comment by KaptenJansson** [comment]
Parameters from the URL as well as some constants (server params from [constants.py)](https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py) are fetched in [apprtc.py](https://github.com/webrtc/apprtc/blob/master/src/app_engine/apprtc.py#L162) and added to an JSON parameters object which is then in turn added to the [index.html file](https://github.com/webrtc/apprtc/blob/master/src/web_app/html/index_template.html#L131 by the jinja2 templating framework and then passed in as an argument to [AppController constructor](https://github.com/webrtc/apprtc/blob/master/src/web_app/html/index_template.html#L164).

Then the loadUrlParams_ method fetches the URL params and makes it available to the rest of the app [here](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/appcontroller.js#L533). These are then merged with the constants [here](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/appcontroller.js#L97).

I would set the default params in loadUrlParams_, like we have done for codec in the [DEFAULT_VIDEO_CODEC constant](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/appcontroller.js#L539).

Server constants like TURN/ICE server or Websocket signalling is set in [constants.py](https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py).

**Comment by KaptenJansson** [comment]
Did that help?

**Comment by KaptenJansson** [comment]
Ping?

**Comment by KaptenJansson** [comment]
Closing due to nothing actionable in bug.
