### ISSUE TITLE
Add option for framerate

### ISSUE THREAD

**Issue by MariasStory** [webrtc/apprtc#300]
Please add option for setting framerate for getusermedia (camera).

**Comment by KaptenJansson** [comment]
We do support arbitrary constraints via URL params but I can see that it does not longer work for the new style of constraints.

Thanks for filing.

**Comment by MariasStory** [comment]
Any progress?

**Comment by KaptenJansson** [comment]
Sorry have not gotten around to it yet. You could use https://webrtc.github.io/samples/src/content/peerconnection/constraints/ for testing at least. Adding max in https://github.com/webrtc/samples/pull/821.

**Comment by KaptenJansson** [comment]
Closing due to age but URL parameters and getUserMedia constraints most likely need a general overhaul.
