### ISSUE TITLE
Switch between Audio and Video - Android

### ISSUE THREAD

**Issue by alexchengalan** [webrtc/apprtc#301]
Using appRTC android demo code, Is there is any way to switch between Audio and video and vise versa?  Can we enable video after starting the audio call?

**Comment by KaptenJansson** [comment]
You cannot change audio and video on the fly. This is something we want to add once replaceTrack() has been implemented in WebRTC, at least for the Web, not sure about Android but I guess it's the same. 

In the apprtc app you can disable video from the settings menu and you can mute the microphone whilst in a call but you probably already know this.

**Comment by KaptenJansson** [comment]
Going to close this, btw the Android and iOS AppRTC demo apps live the https://chromium.googlesource.com/external/webrtc/ code base. Please file an issue the [WebRTC bug tracker](https://bugs.webrtc.org) if there is something wrong or you think a feature is missing.

Also contributions are welcome ;)
