### ISSUE TITLE
Android browsers report: Error getting user media: Only secure origins are allowed

### ISSUE THREAD

**Issue by tedyyan** [webrtc/apprtc#303]
**Browsers and versions affected**
Android browsers

**Description**
Android browsers report following errors:
Messages: Error getting user media: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV). getUserMedia error: Failed to get access to local media.  
How to make origins are https? it's not working to use trafficserver to reverse proxy.
**Steps to reproduce**
setup a apprtc on server with offline Google App Engine which has listen on http 8080 instead of https.

**Expected results**
Video is watching android. 

**Actual results**
Android browsers report following errors:
Messages: Error getting user media: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV). getUserMedia error: Failed to get access to local media. 
only audio

**Comment by KaptenJansson** [comment]
You can access gUM via localhost:8080 using HTTP. Otherwise HTTPS is required.

PTAL at http://stackoverflow.com/questions/6029473/https-for-localhost8080 to setup a HTTPS proxy for GAE.

**Comment by tedyyan** [comment]
thanks a lot. i installed firefox on my android phone. it works now.



来自 魅族 MX5



-------- 原始邮件 --------
发件人：Christoffer Jansson <notifications@github.com>
时间：周四 5月19日 15:39
收件人：webrtc/apprtc <apprtc@noreply.github.com>
抄送：Teddy Yan <tedyyan@hotmail.com>,Author <author@noreply.github.com>
主题：Re: [webrtc/apprtc] Android browsers report: Error getting user media: Only secure origins are allowed (#303)


You can access gUM via localhost:8080 using HTTP. Otherwise HTTPS is required.

PTAL at http://stackoverflow.com/questions/6029473/https-for-localhost8080 to setup a HTTPS proxy for GAE.
