### ISSUE TITLE
Unable to display connection statistics from Firefox browser

### ISSUE THREAD

**Issue by letchoo** [webrtc/apprtc#304]
**Browsers and versions affected**
Firefox 47.0b5 (beta)

**Description**
Pressing `i` in Firefox to see the connection stats results in console error:

> TypeError: Argument 1 of RTCPeerConnection.getStats does not implement interface MediaStreamTrack. apprtc.debug.js:2722:3

**Steps to reproduce**
Tested in the current apprtc.appspot.com.

1. Join the 1st Peer in Chrome / Firefox
2. Join the 2nd Peer in Firefox
3. Press `i` for Firefox Peer to see the connection stats infobox.
4. Open the Web Console in Firefox Peer
5. See the error stated above.

**Expected results**
Be able to see the connection stats for the Firefox browser.

**Actual results**
Only sees the github branch and hash information.

**Comment by KaptenJansson** [comment]
Thanks for reporting (and reminding me ;)), I've already fixed this in #297 but have not pushed it to GAE yet. Will try to do so today. Will let you know!

**Comment by KaptenJansson** [comment]
Please try again now.

**Comment by letchoo** [comment]
@KaptenJansson tested and it seems to work. Just another question (perhaps an enhancement), is that is there any plan to display the outbound or inbound rtp/rtcp packets received / sent statistics for Firefox?

**Comment by KaptenJansson** [comment]
Perhaps, I want to wait until we get a unified stats interface (like in adapter.js) but that's been postponed meaning that I will have to create one in AppRTC to handle stats from Chrome and Firefox (and possible Edge, not sure if edge has stats yet) due to them having different formats.
