### ISSUE TITLE
a=rtpmap sdp line can have dash

### ISSUE THREAD

**Issue by wensheng** [webrtc/apprtc#305]
Some SDP's can have "a=rtpmap:" lines with dash `-` in them, for examples:

    a=rtpmap:122 X-H264UC/9000
    a=rtpmap:123 x-ulpfecuc/9000

The function `getCodecPayloadTypeFromLine` in the file `src/web_app/js/sdputils.js` has this (around line 459):

    var pattern = new RegExp('a=rtpmap:(\\d+) \\w+\\/\\d+');

It should be changed to:

    var pattern = new RegExp('a=rtpmap:(\\d+) [a-zA-Z0-9-]+\\/\\d+');

**Comment by KaptenJansson** [comment]
Thank you for letting us know, will look into it.
