### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by JiantaoFu** [webrtc/apprtc#306]
**Browsers and versions affected**

**Description**

Warning: node_modules/webrtc-adapter/out/adapter.js:2369: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
  var shimError_ = e => ({
                   ^

node_modules/webrtc-adapter/out/adapter.js:2442: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                                     e => onError(shimError_(e)));
                                     ^

node_modules/webrtc-adapter/out/adapter.js:2488: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
    navigator.mediaDevices.getUserMedia = c =>
                                          ^

node_modules/webrtc-adapter/out/adapter.js:2489: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
        origGetUserMedia(c).catch(e => Promise.reject(shimError_(e)));
                                  ^

4 error(s), 0 warning(s)
 Use --force to continue.

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by JiantaoFu** [comment]
diff --git a/Gruntfile.js b/Gruntfile.js
index daef3a4..7fba17e 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -167,7 +167,7 @@ module.exports = function(grunt) {
         },
         options: {
           'compilation_level': 'WHITESPACE_ONLY',
-          'language_in': 'ECMASCRIPT5',
+          'language_in': 'ECMASCRIPT6',
           'formatting': 'PRETTY_PRINT'
         },
       },

fixed this

**Comment by KaptenJansson** [comment]
This should no longer be needed as we have removed the arrow functions for now in adapter.js. If you do npm update again, you should get the latest adapter without arrow functions.
