### ISSUE TITLE
Minimum installation to run apprtc ?

### ISSUE THREAD

**Issue by wstdco** [webrtc/apprtc#307]
Hello,

I've successfully followed all the steps explained at github.com/webrtc/apprtc besides "Deployment" where I almost finished the signaling server part.

Until I get the skills / patience to deploy my own instance of apprtc, is there a minimal installation that allows me to create and join rooms from my own website, using apprtc.appspot.com / appr.tc / etc. instance of apprtc ?

**Comment by agouaillard** [comment]
No

**Comment by KaptenJansson** [comment]
As Alex wrote, no there is not. Please let me know if anything is unclear in the instructions (file a bug).

Thanks!
