### ISSUE TITLE
ERROR - this language feature is only supported in es6 mode: arrow function

### ISSUE THREAD

**Issue by jeeva-sil** [webrtc/apprtc#308]
How to fix the below error created while "grunt build"

`:~/apprtcserver/apprtc$ sudo grunt build
Running "shell:buildAppEnginePackage" (shell) task

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: node_modules/webrtc-adapter/out/adapter.js:2370: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
  var shimError_ = e => ({
                   ^

node_modules/webrtc-adapter/out/adapter.js:2443: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                                     e => onError(shimError_(e)));
                                     ^

node_modules/webrtc-adapter/out/adapter.js:2489: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
    navigator.mediaDevices.getUserMedia = c =>
                                          ^

node_modules/webrtc-adapter/out/adapter.js:2490: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
        origGetUserMedia(c).catch(e => Promise.reject(shimError_(e)));
                                  ^

4 error(s), 0 warning(s)
 Use --force to continue.

Aborted due to warnings.`

**Comment by KaptenJansson** [comment]
Please do npm update again which should fix adapter.js.

**Comment by jeeva-sil** [comment]
Build succeeded after removing all arrows '>' from where error is pointing out.

`:~/apprtcserver/apprtc$ sudo grunt build
[sudo] password for kasadmin: 
Running "shell:buildAppEnginePackage" (shell) task

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
>> Complete: 155638

Running "grunt-chrome-build:apprtc" (grunt-chrome-build) task
Chrome packaged app build.
Deleting buildDir: out/chrome_app
Creating empty buildDir: out/chrome_app
Copying resources to buildDir: out/chrome_app
src/web_app/chrome_app/manifest.json-->out/chrome_app/manifest.json
out/app_engine/js/apprtc.debug.js-->out/chrome_app/js/apprtc.debug.js
out/app_engine/js/loopback.js-->out/chrome_app/js/loopback.js
out/app_engine/css/main.css-->out/chrome_app/css/main.css
out/app_engine/images/apprtc-128.png-->out/chrome_app/images/apprtc-128.png
out/app_engine/images/apprtc-16.png-->out/chrome_app/images/apprtc-16.png
out/app_engine/images/apprtc-22.png-->out/chrome_app/images/apprtc-22.png
out/app_engine/images/apprtc-32.png-->out/chrome_app/images/apprtc-32.png
out/app_engine/images/apprtc-48.png-->out/chrome_app/images/apprtc-48.png
src/web_app/js/background.js-->out/chrome_app/js/background.js
src/web_app/js/appwindow.js-->out/chrome_app/js/appwindow.js

Running "grunt-chrome-build-transform" task
Transforming files using jinja.

Running "jinja:chrome-build" (jinja) task
Using context web_app/html/index_template
File "out/chrome_app/appwindow.html" created.

Running "grunt-chrome-build-compress" task
Creating zip file:out/chrome_app/apprtc.zip

Running "compress:chrome-build" (compress) task
Created out/chrome_app/apprtc.zip (67511 bytes)

Running "grunt-chrome-build-package" task
Skipping creation of Chrome package.

Done, without errors.`

**Comment by jeeva-sil** [comment]
npm update is also solved as you said...
