### ISSUE TITLE
how https://apprtc.appspot.com/ is working with secured

### ISSUE THREAD

**Issue by jeeva-sil** [webrtc/apprtc#309]
Yes as you said Turn server is not working after setting up stunnel. I am facing problem as said in [#257](https://github.com/webrtc/apprtc/issues/257)

Failed to start signaling: Failed to execute 'pushState' on 'History': A history state object with URL 'http://192.168.20.135/r/769453476' cannot be created in a document with origin 'https://192.168.20.135'.

Then how [https://apprtc.appspot.com/](https://apprtc.appspot.com/) is working with secured.

**Comment by KaptenJansson** [comment]
Hmm yes, I forgot about this, the origin is the taken from the client which will different from the what the hosted site (i.e. where AppRTC + GAE is) is running on. Not entirely sure how this can be solved. Maybe via some DNS redirect/proxy?

**Comment by jeeva-sil** [comment]
This problem is solved by commenting the line `window.history.pushState({"roomId":roomId, "roomLink":roomLink}, roomId, roomLink);` (line no:405, page: apprtc.debug.js). Now its working every where.

**Comment by KaptenJansson** [comment]
Aha awesome, did not even think of fixing it in the app, but that means I guess the URL in the URL bar does not update?

**Comment by KaptenJansson** [comment]
Closing due to nothing actionable in bug.
