### ISSUE TITLE
grunt build fails closure-compile with ES6 errors

### ISSUE THREAD

**Issue by phoglund** [webrtc/apprtc#310]
**Browsers and versions affected**
N/A

**Description**
grunt build fails.

**Steps to reproduce**
Did a fresh git clone + npm install + grunt build

**Expected results**
Working build.

**Actual results**
Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: node_modules/webrtc-adapter/out/adapter.js:2369: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
  var shimError_ = e => ({
                   ^

node_modules/webrtc-adapter/out/adapter.js:2442: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                                     e => onError(shimError_(e)));
                                     ^

node_modules/webrtc-adapter/out/adapter.js:2488: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
    navigator.mediaDevices.getUserMedia = c =>
                                          ^

node_modules/webrtc-adapter/out/adapter.js:2489: ERROR - this language feature is only supported in es6 mode: arrow function. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
        origGetUserMedia(c).catch(e => Promise.reject(shimError_(e)));
                                  ^

4 error(s), 0 warning(s)
 Use --force to continue.

**Comment by KaptenJansson** [comment]
Your build environment for some reason does not allow es6 which it should unless deactivated or using an old version of node or grunt. However I'm making a PR to make adapter es5 compliant again.

**Comment by phoglund** [comment]
Ok, I updated npm and grunt (sudo /usr/local/bin/npm install npm grunt -g but I'm still getting the same errors. But those versions shouldn't matter, right, but rather the version of the closure compiler?

**Comment by phoglund** [comment]
What config do you have, besides what's on the getting started instructions? If so, maybe it should go in the instructions?

It does work back at 3807b157c003efe9436508174a020dcf3208412d, I haven't bisected.

**Comment by KaptenJansson** [comment]
Ow right, looked into it, it's definitely the closure compiler not supporting ES6, in fact it has not pushed a new release for two years. As mentioned, I will make sure that adapter is ES5 compliant ASAP. If you need to build now, set the webrtc-adapter version in package.json to 1.1.0.

**Comment by metalmarco** [comment]
Regarding this issue, I fixed it by editing the Gruntfile.js file and setting: `'language_in': 'ECMASCRIPT6'` before launching `grunt build`

**Comment by KaptenJansson** [comment]
It should now work regardless since I've removed all ES6 functions in adapter.js.

**Comment by KaptenJansson** [comment]
This is now fixed.
