### ISSUE TITLE
bypassJoinConfirmation as a GET parameter

### ISSUE THREAD

**Issue by KirTitievsky** [webrtc/apprtc#32]
Would you please support bypassJoinConfirmation as a GET parameter, rather than a server option?

I'd love to be able to send someone a room invitation that requires a single click to join a conference. So desired user journey:
- Go to a room.
- Copy apprtc.appspost.com/r/1234 from my location bar into IM client to a friend
- Add ?bypassJoinConfirmation=True to the URL.
- The friend gets "http://apprtc.appspost.com/r/1234 from my location bar into IM client to a friend
- Clicks on the link indicating intent to join the video conference. 
- [Eliminated step: click on the JOIN button.]
- Talk to me.

**Comment by jiayliu** [comment]
We purposefully choose to not do that since we don't want a third party site embedding AppRTC to join a call without the user's permission.
