### ISSUE TITLE
Can AppRTC + Collider + Coturn be hosted on the same instance?

### ISSUE THREAD

**Issue by whydna** [webrtc/apprtc#323]
I'm deploying my own AppRTC and signalling server on Google App Engine.

I was able to get AppRTC installed. From my understanding, I now need to setup Collider to handle signalling and CoTurn to handle STUN/TURN.

Can these all be installed on the same instance that AppRTC is running on? Or do I need to setup separate instances on GCE for each?

**Comment by KaptenJansson** [comment]
Collider and CoTurn are normal applications requiring a normal VM like GCE, i.e they are not GAE apps. Those two however can run on the same machine/VM.
