### ISSUE TITLE
peers take 3 minutes to connect in local network

### ISSUE THREAD

**Issue by Yucheng123** [webrtc/apprtc#326]
**Browsers and versions affected**
Firefox  43.0.3 . Ubuntu os

**Description**
peers connect too slowly in local network.Maybe it was caused by band-width.But with the server-less webRtc (no signal server),peers connected soon (2 seconds).I suspect the collinder not works well. Collinder prints "send messages" soon, but "messages" reach slowly

**Steps to reproduce**
Install appRtc,collinder and coTurn as instructed. Collinder listens to port 8089 and coTurn starts by commands "service coturn start" 

**Expected results**
In local network, connection should be very fast

**Actual results**
connects slowly

**Comment by Yucheng123** [comment]
I want to take simplemaster as the signal server, appRTC throws the web socked opening error. Collinder is the only choice?

**Comment by KaptenJansson** [comment]
Hi,

You do not have to use Collider however AppRTC is designed around it, not sure if there are other solutions out there you can just use straight away, some modification to AppRTC is most likely required. Our https://appr.tc instance works fast, not sure why it's slow in your local network.

**Comment by KaptenJansson** [comment]
Closing due to nothing actionable in bug.
