### ISSUE TITLE
collider instalation non-standard import

### ISSUE THREAD

**Issue by franroldans** [webrtc/apprtc#327]
Hi,

I was trying to install Collider, but after following all the steps and installing websocket (go get -v golang.org/x/net/websocket), I get the following error message when typing go get collidermain:

/usr/local/go/src/collider/collider.go:11:2: non-standard import "golang.org/x/net/websocket" in standard package "collider"

Does anybody know what could be happening?

Thanks!

**Comment by KaptenJansson** [comment]
Hi, did you manage to solve it?

**Comment by franroldans** [comment]
I used that repo: 
https://github.com/cmorell/AppRTCLocal.git

**Comment by KaptenJansson** [comment]
It could be a go version incompatibility, others have reported this in #384.
