### ISSUE TITLE
How scalable is collider?

### ISSUE THREAD

**Issue by bloodfire91** [webrtc/apprtc#330]
Could anyone explain the apprtc architecture related to the collider & how well it scales?

Thanks

**Comment by KaptenJansson** [comment]
AppRTC runs on a Google App Engine instance and Collider runs on a couple of GCE VM's. Collider handles all the signalling via WebSockets between AppRTC clients.

It scales pretty well, we are using two instances for 2K+ calls a day and the load is very low (less than 1% on a 1 core, 3.75GB VM) hence it should be able to handle loads more.

**Comment by bloodfire91** [comment]
Wow thats great. Thanks for the info!
