### ISSUE TITLE
bindMstToUserIdForCallstats_ should not be called onaddstream

### ISSUE THREAD

**Issue by alexgcastro** [webrtc/apprtc#331]
**Description**

The code added in the commit #261 included that function and broke webkit client.

onaddstream is called "nearly immediately after the remote end of the connection is set using RTCPeerConnection.setRemoteDescription()":

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onaddstream

But the method is using some peer connection values such as the localDescription that it could be not initialized.

Probably a solution is calling the same function in the promise of createAnswer? That way all the information should be there.

Also using a deprecated API for new code is not a good idea.

**Comment by KaptenJansson** [comment]
Thanks for reporting, will take a look.
