### ISSUE TITLE
Uncaught TypeError seen after ending an apprtc loopback call

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#332]
**Browsers and versions affected**
M54 Canary 54.0.2804.0 in Mac 10.11.6

**Description**
Uncaught TypeError: Cannot read property 'ucID' of undefined seen after ending an apprtc loopback call

**Steps to reproduce**
1. Start an apprtc video only loopback call https://appr.tc/r/946789264?debug=loopback&audio=false
2. Verify that audio is not heard, but video is seen
3. End the call and check JS console for any errors

**Expected results**
No JS errors should be seen in console

**Actual results**
Uncaught TypeError: Cannot read property 'ucID' of undefined seen after ending an apprtc loopback call
Screenshot attached

callstats.min.js:3 Uncaught TypeError: Cannot read property 'ucID' of undefinedNb @ callstats.min.js:3(anonymous function) @ callstats.min.js:3Emitter.emit @ socket.io.js:5657Socket.onevent @ socket.io.js:5183Socket.onpacket @ socket.io.js:5141(anonymous function) @ socket.io.js:5522Emitter.emit @ socket.io.js:5657Manager.ondecoded @ socket.io.js:4668(anonymous function) @ socket.io.js:5522Emitter.emit @ socket.io.js:2556Decoder.add @ socket.io.js:6156Manager.ondata @ socket.io.js:4658(anonymous function) @ socket.io.js:5522Emitter.emit @ socket.io.js:2556Socket.onPacket @ socket.io.js:459(anonymous function) @ socket.io.js:276Emitter.emit @ socket.io.js:2556Transport.onPacket @ socket.io.js:892Transport.onData @ socket.io.js:884ws.onmessage @ socket.io.js:2003

![screen shot 2016-07-22 at 12 37 08 pm](https://cloud.githubusercontent.com/assets/14947786/17069069/6ae506cc-5009-11e6-9289-7c1525b7caa1.png)

CC: @KaptenJansson

**Comment by karthikbr82** [comment]
@KaptenJansson This error happens in 3.12.3 version of callstats.js We have fixed this issue in 3.12.4 and the current version is 3.12.5. So updating callstats.js should fix this bug.

**Comment by KaptenJansson** [comment]
Ty, will do!

**Comment by KaptenJansson** [comment]
I've now pushed the latest release, srnarayanan@ could you try again? It looks good to me.

**Comment by srnarayanan** [comment]
LGTM!
I don't see any JS errors after ending apprtc calls (p2p, loopback, audio only, video only)

**Comment by KaptenJansson** [comment]
Awesome, thanks for verifying!
