### ISSUE TITLE
How to set logs timezone

### ISSUE THREAD

**Issue by metalmarco** [webrtc/apprtc#334]
Hi everyone,
I'm trying to modify apprtc logs timezone, as all the logs are currently UTC.

Is it possible  to do it?
Thanks.

**Comment by KaptenJansson** [comment]
Hi,

Could you clarify which logs? Is this for the web version of AppRTC (i.e. this repo) or the native Android or iOS [app](https://cs.chromium.org/chromium/src/third_party/webrtc/examples/)?

AFAIK we do not set a timezone anywhere, we use whatever the OS/browser uses.

**Comment by metalmarco** [comment]
Hi Christoffer, and thanks for your quick reply.
I’m talking about the AppRTC web version. As you can see the logs are 2 hours in advance compared to my OS time.
 
ubuntu@ip-172-30-0-107:~$ date
Thu Jul 28 09:33:32 CEST 2016

ubuntu@ip-172-30-0-107:~$ tail -1 apprtc.log 
INFO     2016-07-28 07:33:21,910 module.py:788] default: “GET /js/apprtc.debug.js HTTP/1.1" 304 -

I don’t know where I can manage the logging timezone configuration, inside the google appengine SDK or inside the AppRTC application.
Thanks again for your support, let me know if you have any suggestion.

Regards,
Marco.

**Comment by KaptenJansson** [comment]
https://timezones.appspot.com/

**Comment by metalmarco** [comment]
Thanks Christoffer, but which line of code do I have to modify to apply this configuration to all AppRTC logs?

Regards,
Marco.

**Comment by KaptenJansson** [comment]
"The runtime's TZ environment variable is set to UTC, and can't be changed. "

We use the python module logging for all logging. You would need to either create your own logging method or find a different logging module that can adjust the time zone.

**Comment by metalmarco** [comment]
Ok thanks for your support.

Marco.
