### ISSUE TITLE
Uncaught TypeError seen after ending an apprtc loopback call

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#336]
**Browsers and versions affected**
M54 Canary 54.0.2810.2 in Mac 10.11.6

**Description**
Uncaught TypeError: Cannot read property 'getlocalStreams' of null
thrown just after ending an apprtc audio-only loopback call 

**Steps to reproduce**
1. Start an audio-only apprtc loopback call https://appr.tc/r/689720219?debug=loopback&audio=true&video=false
2. After a while, end the call and observe the JS console

**Expected results**
The call should end successfully without any JS errors

**Actual results**
Uncaught TypeError: Cannot read property 'getlocalStreams' of null
thrown just after ending an apprtc audio-only loopback call 

CC: @KaptenJansson 
Screenshot:

![screen shot 2016-07-28 at 1 36 21 pm](https://cloud.githubusercontent.com/assets/14947786/17228584/7b17d664-54c8-11e6-9edb-2e3ca485d3e8.png)

**Comment by srnarayanan** [comment]
JS logs -

0.184: Initializing; server= undefined.
apprtc.debug.js:4084 0.186: Initializing; room=undefined.
apprtc.debug.js:4084 2.053: Opening signaling channel.
apprtc.debug.js:4084 2.056: Setting up loopback WebSocket.
apprtc.debug.js:4084 2.061: Got access to local media with mediaConstraints:
  '{"audio":true,"video":false}'
apprtc.debug.js:4084 2.062: User has granted access to local media.
apprtc.debug.js:4084 2.062: Attaching local stream.
apprtc.debug.js:4084 2.178: Signaling channel opened.
apprtc.debug.js:4084 2.232: Retrieved ICE server information.
apprtc.debug.js:4084 2.235: Joined the room.
apprtc.debug.js:4084 2.236: Registering signaling channel.
apprtc.debug.js:4084 2.236: Signaling channel registered.
apprtc.debug.js:4084 2.237: Starting signaling.
apprtc.debug.js:4084 2.240: ECDSA certificate generated successfully.
apprtc.debug.js:4084 2.241: Creating RTCPeerConnnection with:
  config: '{"rtcpMuxPolicy":"require","bundlePolicy":"max-bundle","iceServers":[{"urls":["turn:173.194.202.127:19305?transport=udp","turn:[2607:F8B0:400E:C00::7F]:19305?transport=udp","turn:173.194.202.127:443?transport=tcp","turn:[2607:F8B0:400E:C00::7F]:443?transport=tcp"],"username":"CI377rwFEgbnT/lrwAwYzc/s6OMT","credential":"4hctLH8n2V0wa/qM3fs5G2Flpyo="},{"urls":["stun:stun.l.google.com:19302"]}],"certificates":[{}]}';
  constraints: '{"optional":[{"DtlsSrtpKeyAgreement":false}]}'.
apprtc.debug.js:4084 2.243: Created PeerConnectionClient
apprtc.debug.js:4084 2.243: Adding local stream.
apprtc.debug.js:4084 2.244: Init callstats.
apprtc.debug.js:4084 2.256: Sending offer to peer, with constraints: 
'{"offerToReceiveAudio":1,"offerToReceiveVideo":1,"voiceActivityDetection":false}'.
apprtc.debug.js:4084 2.259: No preference on audio receive codec.
apprtc.debug.js:4084 2.259: Prefer video receive codec: VP9
apprtc.debug.js:4084 2.263: C->GAE: {"sdp":"v=0\r\no=- 5581686220769933742 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS e0m28xToTGkJMZEqcD09ght6i44nKgv7sckm\r\nm=audio 9 RTP/SAVPF 111 103 104 9 0 8 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:JjZX\r\na=ice-pwd:9ZxMLFSKFlmw9lnn3xWXdJPr\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=sendrecv\r\na=rtcp-mux\r\na=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:n8H/qUaBTppCV3Q6lWmrtWqV5RrTPMGEPcYXs8ni\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:1199015864 cname:0C3zuqEgR8G74qCP\r\na=ssrc:1199015864 msid:e0m28xToTGkJMZEqcD09ght6i44nKgv7sckm 1cdeacc9-93fe-4116-91f7-5e6db98b746e\r\na=ssrc:1199015864 mslabel:e0m28xToTGkJMZEqcD09ght6i44nKgv7sckm\r\na=ssrc:1199015864 label:1cdeacc9-93fe-4116-91f7-5e6db98b746e\r\nm=video 9 RTP/SAVPF 101 100 107 116 117 96 97 99 98\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:JjZX\r\na=ice-pwd:9ZxMLFSKFlmw9lnn3xWXdJPr\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:n8H/qUaBTppCV3Q6lWmrtWqV5RrTPMGEPcYXs8ni\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtpmap:101 VP9/90000\r\na=rtcp-fb:101 ccm fir\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=rtcp-fb:101 transport-cc\r\na=rtpmap:107 H264/90000\r\na=rtcp-fb:107 ccm fir\r\na=rtcp-fb:107 nack\r\na=rtcp-fb:107 nack pli\r\na=rtcp-fb:107 goog-remb\r\na=rtcp-fb:107 transport-cc\r\na=fmtp:107 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:116 red/90000\r\na=rtpmap:117 ulpfec/90000\r\na=rtpmap:96 rtx/90000\r\na=fmtp:96 apt=100\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=101\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=107\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=116\r\n","type":"offer"}
apprtc.debug.js:4084 2.266: Signaling state changed to: have-local-offer
apprtc.debug.js:4084 2.267: Set session description success.
apprtc.debug.js:4084 2.269: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:3443785521 1 udp 2113937151 172.19.3.136 62632 typ host generation 0 ufrag JjZX network-cost 50"}
apprtc.debug.js:4084 2.270: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:344400649 1 udp 2113939711 2620::1000:137c:389b:f232:d204:81cc 62633 typ host generation 0 ufrag JjZX network-cost 50"}
apprtc.debug.js:4084 2.306: Loopback WebSocket opened.
apprtc.debug.js:4084 2.367: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:1921708142 1 udp 33563135 173.194.202.127 26723 typ relay raddr 172.19.3.136 rport 62632 generation 0 ufrag JjZX network-cost 50"}
apprtc.debug.js:4084 2.369: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:1921708142 1 udp 33562879 173.194.202.127 27243 typ relay raddr 2620::1000:137c:389b:f232:d204:81cc rport 62633 generation 0 ufrag JjZX network-cost 50"}
apprtc.debug.js:4084 2.391: WSS->C: {"msg":"{\"sdp\":\"v=0\\r\\no=- 5581686220769933742 2 IN IP4 127.0.0.1\\r\\ns=-\\r\\nt=0 0\\r\\na=group:BUNDLE audio video\\r\\na=msid-semantic: WMS e0m28xToTGkJMZEqcD09ght6i44nKgv7sckm\\r\\nm=audio 9 RTP/SAVPF 111 103 104 9 0 8 126\\r\\nc=IN IP4 0.0.0.0\\r\\na=rtcp:9 IN IP4 0.0.0.0\\r\\na=ice-ufrag:JjZX\\r\\na=ice-pwd:9ZxMLFSKFlmw9lnn3xWXdJPr\\r\\na=mid:audio\\r\\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\\r\\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\\r\\na=sendrecv\\r\\na=rtcp-mux\\r\\na=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:n8H/qUaBTppCV3Q6lWmrtWqV5RrTPMGEPcYXs8ni\\r\\na=rtpmap:111 opus/48000/2\\r\\na=rtcp-fb:111 transport-cc\\r\\na=fmtp:111 minptime=10;useinbandfec=1\\r\\na=rtpmap:103 ISAC/16000\\r\\na=rtpmap:104 ISAC/32000\\r\\na=rtpmap:9 G722/8000\\r\\na=rtpmap:0 PCMU/8000\\r\\na=rtpmap:8 PCMA/8000\\r\\na=rtpmap:126 telephone-event/8000\\r\\na=ssrc:1199015864 cname:0C3zuqEgR8G74qCP\\r\\na=ssrc:1199015864 msid:e0m28xToTGkJMZEqcD09ght6i44nKgv7sckm 1cdeacc9-93fe-4116-91f7-5e6db98b746e\\r\\na=ssrc:1199015864 mslabel:e0m28xToTGkJMZEqcD09ght6i44nKgv7sckm\\r\\na=ssrc:1199015864 label:1cdeacc9-93fe-4116-91f7-5e6db98b746e\\r\\nm=video 9 RTP/SAVPF 101 100 107 116 117 96 97 99 98\\r\\nc=IN IP4 0.0.0.0\\r\\na=rtcp:9 IN IP4 0.0.0.0\\r\\na=ice-ufrag:JjZX\\r\\na=ice-pwd:9ZxMLFSKFlmw9lnn3xWXdJPr\\r\\na=mid:video\\r\\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\\r\\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\\r\\na=extmap:4 urn:3gpp:video-orientation\\r\\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\\r\\na=recvonly\\r\\na=rtcp-mux\\r\\na=rtcp-rsize\\r\\na=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:n8H/qUaBTppCV3Q6lWmrtWqV5RrTPMGEPcYXs8ni\\r\\na=rtpmap:100 VP8/90000\\r\\na=rtcp-fb:100 ccm fir\\r\\na=rtcp-fb:100 nack\\r\\na=rtcp-fb:100 nack pli\\r\\na=rtcp-fb:100 goog-remb\\r\\na=rtcp-fb:100 transport-cc\\r\\na=rtpmap:101 VP9/90000\\r\\na=rtcp-fb:101 ccm fir\\r\\na=rtcp-fb:101 nack\\r\\na=rtcp-fb:101 nack pli\\r\\na=rtcp-fb:101 goog-remb\\r\\na=rtcp-fb:101 transport-cc\\r\\na=rtpmap:107 H264/90000\\r\\na=rtcp-fb:107 ccm fir\\r\\na=rtcp-fb:107 nack\\r\\na=rtcp-fb:107 nack pli\\r\\na=rtcp-fb:107 goog-remb\\r\\na=rtcp-fb:107 transport-cc\\r\\na=fmtp:107 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\\r\\na=rtpmap:116 red/90000\\r\\na=rtpmap:117 ulpfec/90000\\r\\na=rtpmap:96 rtx/90000\\r\\na=fmtp:96 apt=100\\r\\na=rtpmap:97 rtx/90000\\r\\na=fmtp:97 apt=101\\r\\na=rtpmap:99 rtx/90000\\r\\na=fmtp:99 apt=107\\r\\na=rtpmap:98 rtx/90000\\r\\na=fmtp:98 apt=116\\r\\n\",\"type\":\"answer\"}","error":""}
apprtc.debug.js:4084 2.392: No preference on audio send codec.
apprtc.debug.js:4084 2.392: No preference on video send codec.
apprtc.debug.js:4084 2.394: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:3443785521 1 udp 2113937151 172.19.3.136 62632 typ host generation 0 ufrag JjZX network-cost 50\"}","error":""}
apprtc.debug.js:4084 2.397: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:344400649 1 udp 2113939711 2620::1000:137c:389b:f232:d204:81cc 62633 typ host generation 0 ufrag JjZX network-cost 50\"}","error":""}
apprtc.debug.js:4084 2.399: Set remote session description success.
apprtc.debug.js:4084 2.399: No remote video stream; not waiting for media to arrive.
apprtc.debug.js:4084 2.399: Call setup time: 161ms.
apprtc.debug.js:4084 2.399: reattachMediaStream: [object MediaStream]
2apprtc.debug.js:4084 2.400: Remote candidate added successfully.
apprtc.debug.js:4084 2.401: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:1007226014 1 udp 16785151 173.194.202.127 30799 typ relay raddr 2620::1000:137c:389b:f232:d204:81cc rport 62859 generation 0 ufrag JjZX network-cost 50"}
apprtc.debug.js:4084 2.401: Signaling state changed to: stable
apprtc.debug.js:4084 2.401: ICE connection state changed to: checking
apprtc.debug.js:4084 2.402: Remote stream added.
apprtc.debug.js:4084 2.403: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:1007226014 1 udp 16785407 173.194.202.127 27594 typ relay raddr 172.19.3.136 rport 62858 generation 0 ufrag JjZX network-cost 50"}
apprtc.debug.js:4084 2.406: End of candidates.
apprtc.debug.js:4084 2.407: ICE connection state changed to: connected
apprtc.debug.js:4084 2.421: ICE connection state changed to: completed
apprtc.debug.js:4084 2.421: ICE complete time: 183ms.
apprtc.debug.js:4084 2.469: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:1921708142 1 udp 33562879 173.194.202.127 27243 typ relay raddr 2620::1000:137c:389b:f232:d204:81cc rport 62633 generation 0 ufrag JjZX network-cost 50\"}","error":""}
apprtc.debug.js:4084 2.471: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:1921708142 1 udp 33563135 173.194.202.127 26723 typ relay raddr 172.19.3.136 rport 62632 generation 0 ufrag JjZX network-cost 50\"}","error":""}
apprtc.debug.js:4084 2.472: Remote candidate added successfully.
apprtc.debug.js:4084 2.474: Remote candidate added successfully.
apprtc.debug.js:4084 2.475: ICE connection state changed to: connected
apprtc.debug.js:4084 2.504: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:1007226014 1 udp 16785151 173.194.202.127 30799 typ relay raddr 2620::1000:137c:389b:f232:d204:81cc rport 62859 generation 0 ufrag JjZX network-cost 50\"}","error":""}
apprtc.debug.js:4084 2.508: WSS->C: {"msg":"{\"type\":\"candidate\",\"label\":0,\"id\":\"audio\",\"candidate\":\"candidate:1007226014 1 udp 16785407 173.194.202.127 27594 typ relay raddr 172.19.3.136 rport 62858 generation 0 ufrag JjZX network-cost 50\"}","error":""}
apprtc.debug.js:4084 2.510: Remote candidate added successfully.
apprtc.debug.js:4084 2.511: Remote candidate added successfully.
apprtc.debug.js:4084 2.545: ICE connection state changed to: completed
apprtc.debug.js:4084 2.545: ICE complete time: 307ms.
apprtc.debug.js:4084 2.621: Set up callstats.
apprtc.debug.js:4084 2.637: Init status: success msg: SDK authentication successful.
apprtc.debug.js:4084 8.544: Hanging up.
apprtc.debug.js:4084 8.557: Callstats status: success msg: fabricTerminated sent to the backend.
apprtc.debug.js:4084 8.673: C->WSS: {"type":"bye"}
apprtc.debug.js:4084 8.712: Channel closed with code:1000 reason:
apprtc.debug.js:3152 Uncaught TypeError: Cannot read property 'getlocalStreams' of nullPeerConnectionClient.bindMstToUserIdForCallstats_ @ apprtc.debug.js:3152processQueue @ apprtc.debug.js:3092(anonymous function) @ apprtc.debug.js:3140oa @ callstats.min.js:2(anonymous function) @ callstats.min.js:2
apprtc.debug.js:4084 12.371: Callstats status: success msg: callStatsEvent sent to the backend.

**Comment by KaptenJansson** [comment]
Thanks for a filing, clearly a bug. Will fix!

**Comment by srnarayanan** [comment]
This error re-surfaced in M54 54.0.2840.10, after ending apprtc loopback call (audio only, video only)

Uncaught TypeError: Cannot read property 'getLocalStreams' of null(…) 

PeerConnectionClient.bindMstToUserIdForCallstats_ @ apprtc.debug.js:3130
processQueue @ apprtc.debug.js:3070
(anonymous function) @ apprtc.debug.js:3118
ka @ callstats.min.js:2
(anonymous function) @ callstats.min.js:2

**Comment by KaptenJansson** [comment]
I've now pushed a new release containing callstats fixes, please retry.
