### ISSUE TITLE
AppRTC loopback should work with DTLS

### ISSUE THREAD

**Issue by marwahvikas** [webrtc/apprtc#34]
Quoth https://github.com/GoogleChrome/webrtc/blob/master/samples/web/content/apprtc/apprtc.py#L395

debug = self.request.get('debug')
if debug == 'loopback':
  # Set dtls to false as DTLS does not work for loopback.
  dtls = 'false'
Indeed, failing to disable DTLS causes errors like:
Error(transport.cc:101): Answerer must use either active or passive value for setup attribute.

Since SDES is eventually going to disappear in favor of DTLS we should make sure loopback calls work with DTLS as well. The answer is probably to set up a second PeerConnection on the same page.
Once the JS version is updated the same should be done for the Android & iOS sample apps.

**Comment by KaptenJansson** [comment]
Closing this in favor of #312
