### ISSUE TITLE
AppRTC turnserver NO TURN SERVER

### ISSUE THREAD

**Issue by pieronov** [webrtc/apprtc#341]
Hello everyone, I wrote in this topic, but it is closed.
https://github.com/webrtc/apprtc/issues/266

I'm trying to use this app on a VPS, so I'm not using localhost, and I do not even https, this is the address:
http://51.254.115.249:8083?wstls=false

The collider is working properly, the log shows me the room opened, closed, connections, etc

To start the turnserver I also use the simple command
sudo -v -a -o -n --no-DTLS --no-tls -u hello:hello -r someRealm
Open ports are the 3478 and 3479, so I have included this variable in call.js file

`var servers = [{credentials: "hello", urls: [ "turn: 51.254.115.249: 3478? transport = udp", "turn: 51.254.115.249: 3478? transport = tcp"], username: "hello"}, {urls: [ "stun: stun.l.google.com: 19302"]}];`

When I try to connect with my smartphone it does not work.

"No TURN server; unlikely That average will traverse networks"

From console
http://pastebin.com/eVwVLD7f

**Comment by KaptenJansson** [comment]
Have you tested your turn server using https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ ?

**Comment by pieronov** [comment]
Hello, I tried it, it works, this is the result

```
0.170	1	relay 	3047925410	udp	51.254.115.249	53601	2 | 30 | 255
0.175	2	relay 	3047925410	udp	51.254.115.249	59968	2 | 30 | 254
0.175	Done
```

Its done.

**Comment by KaptenJansson** [comment]
I figured out the problem, I was naively think that it was enough to replace the server array in calls.js but in fact the requestIceServers function in utils.js fails causing the TURN logic to fail. I've updated the instructions at https://github.com/webrtc/apprtc/blob/master/README.md#deployment. 

Please try them out and let me know if it works.

**Comment by pieronov** [comment]
So i have to delete the servers array in calls.js? I dont think so,  If I delete, nothing changes the problem persists.
In calls.js:
` var servers = [{credentials:"hello", urls:["turn:51.254.115.249:3478?transport=udp", "turn:51.254.115.249:3478?transport=tcp"], username:"hello"}, {urls:["stun:stun.l.google.com:19302"]}];`

In utilis.js add:
```
function requestIceServers (iceServerRequestUrl, iceTransports) {
   return new Promise (function (resolve, reject) {
     var servers = [{
         credentials: "hello",
         username: "hello"
         urls: [
           "Turn: 51254115249: 3478? Transport = udp",
           "Turn: 51254115249: 3478? Transport = tdp"
         ]
     }];
     resolve (servers);
   });
}

```
You wrote? "Transport = TDP" and not TCP, correct?


However comes a popup that says the following error:
`Can not create RTCPeerConnection: RTCPeerConnection constructor passed invalid RTCConfiguration - missing credential: turn: 51254115249: 3478? Transport = udp`

Missing credential? its strange

Here the complete log:
http://pastebin.com/MtwqJZf0

**Comment by KaptenJansson** [comment]
Sorry for the typo, tdp should obviously be tcp.

The instructions assume no other changes, hence you can restore call.js to the original.

Also to clarify, you should replace the requestIceServers function already there.

**Comment by pieronov** [comment]
Ok i've restored constants.py to original and changed only WSS_INSTANCE_HOST_KEY
Collider working good.

Restored calls.js to original from the git

Restored utils.js and replaced function to:
```
function requestIceServers (iceServerRequestUrl, iceTransports) {
   return new Promise (function (resolve, reject) {
     var servers = [{
         credentials: "hello",
         username: "hello"
         urls: [
           "Turn:51.254.115.249:3478?Transport=udp",
           "Turn:51.254.115.249:3478?Transport=tdp"
         ]
     }];
     resolve (servers);
   });
}
```
Tested with localhost too

Same problem as before:
`Can not create RTCPeerConnection: RTCPeerConnection constructor passed invalid RTCConfiguration - missing credential:turn:51254115249:3478?Transport=udp`

Log:
http://pastebin.com/7Z1jCPGd

Ofc credentials are corrects
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
Still return Done

I'm trying to figure out the problem

**Comment by KaptenJansson** [comment]
credentials should be credential.

**Comment by pieronov** [comment]
It works,
There are errors, thank you.
There is one thing I do not understand,
I can connect from my smartphone ANDROID disabling the wireless and using 3G and 4G connections,

But if I try to use an iphone, it does not work, there is a strange, gray circle at the center of the screen.

**Comment by pieronov** [comment]
If i remove 
`  <video id="local-video" autoplay muted></video>`
from index_template.html,the circle disappear, but of course does not resolve the problem.
it is as if the app does not communicate with the iphone, when I click on Join the collider log does not report anything, no connection and the screen is gray

**Comment by KaptenJansson** [comment]
Chrome on iOS does not have WebRTC  hence you cannot use it, details to why can be found in this [post](https://groups.google.com/forum/#!topic/discuss-webrtc/bch_feIJn88). You need to build the AppRTCDemo iOS (there is one for Android as well) app part of the webrtc.org code base. Instructions [here](https://webrtc.org/native-code/ios/).

As an alternative you could try http://www.openwebrtc.org/bowser/ and see if it works with the web version of appr.tc, I've not tried it myself.

**Comment by pieronov** [comment]
I must ask you the last thing,
The problem is not only chrome, even using safari and firefox can not connect to appr.tc using the iphone.
I would understand if there is a way to connect directly to the web site, without using the app brower.
If I implement apprtc on my website, I can connect only using Android smartphone?

The only way I think is to implement AppRTCDemo-iOS in my APP and connect it to my server on VPS, thats right?

**Comment by KaptenJansson** [comment]
Safari is not a WebRTC capable browser. Please to https://webrtc.org/ to see the officially supported WebRTC browsers.

**Comment by pieronov** [comment]
I know about safari , but also firefox does not work using the iphone

**Comment by KaptenJansson** [comment]
Yes, no browser with the exception of Bowser has WebRTC since they are all just a wrapper around the built in WebKit engine used by safari due to Apple policy. This is outlined in the post in comment https://github.com/webrtc/apprtc/issues/341#issuecomment-237495234 I added yesterday..
