### ISSUE TITLE
sendFabricEvent error thrown (intermittently) after ending an apprtc 2 way call

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#345]
**Browsers and versions affected**
Chrome M53 Beta 53.0.2785.46 
Mac 10.11.6, CrOS 

**Description**
sendFabricEvent: SDK is not initialized or no Fabrics added error thrown after ending a 2 way apprtc call 

**Steps to reproduce**
1. Establish a 2 way apprtc call between Mac and CrOS 
2. End the call after a while

**Expected results**
No JS errors should be seen after ending a peer2peer apprtc call

**Actual results**
The following error is thrown

sendFabricEvent: SDK is not initialized or no Fabrics added.
gc @ callstats.min.js:3
PeerConnectionClient.sendCallstatsEvents @ apprtc.debug.js:3204
PeerConnectionClient.close @ apprtc.debug.js:2931
Call.hangup @ apprtc.debug.js:2296
AppController.hangup_ @ apprtc.debug.js:1971

Attached screenshot
CC @KaptenJansson

**Notes** 
In that AppRTC call session, ICE connection dropped. Not sure if that's related, but thought might be helpful to mention it!
JS Console logs attached as well. 

![screen shot 2016-08-04 at 1 05 51 pm](https://cloud.githubusercontent.com/assets/14947786/17416787/b842f06a-5a44-11e6-86d5-2ef5b96be678.png)

[JS logs.txt](https://github.com/webrtc/apprtc/files/402604/JS.logs.txt)

**Comment by KaptenJansson** [comment]
Thanks for filing, I will fix this.

**Comment by KaptenJansson** [comment]
This is fixed.
