### ISSUE TITLE
"No TURN server" when viewing from Android app via Webview.

### ISSUE THREAD

**Issue by callingshotgun** [webrtc/apprtc#347]
**Browsers and versions affected**
Android Marshmellow via Chrome Webview

**Description**
When loading appr.tc via webview in Android, error along bottom of screen reads:
"No TURN server, unlikely that media will traverse networks.  If this persissts please report it to discuss-webrtc@googlegroups.com"

**Steps to reproduce**
1) git clone https://github.com/GoogleChrome/chromium-webview-samples
Update android sample to point to appr.tc instead of apprtc-m.appspot.com

**Expected results**
Visiting appr.tc via android phone results in working VC.

**Actual results**
Error message along bottom of the screen, as described above.

**Comment by KaptenJansson** [comment]
The turn server only serves from localhost:8080 and appr.tc domains.

**Comment by callingshotgun** [comment]
Doesn't that mean that if your Android app opens appr.tc (via webview), it should detect the turn server there?

**Comment by KaptenJansson** [comment]
Can you get javascript logs? It should indicate what went wrong.
