### ISSUE TITLE
Will this AppRTC Supports conference call ?

### ISSUE THREAD

**Issue by jeeva-sil** [webrtc/apprtc#349]
I increased the number of occupancies in room but can't create multiple stream connection. Is it possible to implement conference or broadcast(one to many) in this AppRTC ?

**Comment by KaptenJansson** [comment]
I cannot see this happening in the near future. Patches are however welcome ;) You could always fork the repo and make your own app.

**Comment by jeeva-sil** [comment]
Now i am trying to implement conference in this. I will post solution once if i succeeded.

**Comment by sinumohan** [comment]
Did anyone got a solution for this ??

**Comment by Max01010101010101** [comment]
Did anyone got a solution for this ??

**Comment by kiran5232** [comment]
Did anyone got a solution for this ??

**Comment by kokhp** [comment]
Have you guys found any way to make conference possible in apprtc??
