### ISSUE TITLE
Unable to make Apprtc loopback calls with H264 on chrome OS

### ISSUE THREAD

**Issue by cvranjani** [webrtc/apprtc#350]
Chrome version: 54.0.2824.0 / 8696.0.0 dev 
Chrome device : Peppy

Steps to reproduce:
1.   Browse to https://appr.tc/?debug=loopback&vsc=h264
2.   Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Press "i" to open up the stats data, while in the call 
(alternatively, expand the ssrc_<>_send in chrome://webrtc-internals)

Expected result:
- Apprtc loopback call should be connected 
- In the apprtc call stats window, Video Tx should show H264 (also in ssrc_<>_send in chrome://webrtc-internals)

Actual result:
- Apprtc loopback call is not connected
- Apprt call stats window shows that call is not connected
"Audio Tx: opus, 42.0 kbps, 50.0 pps
Audio Rx: opus, 42.0 kbps, 50.0 pps
Video Tx: H264, 360p30, 2.03 Mbps, 231 pps
Video Rx: , 0p0, - bps, - pps"
![apprtc_loopback_h264_call_stats_window](https://cloud.githubusercontent.com/assets/15255941/17599178/ab7f1728-5fb2-11e6-9b48-ad388e206664.png)

Notes: 
No javascript errors were observed for initial 20-25 minutes of the call.
[Apprtc_loopback_h2674_js_logs_M54.txt](https://github.com/webrtc/apprtc/files/413878/Apprtc_loopback_h2674_js_logs_M54.txt)

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by cvranjani** [comment]
- Chrome device Peppy is on "Google Guest" network 
- AppRTC loopback calls with default video codec VP9( https://appr.tc/?debug=loopback) and VP8( https://appr.tc/?debug=loopback&vsc=vp8) are working as expected

**Comment by cvranjani** [comment]
Also observed this issue in apprtc calls with VP8 codec on chrome device Blaze. Not sure if this issue is related to problems with TURN servers or new apprtc loopback real peer2peer connections.

**Comment by KaptenJansson** [comment]
I think this is a race condition in the signalling which happens on slower devices. Will take a look.

**Comment by srnarayanan** [comment]
I see this in Mac as well - Chrome Canary 54.0.2829.0

**Comment by wuchengli** [comment]
Hi. Any update for this? We use apprtc loopback for Chrome OS testing a lot.

**Comment by cvranjani** [comment]
Recent code changes to AppRTC code have been reverted back and this issue is resolved now. Apprtc loopback calls are getting connected with VP8 and h264 .

**Comment by KaptenJansson** [comment]
I will make sure the issues (which are outside of AppRTC) uncovered by the new loopback logic are fixed before re-landing the new loopback logic.
