### ISSUE TITLE
New loopback - Uncaught TypeError seen after apprtc call drops due to appConnectivityError

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#353]
**Browsers and versions affected**
M54 Canary 54.0.2837.0 in Win 8 

**Description**
"Uncaught TypeError: Cannot read property 'catch' of undefined" error thrown after apprtc call drop

**Steps to reproduce**
1. Start a 2 way apprtc call b/w 2 hosts
2. Observe the JS console

**Expected results**
ICE state should not disconnect, and no appConnectivityError should occur. Apprtc call should be established correctly without JS errors

**Actual results**
1. ICE state disconnects, and appConnectivityError is thrown
2. Uncaught TypeError: Cannot read property 'catch' of undefined JS error is thrown
Screenshot and JS logs attached

Screenshot:
![untitled](https://cloud.githubusercontent.com/assets/14947786/17911175/1ba7639c-6941-11e6-9f6b-43d7edf85388.png)

JS logs - 
[js logs.txt](https://github.com/webrtc/apprtc/files/433630/js.logs.txt)

Notes:
This might not be 100% reproducible since ICE drops don't happen as frequently now, as before.
CC @KaptenJansson @hkjellander

**Comment by KaptenJansson** [comment]
Will fix in the new loopback logic.

**Comment by KaptenJansson** [comment]
Closing due to age.
