### ISSUE TITLE
New Loopback - Uncaught TypeError seen just before re-joining an apprtc loopback call, with a different name 

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#354]
**Browsers and versions affected**
M54 Canary 54.0.2839.x in Win 10, Linux 

**Description**
"Uncaught TypeError: Cannot read property 'hangup' of null" seen just before joining an apprtc video-only loopback call

**Steps to reproduce**
1. Start an apprtc loopback call (for ex: https://appr.tc/r/138919216?debug=loopback)
2. After a while, end the call
3. In the same session, edit the URL to https://appr.tc/r/138919216?debug=loopback&audio=true and hit Enter
4. Observe the JS console

**Expected results**
Video-only loopback call should be established without errors

**Actual results**
Very quickly, just after you hit Enter, you'd see the JS error "Uncaught TypeError: Cannot read property 'hangup' of null", before prompt to join the apprtc video-only loopback call appears

Screenshot -

<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/14947786/17987161/54aaf4c2-6ad3-11e6-957a-76ad22b4a651.png">

CC: @KaptenJansson

**Comment by srnarayanan** [comment]
This happens even after re-joining the apprtc loopback call with a different room name (by editing the URL), in the same session 

Changed the title accordingly

**Comment by KaptenJansson** [comment]
Issue in the new loopback logic which has been temporarily reverted.

**Comment by KaptenJansson** [comment]
Closing due to age.
