### ISSUE TITLE
Muting video should turn off camera

### ISSUE THREAD

**Issue by jyasskin** [webrtc/apprtc#355]
**Browsers and versions affected**
Chrome 54 and Firefox 48, at least

**Description**

**Steps to reproduce**
1. Open https://appr.tc/ and join a room.
2. Mute the video

**Expected results**
The hardware light indicating the camera is recording should turn off.

**Actual results**
The camera keeps recording.

If you do a similar experiment with Google Hangouts, the camera light turns off when you disable video in the web page.

**Comment by KaptenJansson** [comment]
We only mute the track. not the underlying source. If we were, it would result in lots more code, renegotiation of the call etc. Will revisit this when replace track has been implemented.

**Comment by MariasStory** [comment]
Track the status of the feature on the following page: https://www.chromestatus.com/feature/5347809238712320

**Comment by MariasStory** [comment]
Reference for an example of realization:
http://stackoverflow.com/questions/35504214/how-to-addtrack-in-mediastream-in-webrtc

**Comment by twister55** [comment]
Hi everyone! :)

> If we were, it would result in lots more code, renegotiation of the call etc.

Can you explain how to do it theoretically? I saw this in Google Hangouts but I can't found out how to implement it

**Comment by KaptenJansson** [comment]
Sure, PTAL https://blog.mozilla.org/webrtc/warm-up-with-replacetrack/

**Comment by KaptenJansson** [comment]
We will not add this as its not critical for apps function.
