### ISSUE TITLE
Setup continuous running test runs

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/apprtc#359]
**Description**
Currently tests are run on commits, we want to in addition to that add daily runs

**Comment by KaptenJansson** [comment]
cc @hkjellander

**Comment by hkjellander** [comment]
Having daily runs would make it possible for us to catch regressions using Chrome Canary. It's necessary since it can sometimes take weeks between updates to AppRTC (during which time a breaking change in Canary could have sneaked in).

**Comment by KaptenJansson** [comment]
The question is if we can get a hold of canary builds, they are not readily available for download.

**Comment by KaptenJansson** [comment]
Travis now supports cron jobs: https://docs.travis-ci.com/user/cron-jobs/

**Comment by fippo** [comment]
and travis just shipped cron jobs. @hkjellander is there a public url where linux canaries can be downloaded? The [dev channel](http://browsers.contralis.info/linux/chrome/unstable) is typically behind

**Comment by hkjellander** [comment]
@fippo AFAIK there are no official Chrome canary releases available for Linux, but there are Chromium builds that are served from https://download-chromium.appspot.com (will auto-detect your current platform, so use https://download-chromium.appspot.com/?platform=Linux_x64&type=snapshots if you're not browsing from Linux).

**Comment by fippo** [comment]
ah...  one of the disadvantages of that version is that it doesn't have H264 :-/
