### ISSUE TITLE
Is there a free to use TURN server/a place to buy an already installed one ?

### ISSUE THREAD

**Issue by boozi2** [webrtc/apprtc#363]
I've installed my version of apprtc on google app engine. Now i need a TURN server. What is the simplest way to set up one (Don't have a lot of server installing experience, willing to pay for an off the self working server)

**Comment by KaptenJansson** [comment]
I've got no idea what's best but there are COTURN images on [AWS](https://www.google.nl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiNlPHNp_3OAhWHHxoKHWrOBIUQFggpMAA&url=https%3A%2F%2Faws.amazon.com%2F&usg=AFQjCNGktsHCxc6P03bUh3geeEzhbHcXew&bvm=bv.131783435,d.d2s) which are pretty easy to use. You could also use [GCE](https://www.google.nl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiG_a3Jp_3OAhVKSRoKHSY2BrEQFggcMAA&url=https%3A%2F%2Fcloud.google.com%2Fcompute%2Fdocs%2Fimages&usg=AFQjCNHaAAaAac9nxKrnugVZphi-KGgWSg) and in a VM instance install COTURN.

**Comment by boozi2** [comment]
Ok so i have set up the COTURN server on Amazon Ec2 using ubuntu 16.04 server (using the help given here: http://stackoverflow.com/questions/31161864/how-to-create-stun-turn-server-instance-using-aws-ec2).

Now how do i get over the ICE server (https://networktraversal.googleapis.com/v1alpha/iceconfig?key=none) which is for google only use ?

**Comment by KaptenJansson** [comment]
Please check the [Deployment](https://github.com/webrtc/apprtc#deployment) instructions in README.md.
