### ISSUE TITLE
Not able to install closurecompiler

### ISSUE THREAD

**Issue by rbnx** [webrtc/apprtc#365]
I get this error after doing npm install on the home directoy 

> npm ERR! Linux 3.13.0-55-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "configure"
> npm ERR! node v6.4.0
> npm ERR! npm  v3.10.7
> npm ERR! code ELIFECYCLE
> npm ERR! closurecompiler@1.6.0 configure: `node scripts/configure.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the closurecompiler@1.6.0 configure script 'node scripts/configure.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the closurecompiler package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/configure.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs closurecompiler
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls closurecompiler
> npm ERR! There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/vagrant/apprtc/node_modules/closurecompiler/npm-debug.log
> npm ERR! Linux 3.13.0-55-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v6.4.0
> npm ERR! npm  v3.10.7
> npm ERR! code ELIFECYCLE
> 
> npm ERR! closurecompiler@1.6.0 install: `npm run-script configure`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the closurecompiler@1.6.0 install script 'npm run-script configure'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the closurecompiler package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run-script configure
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs closurecompiler
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls closurecompiler
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/vagrant/apprtc/npm-debug.log
> 

the file: /usr/local/lib/node_modules/grunt-closurecompiler/node_modules/closurecompiler/npm-debug.log (mentioned in that log) is empty btw 

> /usr/local/bin/node -v
> v6.4.0

**Comment by KaptenJansson** [comment]
It works fine for me but I'm using node 4.x. Have not tried 6.4.0. It could be that some dependencies are not supported in 6.4.0 yet.
