### ISSUE TITLE
AppRTCDemo Android POST 405 Method Not Allowed

### ISSUE THREAD

**Issue by ubuntutest** [webrtc/apprtc#366]
I'm trying to use apprtc Android.

If I remove the https://appr.tc address and insert the IP address of my server I get the following error:
```

09-09 16:39:05.327 13569-19172/org.appspot.apprtc E/RoomRTCClient: Room connection error: Non-200 response to POST to URL: http://XX.XXX.XXX.XXX:8083/r/45048692 : HTTP/1.1 405 Method Not Allowed
09-09 16:39:05.327 13569-19172/org.appspot.apprtc E/WSRTCClient: Non-200 response to POST to URL: http://XX.XXX.XXX.XXX:8083/r/45048692 : HTTP/1.1 405 Method Not Allowed
```
So if I try to replace POST with GET, the error is as follows:

```
`09-09 16: 44: 48,371 13569-24617 / org.appspot.apprtc E / WSRTCClient: Room JSON parsing error: org.json.JSONException: Value <! DOCTYPE of type java.lang.String can not be converted to JSONObject
```
Unfortunately I can not fix this, the information found on the web or are old or do not solve my problem

**Comment by KaptenJansson** [comment]
Have you setup [Collider](https://github.com/webrtc/apprtc/tree/master/src/collider) and changed your AppRTC instance to use your own Collider in [constants.py](https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py#L32-L40)? The collider instance used by appr.tc is only accessible by appr.tc.

I suggest you read the Deployment [instructions](https://github.com/webrtc/apprtc#deployment)in README.md.

**Comment by ubuntutest** [comment]
Hello KaptenJansson,
I probably incorrectly explained the problem
My WebAPP apprtc working properly for both the web and for iOS
Collider and Turnserver, working well.

The problem is on Android. The apprtcdemo-ANDROID wont work ( https://github.com/njovy/AppRTCDemo )
The problems are those of the first post

**Comment by KaptenJansson** [comment]
I see, it should definetly be GET as you can see [here](https://github.com/webrtc/apprtc/blob/master/src/app_engine/apprtc.py#L570).

Can you post the string it cannot convert to JSON here?

**Comment by ubuntutest** [comment]
A strange thing, If I do not change "join" to "r"

` private static final String ROOM_JOIN = "join";`

My android app tries to connect to networktraversal.googleapis.com
```

org.appspot.apprtc D/RoomRTCClient: WSS url: ws://**.***.***.***:8089/ws
org.appspot.apprtc D/RoomRTCClient: WSS POST url: http://**.***.***.***:8089
org.appspot.apprtc D/RoomRTCClient: Request TURN from: https://networktraversal.googleapis.com/v1alpha/iceconfig?key=none
```
And finding this error
`
org.appspot.apprtc E / WSRTCClient: Room IO error: java.io.IOException: Not-200 response are requesting When TURN server from https://networktraversal.googleapis.com/v1alpha/iceconfig?key=none : HTTP / 1.1 400 Bad Request`

If i change "join" to "r" the app try to connect to my turnserver but getting POST error

```
E/RoomRTCClient: Room connection error: Non-200 response to POST to URL: http://**.***.***.***/r/20333872 : HTTP/1.1 405 Method Not Allowed
E/WSRTCClient: Non-200 response to POST to URL: http://**.***.***.***:8083/r/20333872 : HTTP/1.1 405 Method Not Allowed
```
 When I change the method from POST to GET in some files:
`
 E / WSRTCClient: Room JSON parsing error: org.json.JSONException: Value <! DOCTYPE of type java.lang.String can not be converted to JSONObject`

It try to parse the string as html

```
      SignalingParameters params = new SignalingParameters(
          iceServers, initiator,
          clientId, wssUrl, wssPostUrl,
          offerSdp, iceCandidates);
      events.onSignalingParametersReady(params);
    } catch (JSONException e) {
      events.onSignalingParametersError(
          "Room JSON parsing error: " + e.toString());
    } catch (IOException e) {
      events.onSignalingParametersError("Room IO error: " + e.toString());
    }
  }
```

**Comment by KaptenJansson** [comment]
You should not have to change any constant methods (r and join etc).

Have you set your own turn server and does it return the same [format](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/util.js#L77-L93) as the network traversal ap (which is an ICE server provider)? I changed the response format in https://codereview.webrtc.org/1862423002/ for AppRTCDemo.

**Comment by ubuntutest** [comment]
This part is not totally clear to me.
As I said before my app works correctly on the web and for iOS, even with the 3g / 4g connection, my turnserver and collider works, the format seems to be correct. I followed the instructions

I changed to "join" instead of "r"

It seems that to run Android apps I have to change something constants.py:

```
ICE_SERVER_BASE_URL = 'https://networktraversal.googleapis.com'
ICE_SERVER_URL_TEMPLATE = '% s / v1alpha / iceconfig? Key =% s'
ICE_SERVER_API_KEY = os.environ.get ('ICE_SERVER_API_KEY')
```

**Comment by KaptenJansson** [comment]
iOS has not been updated to the new ICE server provider format , it still uses the old format provided by the CEOD (compute engine on demand turn server provider), i.e. these params in [constants.py](https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py#L14). 

As I mentioned, you should not change the the methods since you will then use a different part of the backend.

**Comment by ubuntutest** [comment]
I restored the default methods.
The old format on IOS working good.
So how to make it working on android too? Is possibile to make it working on both OS?

**Comment by KaptenJansson** [comment]
Please read my comments, take a look at https://codereview.webrtc.org/1862423002/ and revert the code that I changed in the patch.

**Comment by ubuntutest** [comment]
I reversed the code following this link

https://codereview.webrtc.org/1862423002/patch/1/10001
The app building properly
But I get the following error:

```
D / RoomRTCClient: WSS url: ws: //**.***.***.***: 8089 / ws
D / RoomRTCClient: WSS POST url: http: //**.***.***.***: 8089
D / RoomRTCClient: Request TURN from:% s / turn? Username =% s & key =% s
E / WSRTCClient: Room IO error: java.net.MalformedURLException: Protocol not found:% s / turn? Username =% s & key =% s
```

If i manually insert the parameters I get this error:
`E / WSRTCClient: Room JSON parsing error: org.json.JSONException: No value for http: //**.***.***.***: 3478`

Otherwise the same error as before:
`Room JSON parsing error: org.json.JSONException: Value <! DOCTYPE of type java.lang.String can not be converted to JSONObject`

Could you suggest me if i have to enter them manually, and where?

**Comment by KaptenJansson** [comment]
Your URL for the turn request is incorrect.

**Comment by KaptenJansson** [comment]
Have you set https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py#L15 to your own turn server provider (note: not turn server, a web server that returns a JSON with turn servers)?

**Comment by ubuntutest** [comment]
I set this parameter:
TURN_BASE_URL = 'http://**.***.***.***:8083'

I was not sure about the port so I tried to insert also 8089 and 3478
But the answer is always this:

D / RoomRTCClient: Request TURN from:% s / turn? Username =% s & key =% s
E / WSRTCClient: Room IO error: java.net.MalformedURLException: Protocol not found:% s / turn? Username =% s & key =% s

Probably we have to change something else in the code

**Comment by ubuntutest** [comment]
If i set this parameter:
`TURN_BASE_URL = 'http://**.***.***.***/'`

without port and with a trailing slash, this is the result:

```
E/RoomRTCClient: Room connection error: HTTP POST to http://**.***.***.***:8083/join/50000210 timeout
E/WSRTCClient: HTTP POST to http://**.***.***.***:8083/join/50000210 timeout
```

**Comment by ubuntutest** [comment]
Solved:

constants.py
Line 146:
`  if (!isTurnPresent) { ... }`

Should be:
`  if (isTurnPresent) { ... }`

**Comment by KaptenJansson** [comment]
Well as I wrote, you need an ICE Server provider, do you have that? You cannot point it directly at your turn server without modifying the Android code.

**Comment by ubuntutest** [comment]
I would like to point directly, but I think it's too complex for me at the moment. (hard coding?)

The app is installed on my ubuntu server. On the same server there are also installed  the turn and collider
I can create my json file with the parameters inside, but do not know how to name it and where to add it.

You can tell me something?

**Comment by KaptenJansson** [comment]
You can find the JSON format in the **_servers_** variable in step 6 in the [deployment](https://github.com/webrtc/apprtc#deployment) instructions. Just setup a simple web server that responds to a POST message with that JSON message. Then you do not need to change the Android code.

**Comment by ubuntutest** [comment]
Hello, I created the JSON file with this code:
```
{
        credential: "mypwd",
        username: "mypwd",
        urls: [
          "turn:**.***.***.***:3478?transport=udp",
          "turn:**.***.***.***:3478?transport=tcp"
        ];
}
```
And I installed a web server with XAMP.
xampp/htdocs/myJSON.json

Now I can simply enter the address with the main port 8083?
For example:

`TURN_BASE_URL = 'http://51.254.115.249:8083'`

**Comment by ubuntutest** [comment]
Dude I wrote three different json file to test several times in different ways.

Changed many times the url:
`TURN_BASE_URL = 'http://**.***.***.***'

With port, and without port, with full directory ip/myjson.json  or without directory
But still cant solve that, any idea?

**Comment by KaptenJansson** [comment]
You need to investigate the issue at hand, what does web request look like? Can you see it in the webserver logs? Also, you need to make sure it responds to POST (not GET) requests.

For the port, set whatever your webserver listens to.

Also you might want to set TURN_URL_TEMPLATE and CEOD_KEY to an empty string in constants.py since your webserver in this case does not do any authentication (all those three are merged before making the HTTP request).

**Comment by ubuntutest** [comment]
Apparently my web server support POST requests. I'm using a OVH VPS on which I also installed XAMPP.

I used Postman chrome extension.
If I send a POST request to the address http: //**.***.***.*** with port 80 or 8080 etc, the answer is STATUS OK
If i point to http: //**.***.***.***: 8083 (apprtc port), the answer is:

```
         <Title> 405 Method Not Allowed </ title>
         <H1> 405 Method Not Allowed </ h1>
   The method POST is not allowed for this resource.
```
I already put TURN_URL_TEMPLATE and CEOD_KEY as empty fields.

But I did not understand if in "TURN_BASE_URL" parameter I have to enter only the IP address with the port or the full path with the JSON file name.

At the moment everything I write in "TURN_BASE_URL" the answer is always the same:
`E/WSRTCClient: Room IO error: java.net.MalformedURLException: Protocol not found: `

**Comment by KaptenJansson** [comment]
>If I send a POST request to the address http: //...* with port 80 or 8080 etc, the answer is STATUS OK

Do you see your JSON file in the response? I suspect your web server is not responding with the correct JSON file and this AppRTCDemo tries to connect with whatever your webserver is returning. Please try to log the actual data flowing instead of just relying on log messages.

> But I did not understand if in "TURN_BASE_URL" parameter I have to enter only the IP address with the port or the full path with the JSON file name.

URL and no port as when a URL is prefixed with a protocol, in this instance, HTTP, the default port for the protocol will be used which is 80.

**Comment by ubuntutest** [comment]
I'm trying to see what the web server responds by creating a log file.

Meanwhile, please, read the edits of my previous post, I am a bit confused about:
```
TURN_BASE_URL
ICE_SERVER_BASE_URL
```
In step 7 in your documentation you  say to change the ICE parameter and here you tell me to change the TURN.

At the time I deleted the change to utils.js file (step 5), restoring the original file, removing my parameters

**Comment by ubuntutest** [comment]
Can you tell me how to solve that? i've turn server, webserver and json ready

**Comment by ubuntutest** [comment]
Do i have to remove  "/v1alpha/iceconfig?key=none" ?
I have some problems to solve that.
Tell me how to make my webserver return the json, i want to finish it.
The problem isnt only Android App.
Following apprtc deployment instruction (jumping steps 5-6) it wont work

**Comment by KaptenJansson** [comment]
Try to search for how to serve json from a web server. Look at the response you get from the webserver, these are basic debugging steps.

I'm sorry, I do not have the capacity to help you more than I already have.

**Comment by ubuntutest** [comment]
I am sure that something is wrong, it's not like you say, as has already happened in another thread.
You should try to set up your own iceserver and test this problem, I have tried everything.
Good luck

**Comment by Max01010101010101** [comment]
Same problem here... i read everything... and i have the same problem.

**Comment by KaptenJansson** [comment]
I've since updated the documentation hence it should be clearer how to set this up. But in short you need to setup your own AppRTC google app engine instance, Collider for signalling and a Turn/Stun server (COTURN for example) for connectivity.
