### ISSUE TITLE
Unable to start apprtc calls due to "Room server join error"

### ISSUE THREAD

**Issue by cvranjani** [webrtc/apprtc#376]
**Browsers and versions affected**
Chrome version:  53.0.2785.103  / 8530.81.0 stable-channel
All chrome devices

Steps to reproduce:
1. Start an apprtc loopback call using https://appr.tc/?debug=loopback

**Expected results**
Apprtc loopback call should be successfully established

**Actual results**
Apprtc loopback call fails to start and displays following message  : 
"Messages:  
Room server join error: Failed to join the room: Status=500, response=
WebSocket register error: Failed to join the room: Status=500, response=
Version:    
gitHash:    6bbc9ae8a9accf84ea2e92859bdbddeaa7ef58c4
branch:     master
time:       Tue Sep 6 09:55:22 2016 +0200"

Note:
This issue is also observed with apprtc peer2peer calls

[Chrome_device_apprtc_Call_js_console_logs.txt](https://github.com/webrtc/apprtc/files/481301/Chrome_device_apprtc_Call_js_console_logs.txt)

Feedback submitted for this issue:
 @https://feedback.corp.google.com/product/208/neutron?lView=rd&lRSort=1&lROrder=2&lRFilter=1&lReportSearch=user:srcv&lReport=13559992745

@KaptenJansson

**Comment by KaptenJansson** [comment]
I cannot reproduce. I wonder if it's an intermittent server error. When this happens, could you try your corp workstation/laptop on wired corp at the same time?

**Comment by cvranjani** [comment]
Yes. It looks like an intermittent server error. Apprtc calls are successfully established now.
