### ISSUE TITLE
Apprtc ICE SERVER problem

### ISSUE THREAD

**Issue by GiacomoSilli** [webrtc/apprtc#377]
Hello all,
I followed the instructions and I configured my iceserver.
When i change the ICE_SERVER_BASE_URL in costants.py with http: // localhost
The result is this:
```
http: // localhost / v1alpha / iceconfig
ICE request server error: Status = 0, response =
```
If I try to delete:
```
ICE_SERVER_URL_TEMPLATE = '% s / v1alpha / iceconfig? Key =% s'
ICE_SERVER_API_KEY os.environ.get = ('')
```
The result is a blank page, and the application does not work anymore.

**Comment by KaptenJansson** [comment]
Try to set ICE_SERVER_URL_TEMPLATE and ICE_SERVER_API_KEY to and empty string.

**Comment by GiacomoSilli** [comment]
I never entirely deleted it.
I had just left it empy.
```
ICE_SERVER_URL_TEMPLATE = ''
ICE_SERVER_API_KEY = os.environ.get('')
```
As I said, the result is a blank page, from the console I see the following error:
` [HTTP / 1.1 500 Internal Server Error 448ms]`

**Comment by KaptenJansson** [comment]
What server do you on localhost? What port? Does it respond with a json containing turn servers?

**Comment by GiacomoSilli** [comment]
I use the apache web server on ubuntu, default port :80
It should respond with the json file containing the data
But the problem I think is another, anything I write, the page is always white with the same error if those two parameters remain empty.
There is a specific tool to check the server's response?
Tell me and I'll help you check and resolve the problem

**Comment by KaptenJansson** [comment]
> There is a specific tool to check the server's response?
A browser, just check the response in the network dev tools.

**Comment by GiacomoSilli** [comment]
http://imgur.com/a/as2xj port 8083
http://imgur.com/a/cOMBw port 80

**Comment by GiacomoSilli** [comment]
From firefox:
http://imgur.com/a/3Mhqr port 8083

**Comment by GiacomoSilli** [comment]
Any news?

**Comment by KaptenJansson** [comment]
I've now updated AppRTC to allow to use a turn server directly rather than an Ice server provider.

Just enter your turn server info (not ice/turn server provider) directly in https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py#L21-L40 and you should be good to go.

**Comment by GiacomoSilli** [comment]
You rock,
I'll test it asap

**Comment by GiacomoSilli** [comment]
Hi again, finally its working web- apprtcAndroid with 3g/4g too.

Soon i'll test it with iOS, but i have ask to you something.
Its not totally clear to me what it is for:
`REDIRECT_DOMAINS =  []`
If i COMMENT it the app will not work, i just leave it empty.

And about iphone
# TODO(jansson): Remove once AppRTCDemo on iOS supports ICE_SERVER.
```
TURN_BASE_URL = 'https://computeengineondemand.appspot.com'
TURN_URL_TEMPLATE = '%s/turn?username=%s&key=%s'
CEOD_KEY = '4080218913'

ICE_SERVER_BASE_URL = 'https://networktraversal.googleapis.com'
ICE_SERVER_URL_TEMPLATE = '%s/v1alpha/iceconfig?key=%s'
ICE_SERVER_API_KEY = os.environ.get('ICE_SERVER_API_KEY')
```

Do i have to change something here?

**Comment by KaptenJansson** [comment]
# Deprecated domains which we should to redirect to REDIRECT_URL.
REDIRECT_DOMAINS =  [
  'apprtc.appspot.com', 'apprtc.webrtc.org', 'www.appr.tc'
]
# URL which we should redirect to if matching in REDIRECT_DOMAINS.
REDIRECT_URL = 'https://appr.tc'

This only affects our instance of AppRTC. But you can use if you have several URL's pointing to the same instance and you want to redirect to a single URL. In our case, we do not want people using our older domains.

**Comment by ChunJR** [comment]
@GiacomoSilli Hi, can you tell me how to fix AppRTC Android App to work with 3g/4g network..

**Comment by einsteinarbert** [comment]
> @GiacomoSilli Hi, can you tell me how to fix AppRTC Android App to work with 3g/4g network..

config turnserver, but I get an error in android app: CertPathVaildatorException
