### ISSUE TITLE
"Websocket open error" when using nw (node webkit)

### ISSUE THREAD

**Issue by pmenico** [webrtc/apprtc#378]
When I use https://apprtc.appspot.com/r/2762825 from Chrome I have no issues,
But when I load the same using a nw package I get a "Websocket open error: Websocket error."
The error shows up once I press the Join button. The video of myself shows fine on my end.
Any ideas why and how to fix?

The nodewebkit package.json I am using is below:

{
  "main": "https://apprtc.appspot.com/r/2762825",
  "name": "nw-WebRTC",
  "description": "nw-WebRTC",
  "version": "0.1.0",
  "keywords": [ "nw", "node-webkit", "WebRTC", "Video", "nodejs" ],
  "window": {
    "title": "nw-WebRTC",
    "icon": "http://piwas1030/Logo/Logo.png",
    "toolbar": true,
    "frame": true,
    "width": 700,
    "height": 600,
    "position": "center",
    "min_width": 50,
    "min_height": 50,
    "max_width": 1900,
    "max_height": 1900,
	"resizable": true,
	"show_in_taskbar": true,
	"show": true
  },
  "webkit": {
    "plugin": true
  },
  "maintainers":[ {
   "name": "PM",
   "email": "pm@gm.com",
   "web": ""
  }]
}

**Comment by KaptenJansson** [comment]
You cannot use the websocket server from other domains.

**Comment by pmenico** [comment]
Thanks for the prompt response. I am not running this off a server but a desktop. So accessing apprtc using nw.js makes it look like a domain to domain request?

**Comment by KaptenJansson** [comment]
I do not know how nw.js makes the requests since it's a webkit fork. Does it support all the API's that Chrome has? Essentially it's another browser which needs to support all the things that apprtc wants.
