### ISSUE TITLE
Chrome app doesn't send /bye on close.

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#38]
https://github.com/webrtc/samples/issues/437

There are 2 issues.

If you close the app window, no bye message is sent, because onbeforeunload is not available in Chrome Apps
Sync xhr is not available in Chrome apps, so even when you hit hangup, the messages don't get sent.
I started working on these but it isn't as simple as changing the xhr to async, because there is a specific ordering we need, and we need to finish the work before the window closes. I'll continue to work on a fix.
Jiayang Liu
 Owner
 jiayliu commented 6 days ago
Is there a solution for the first issue?
…
Chuck Hays
 Owner
chuckhays commented 6 days ago
The background.js file can detect when the window closes, and can do the cleanup. This is how it can be hooked up:
chuckhays@e1a48f5

The next step is to re-arrange things so the needed context is still available. Chrome starts disposing objects that we still need in order to make the ending calls.

**Comment by jiayliu** [comment]
Just for the record, we should fix this one before we release the app to wider audience.

**Comment by KaptenJansson** [comment]
What's the status of this app? Should we still fix this?

**Comment by juberti** [comment]
Not a priority ATM.

**Comment by KaptenJansson** [comment]
Closing due to age.
