### ISSUE TITLE
Uncaught TypeError thrown during an unsuccessful 2 way apprtc call

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#380]
**Browsers and versions affected**
Win 10, M55 Canary 55.0.2872.0

**Description**
Uncaught TypeError: Cannot read property 'receiveSignalingMessage' of null 
error thrown when a 2 way apprtc call couldn't connect successfully

**Steps to reproduce**
1. Start a 2 way apprtc call over a slow internet connection 
2. Observe the JS console

**Expected results**
The apprtc call should connect successfully, albeit with some delay; No JS console errors should be seen

**Actual results**
"Uncaught TypeError: Cannot read property 'receiveSignalingMessage' of null" error thrown

Screenshot:

![image](https://cloud.githubusercontent.com/assets/14947786/18851938/0d49c98a-83f3-11e6-8170-c79ad46e4449.png)

CC: @KaptenJansson

**Comment by cvranjani** [comment]
Github issue filed for similar error : https://github.com/webrtc/samples/issues/763

**Comment by KaptenJansson** [comment]
Intermittent issue but closing due to age.

**Comment by zeta92** [comment]
@srnarayanan Did you solve this error? i am having the same error
