### ISSUE TITLE
"addNewFabric: Arguments missing/Invalid" error seen after an apprtc loopback call

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#383]
**Browsers and versions affected**
M55 Canary 55.0.2880.0 in Mac 10.11.6

**Description**
"addNewFabric: Arguments missing/Invalid" error seen after an apprtc loopback call

**Steps to reproduce**
1. Establish a H264 apprtc loopback call https://appr.tc/r/424898770?debug=loopback&vsc=h264
2. After checking stats of the call, hang up 
3. Let the tab be as is, for a while

**Expected results**
No JS errors should be seen during and after the call

**Actual results**
"addNewFabric: Arguments missing/Invalid" error seen, after a while (I let the tab be as is for close to 30 mins)

Screenshot:

![screen shot 2016-10-04 at 2 12 03 pm](https://cloud.githubusercontent.com/assets/14947786/19093282/5f834a30-8a3f-11e6-9ba0-5b42d70629d1.png)

CC @KaptenJansson

**Comment by karthikbr82** [comment]
@KaptenJansson is this happening still??

**Comment by KaptenJansson** [comment]
I've not seen it, @srnarayanan have you?

**Comment by srnarayanan** [comment]
@KaptenJansson - I haven't seen this error in a while
