### ISSUE TITLE
collider install error: non-standard import "golang.org/x/net/websocket"

### ISSUE THREAD

**Issue by aprilsam** [webrtc/apprtc#384]
**Browsers and versions affected**
CentOS7, go1.7.1

**Description**
I've installed go and write a Hello World to run, it's OK.
Then I entered 'go get collidermain' on terminal. It prompt me: cannot find package "golang.org/x/net/websocket" in any of:
	/program/go/src/vendor/golang.org/x/net/websocket (vendor tree)
	/program/go/src/golang.org/x/net/websocket (from $GOROOT)
	/program/go/work/src/golang.org/x/net/websocket (from $GOPATH)

So, I entered 'go get golang.org/x/net/websocket', 'go install golang.org/x/net/websocket' to get & install websocket. The package installed successfully.

But when I entered 'go get collidermain' on terminal, it still failed however. It print that:
/program/go/src/collider/collider.go:11:2: non-standard import "golang.org/x/net/websocket" in standard package "collider"

If anyone can help me solve this problem? Thanks!

**Steps to reproduce**
After installed go and linked the collider directories into $GOPATH/src
# go get golang.org/x/net/websocket
# go install golang.org/x/net/websocket
# go get collidermain

**Expected results**
No message appear.

**Actual results**
non-standard import "golang.org/x/net/websocket" in standard package "collider"

**Comment by hustwei** [comment]
The same with me!

root@complie-desktop:/var/go/src# go get collider
can't load package: /var/go/src/collider/collider.go:11:2: non-standard import "golang.org/x/net/websocket" in standard package "collider"
root@complie-desktop:/var/go/src# go get collidermain
/var/go/src/collider/collider.go:11:2: non-standard import "golang.org/x/net/websocket" in standard package "collider"

**Comment by KaptenJansson** [comment]
https://godoc.org/golang.org/x/net/websocket still says it's valid, I've not tried go 1.7.1. Could you try 1.6 and report back?

**Comment by savayg** [comment]
got the same error and solved it fixing the workspace `GOPATH: /usr/local/goWorkspace` and properly linking collider files to the $GOPATH/src folder as explained in the docs.

**Comment by KaptenJansson** [comment]
Aha I assumed everyone had followed the instructions ;)

**Comment by aprilsam** [comment]
As KaptenJansson said,
> https://godoc.org/golang.org/x/net/websocket still says it's valid, I've not tried go 1.7.1. Could you try 1.6 and report back?

It runs successfully in GO 1.6. Thanks a lot!!! @KaptenJansson

**Comment by savayg** [comment]
@aprilsam I got it successfully running in Go 1.7.3

**Comment by aprilsam** [comment]
How do you do that? @savayg

**Comment by savayg** [comment]
@aprilsam just followed the repo instructions, I got this error because I confused the $GOROOT and $GOPATH env vars

**Comment by aprilsam** [comment]
I set the right $GOROOT and $GOPATH but still in error. Only I use GO 1.6 then it runs successfully.

**Comment by nathando** [comment]
I just tried it with **go1.9** version and the same thing happen. The server is Ubuntu 16.04 and have this in my `.bash_profile` (the GOROOT is just to make sure...) :  

```
export GOPATH=$HOME/goWorkpace
export GOROOT=/usr/local/go
```
Did any one resolve it ?

**Comment by aprilsam** [comment]
@nathando You should try go 1.6 instead.

**Comment by nathando** [comment]
@aprilsam yup in the end, i use the `apt-get install golang-go` on Ubuntu and got the 1.6 version. It works!

**Comment by einsteinarbert** [comment]
> I just tried it with **go1.9** version and the same thing happen. The server is Ubuntu 16.04 and have this in my `.bash_profile` (the GOROOT is just to make sure...) :
> 
> ```
> export GOPATH=$HOME/goWorkpace
> export GOROOT=/usr/local/go
> ```
> Did any one resolve it ?

$GOROOT="your go code extracted from zip: g.tar.gz"
for example: 
~/Documents/webrtc/go$ tree -L 1
.
├── api
├── AUTHORS
├── bin
├── CONTRIBUTING.md
├── CONTRIBUTORS
├── doc
├── favicon.ico
├── helloworld
├── lib
├── LICENSE
├── misc
├── PATENTS
├── pkg
├── README.md
├── robots.txt
├── src
├── test
└── VERSION
$GOPATH="your workspace with src folder"
for example:
~/Documents/webrtc/collider$ tree -L 2
.
├── bin
│   └── collidermain
├── pkg
│   └── linux_amd64
└── src
    ├── collider -> /media/huyen/Data/workspace/apprtc/src/collider/collider
    ├── collidermain -> /media/huyen/Data/workspace/apprtc/src/collider/collidermain/
    ├── collidertest -> /media/huyen/Data/workspace/apprtc/src/collider/collidertest
    ├── github.com
    ├── golang.org
    └── hello
**Note, rename ~/Documents/webrtc/go/src/vendor/golang_org -> golang.org**
`~> cd golang.org/x/`
**and `git clone https://github.com/gorilla/websocket`**
Finally go to your workspace and install collinder:
```
cd ~/Documents/webrtc/collider/src
 go get collidermain
 go install collidermain
```

**Comment by einsteinarbert** [comment]
when type link: ln -s  
something wrong with thi link of collider in go/src
NOTICE: collidermain, collider, collidertest link must be inside go/src/ folder
