### ISSUE TITLE
AppRTC no longer allows mic-only and cam-only Firefox users to participate (regression)

### ISSUE THREAD

**Issue by jan-ivar** [webrtc/apprtc#385]
**Browsers and versions affected**
Firefox 49 (release) and newer

**Description**
Starting with Firefox 49, a user with only a mic and no camera can no longer talk on an AppRTC call (presumably the reverse is true as well, a user with camera but no mic can't be seen).

Firefox 49 updated to follow [the spec](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediadevices-getusermedia), which says to fail an audio+video request unless both are available.

**Steps to reproduce**
Join an appRTC call from a machine with mic only and no camera.

**Expected results**
- Joins conversation by sending audio only, and still receives audio+video whatever.

**Actual results**
- "Failed to get access to local media. Error name was NotFoundError. Continuing without sending a stream." [OK]
- Joins conversation without sending audio (still receives audio+video whatever).

**Comment by KaptenJansson** [comment]
I've pushed a new release of AppRTC with the latest adapter release, could you please verify?

**Comment by jan-ivar** [comment]
WFM, Thanks!

**Comment by KaptenJansson** [comment]
No problem and thanks for the fix!
