### ISSUE TITLE
How to make appRTC listen on its host's IPV4 ?

### ISSUE THREAD

**Issue by mojostelar** [webrtc/apprtc#392]
Hello,

I've installed appRTC on a Debian server.

Output at launch : 

> INFO     2016-11-06 10:02:33,024 sdk_update_checker.py:229] Checking for updates to the SDK.
> INFO     2016-11-06 10:02:33,250 sdk_update_checker.py:257] The SDK is up to date.
> INFO     2016-11-06 10:02:33,289 api_server.py:205] Starting API server at: http://localhost:56817
> INFO     2016-11-06 10:02:33,296 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
> INFO     2016-11-06 10:02:33,297 admin_server.py:116] Starting admin server at: http://localhost:8000

Seems like appRTC is only listening to its host's loopback. I've read some documentation about Google AppEngine SDK and figured out that creating a file called `dispatch.yaml` might solve my problem : 

```
dispatch:
  # Default module serves simple hostname request.
  - url: "<IPV4 ADRESS>:8080/"
    module: default
```

I've rebuilt appRTC with this file, yet nothing seems to change.
Right now I only can access appRTC using two paths: 

Locally by using host's web browser, typing localhost:8080
Externally by using SSH tunneling, typing localhost:8080

I want anyone to be able to access appRTC externally just by typing <IPV4 ADRESS>:8080

How do I do that ?

Thanks in advance.

**Comment by KasusKnaxus** [comment]
There is a parameter for your dev_appserver.py called --host. You can use --host=0.0.0.0 to addess via <IPV4 ADRESS>:8080
http://stackoverflow.com/questions/15513064/address-0-0-0-0-argument-not-working-after-upgrading-to-app-engine-1-7-6

**Comment by KaptenJansson** [comment]
Yes the above comment is correct. Do note that dev_appserver.py is a development tool, not for production deployment.
