### ISSUE TITLE
getStats not showing in apprtc.appspot.com UI

### ISSUE THREAD

**Issue by svarunan** [webrtc/apprtc#395]
I remember i was able to see getstats report in UI on https://apprtc.appspot.com, some months before. 
It appeared in some red background with all stats, now i'm not seeing it. 

Im not seeing any param in https://apprtc.appspot.com/params.html to enable it back. I want to see it for my reference. Do any one knows how to enable? Thanks

**Comment by KaptenJansson** [comment]
press 'i'

**Comment by svarunan** [comment]
Thanks @KaptenJansson

**Comment by KaptenJansson** [comment]
No problem ;) I want to add a shortcut help UI one day......
