### ISSUE TITLE
Problem with the command npm install

### ISSUE THREAD

**Issue by CristianAlvear** [webrtc/apprtc#399]
Hi, I an Cristian Alvear

I have a problem with the command npm install, when I put this  command.

I have this problem:

root@cristian-virtual-machine:/home/cristian# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/cristian/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/cristian
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/cristian/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/cristian/npm-debug.log
npm ERR! not ok code 0

root@cristian-virtual-machine:/home/cristian# cd /usr/bin
root@cristian-virtual-machine:/usr/bin# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/usr/bin/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/bin
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/bin/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/bin/npm-debug.log
npm ERR! not ok code 0
root@cristian-virtual-machine:/usr/bin# 

I don´t know, what happens.

Please, help me.

Thanks for your attention

**Comment by KaptenJansson** [comment]
You are running npm install outside of the AppRTC source directory (root@cristian-virtual-machine:/home/cristian). First navigate to the AppRTC source directory and try again.
