### ISSUE TITLE
Apprtc calls are failing with Websocket connection failures

### ISSUE THREAD

**Issue by cvranjani** [webrtc/apprtc#405]
**Browsers and versions affected**
Chrome OS version : 56.0.2924.28 / 9000.29.0 beta
All chrome OS devices

**Steps to reproduce**
Join an apprtc loopback call using https://appr.tc/?debug=loopback

Expected result:
Apprtc call should connect successfully without any errors

Actual result:
Apprtc call is not connecting and failing with error message : 
"Messages:  
WebSocket open error: WebSocket error.
WebSocket register error: WebSocket error

Version:    
gitHash:    742b12785c6e6876a2ec96dca1f07d82b40f0dca
branch:     master
time:       Mon Dec 12 11:22:18 2016 +0100 "
(Notice that timestamp is incorrect)
 
Notes:
1) This issue is also observed in peer2pper apprtc calls
2) Feedback submitted for this issue: 
Id:50521324092

[Sumo_log-122016-101716.tar.gz](https://github.com/webrtc/apprtc/files/664485/Sumo_log-122016-101716.tar.gz)
[Sumo_apprtc_loopback_js_logs.txt](https://github.com/webrtc/apprtc/files/664495/Sumo_apprtc_loopback_js_logs.txt)

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by srnarayanan** [comment]
This issue is seen in Chrome M57 in Linux, Mac as well.

Attached screenshot

![screen shot 2016-12-20 at 10 54 43 am](https://cloud.githubusercontent.com/assets/14947786/21363792/df2f9bea-c6a2-11e6-8a12-2f68c48bbb9d.png)

**Comment by uysalere** [comment]
It should be back up now.

**Comment by cvranjani** [comment]
Yes. It is working now. Thanks uysalere@
