### ISSUE TITLE
Warning: Error: Unable to access jarfile undefined

### ISSUE THREAD

**Issue by zzhanga** [webrtc/apprtc#408]
Hello,every body.I have a problem:

root@192:~/code/apprtc# grunt build
Running "shell:buildAppEnginePackage" (shell) task
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
Copying socket.io.js
File found socket.io.js

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
java=/root/install_packge/java/jdk1.7.0_07/bin/java
java2222=/root/install_packge/java/jdk1.7.0_07/bin/java
true
java=/root/install_packge/java/jdk1.7.0_07/bin/java
java2222=/root/install_packge/java/jdk1.7.0_07/bin/java
run
run-XX:+TieredCompilation,-Xmx1024m,-jar,,--js,node_modules/webrtc-adapter/out/adapter.js,--js,src/web_app/js/analytics.js,--js,src/web_app/js/enums.js,--js,src/web_app/js/appcontroller.js,--js,src/web_app/js/call.js,--js,src/web_app/js/constants.js,--js,src/web_app/js/infobox.js,--js,src/web_app/js/peerconnectionclient.js,--js,src/web_app/js/remotewebsocket.js,--js,src/web_app/js/roomselection.js,--js,src/web_app/js/sdputils.js,--js,src/web_app/js/signalingchannel.js,--js,src/web_app/js/stats.js,--js,src/web_app/js/storage.js,--js,src/web_app/js/util.js,--js,src/web_app/js/windowport.js,--compilation_level,WHITESPACE_ONLY,--language_in,ECMASCRIPT5,--formatting,PRETTY_PRINT
{ [Error: 1] code: 1, signal: null }
Warning: Error: Unable to access jarfile undefined
 Use --force to continue.

Aborted due to warnings.

please help me,thanks

**Comment by KaptenJansson** [comment]
You have to run grunt build from the apprtc root folder, not src.

**Comment by zzhanga** [comment]
root@192:~/code/apprtc# grunt build
Running "shell:buildAppEnginePackage" (shell) task
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
Copying socket.io.js
File found socket.io.js

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
java=/root/install_packge/java/jdk1.7.0_07/bin/java
java2222=/root/install_packge/java/jdk1.7.0_07/bin/java
true
java=/root/install_packge/java/jdk1.7.0_07/bin/java
java2222=/root/install_packge/java/jdk1.7.0_07/bin/java
run
run-XX:+TieredCompilation,-Xmx1024m,-jar,,--js,node_modules/webrtc-adapter/out/adapter.js,--js,src/web_app/js/analytics.js,--js,src/web_app/js/enums.js,--js,src/web_app/js/appcontroller.js,--js,src/web_app/js/call.js,--js,src/web_app/js/constants.js,--js,src/web_app/js/infobox.js,--js,src/web_app/js/peerconnectionclient.js,--js,src/web_app/js/remotewebsocket.js,--js,src/web_app/js/roomselection.js,--js,src/web_app/js/sdputils.js,--js,src/web_app/js/signalingchannel.js,--js,src/web_app/js/stats.js,--js,src/web_app/js/storage.js,--js,src/web_app/js/util.js,--js,src/web_app/js/windowport.js,--compilation_level,WHITESPACE_ONLY,--language_in,ECMASCRIPT5,--formatting,PRETTY_PRINT
{ [Error: 1] code: 1, signal: null }
Warning: Error: Unable to access jarfile undefined
 Use --force to continue.

Aborted due to warnings.

**Comment by zzhanga** [comment]
@KaptenJansson thank you，but the problem remains

root@192:~/code/apprtc# grunt build
Running "shell:buildAppEnginePackage" (shell) task
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
Copying socket.io.js
File found socket.io.js

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
java=/root/install_packge/java/jdk1.7.0_07/bin/java
java2222=/root/install_packge/java/jdk1.7.0_07/bin/java
true
java=/root/install_packge/java/jdk1.7.0_07/bin/java
java2222=/root/install_packge/java/jdk1.7.0_07/bin/java
run
run-XX:+TieredCompilation,-Xmx1024m,-jar,,--js,node_modules/webrtc-adapter/out/adapter.js,--js,src/web_app/js/analytics.js,--js,src/web_app/js/enums.js,--js,src/web_app/js/appcontroller.js,--js,src/web_app/js/call.js,--js,src/web_app/js/constants.js,--js,src/web_app/js/infobox.js,--js,src/web_app/js/peerconnectionclient.js,--js,src/web_app/js/remotewebsocket.js,--js,src/web_app/js/roomselection.js,--js,src/web_app/js/sdputils.js,--js,src/web_app/js/signalingchannel.js,--js,src/web_app/js/stats.js,--js,src/web_app/js/storage.js,--js,src/web_app/js/util.js,--js,src/web_app/js/windowport.js,--compilation_level,WHITESPACE_ONLY,--language_in,ECMASCRIPT5,--formatting,PRETTY_PRINT
{ [Error: 1] code: 1, signal: null }
Warning: Error: Unable to access jarfile undefined
 Use --force to continue.

Aborted due to warnings.

**Comment by KaptenJansson** [comment]
Are you in the git checkout? There are two warnings at the top indicating that you are not:

```
root@192:~/code/apprtc# grunt build
Running "shell:buildAppEnginePackage" (shell) task
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by zzhanga** [comment]
@KaptenJansson no，but The code was downloaded this morning

**Comment by zzhanga** [comment]
@KaptenJansson thank you，I Reinstall the npm and grunt，the problem is over
