### ISSUE TITLE
easy install process available?

### ISSUE THREAD

**Issue by suhashpatil** [webrtc/apprtc#409]
**Browsers and versions affected**
All

**Description**
We have spent close to 6 days in just trying to install webrtc/apprtc on an Ubuntu server here and have failed to properly set it up. Is there an idiotproof version of the install procedure that we can use to install on a "3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux"

**Steps to reproduce**
Followed all instructions to the "t" and still failing. Used https://github.com/webrtc/apprtc documentation and all that it refers to go through the steps. 

**Expected results**
Running installation !

**Actual results**
1. We are able to run the server when we access localhost:8080 and able to join room but when we run with IP address it simply refuses to run. This prevents to access the server from other devices.
2. grunt runPythonTests shows following errors.
Running "shell:pipInstall" (shell) task
Requirement already satisfied (use --upgrade to upgrade): urllib3[secure]==1.19.1 in /home/suhas/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
  Installing extra requirements: 'secure'
Requirement already satisfied (use --upgrade to upgrade): requests==2.12.4 in /home/suhas/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): webtest==2.0.24 in /home/suhas/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Cleaning up...

Running "shell:ensureGoogleAppEngineIsInstalled" (shell) task
Already has google_appengine_1.9.49.zip, skipping

Running "shell:buildAppEnginePackageWithTests" (shell) task
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Traceback (most recent call last):
  File "./build/build_app_engine_package.py", line 172, in <module>
    sys.exit(main())
  File "./build/build_app_engine_package.py", line 165, in main
    downloadCallstats()
  File "./build/build_app_engine_package.py", line 112, in downloadCallstats
    % os.path.join('node_modules', dirpath, deps[dirpath]))
KeyError: 'out/app_engine/third_party/callstats/'
Warning: Command failed: python ./build/build_app_engine_package.py src out/app_engine --include-tests
Traceback (most recent call last):
  File "./build/build_app_engine_package.py", line 172, in <module>
    sys.exit(main())
  File "./build/build_app_engine_package.py", line 165, in main
    downloadCallstats()
  File "./build/build_app_engine_package.py", line 112, in downloadCallstats
    % os.path.join('node_modules', dirpath, deps[dirpath]))
KeyError: 'out/app_engine/third_party/callstats/'
 Use --force to continue.

Aborted due to warnings.

**Comment by MirkoBonadei** [comment]
Hi @suhashpatil,

I tried to reproduce your bug on my local environment and it seems that you need to install the node module `socket.io-client`.
Unfortunately the error message is really cryptic and I have tried to fix it with this pull request (webrtc/apprtc#410).

While we are waiting for a review you can run `npm update` or (`npm install` if you have not run it yet) and then try to launch the `grunt runPythonTests` command again.

I don't think this solves the problem with the ip address binding. I will try to investigate on that.

**Comment by MirkoBonadei** [comment]
Can you send me more details about the crash that you have when running with `--host`?

**Comment by suhashpatil** [comment]
I installed socket.io-client and then used your version of (unapproved file) and reran the grunt runPythonTests command. I got following error:
Running "shell:buildAppEnginePackageWithTests" (shell) task
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
Copying socket.io.js
File found socket.io.js

Running "shell:runPythonTests" (shell) task
You need to install webtest dependencies before you can proceed 
running the tests. To do this you need to have pip installed.
Go to https://packaging.python.org/installing/ and follow the 
instructions and then rerun the grunt command.
Warning: Command failed: python build/run_python_tests.py temp/google_appengine/ out/app_engine
 Use --force to continue.

Aborted due to warnings.

**Comment by MirkoBonadei** [comment]
Ok, seems that you are missing some deps.
Please try to run `grunt --verbose` and let me know.

I agree that the README should be updated. I will try to update is asap.

**Comment by suhashpatil** [comment]
With --verbose mode: 

Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
Copying socket.io.js
File found socket.io.js

Running "shell:runPythonTests" (shell) task
Verifying property shell.runPythonTests exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: python build/run_python_tests.py temp/google_appengine/ out/app_engine
You need to install webtest dependencies before you can proceed 
running the tests. To do this you need to have pip installed.
Go to https://packaging.python.org/installing/ and follow the 
instructions and then rerun the grunt command.
Warning: Command failed: python build/run_python_tests.py temp/google_appengine/ out/app_engine
 Use --force to continue.

Aborted due to warnings.

**Comment by MirkoBonadei** [comment]
Ok, it seems that you don't have `pip` installed. We use `pip` to install some dependencies.
Please follow [these instructions](https://pip.pypa.io/en/stable/installing/) and let me know.

**Comment by suhashpatil** [comment]
No. pip is installed and was always present.

**Comment by suhashpatil** [comment]
suhas@suhas:~/apprtc$ which pip
/usr/bin/pip
suhas@suhas:~/apprtc$ pip

Usage:   
  pip <command> [options]

Commands:
  install                     Install packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
....

**Comment by suhashpatil** [comment]
OK. I upgraded the pip to latest version  and reran grunt. got  "Done, without errors."!

**Comment by MirkoBonadei** [comment]
Ok, that's nice.

Can you confirm that you are able to run `apprtc` with the `--host` now?

**Comment by suhashpatil** [comment]
I copied a js file by hand to a directory:
cp ./out/chrome_app/js/apprtc.debug.js out/app_engine/js/

I then ran:
$ ~/apprtc$ /usr/local/google-cloud-sdk/bin/dev_appserver.py --host 192.168.1.73 --port 8080 ./out/app_engine/

Now it is complaining about not having TURN server and not running in secure mode. I investigated TURN server configuration but the documentation https://github.com/coturn/coturn/wiki/CoturnConfig is incomplete and I don't know where I need to modify following: 
var pc_config = {"iceServers": [{"url": "stun:stun.l.google.com:19302"},
                        {"url":"turn:my_username@<turn_server_ip_address>", 
                                          "credential":"my_password"}]};
        pc_new = new webkitRTCPeerConnection(pc_config);
I am still grep'ing and trying to figure out how all this is supposed to work. 


====
Waiting for someone to join this room: http://192.168.1.73:8080/r/149999361
States:     
Signaling:  have-local-offer
Gathering:  complete
Connection: new
Local:      host:1
Remote:     

Stats:      
Call time:  03:04
Setup time: 0 ms

Messages:  
Error getting user media: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
getUserMedia error: Failed to get access to local media. Error name was NotSupportedError. Continuing without sending a stream.

Version:    
gitHash:    a75615ce85560ffd9ec98f5b269b6e1ca5a9c2d7
branch:     master
time:       Thu Dec 29 10:28:45 2016 +0100
No TURN server; unlikely that media will traverse networks. If this persists please report it to discuss-webrtc@googlegroups.com.

**Comment by suhashpatil** [comment]
I can offer to write a clean install script and configure and run document. Let me know how I can help.
Ideally, I want instructions like so:
1. unzip this tarfile
2. modify these variables in this config file.
3. test your modifications through these commands.
4. run 

I can make them in this form while hiding all intricacies that only developers need to know.

**Comment by bandish2189** [comment]
Hello Suhash,
I need little help here...

i sucked on applying grunt command.. can you help me please.

**Comment by suhashpatil** [comment]
"i sucked on applying grunt command." Don't know what you mean here. 

How can I help?

**Comment by MirkoBonadei** [comment]
@suhashpatil please take a look [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/efuWL9JqoOo/MMVumBzmFAAJ) for the problem with `Error getting user media: Only secure origins are allowed`. `localhost` is considered secure while any other host should be on `https` which is not supported by `dev_appserver.py`. So to run with an ip address as host you have to read the link and use that flag ` --unsafely-treat-insecure-origin-as-secure` when you start your chrome browser (this should only be used for development).

**Comment by MirkoBonadei** [comment]
@suhashpatil don't worry about the instructions. I was to review them because some stuff can be removed.

**Comment by KaptenJansson** [comment]
@suhashpatil For TURN settings, start at Step 4 in the Deployment [instructions](https://github.com/webrtc/apprtc#deployment) and go to [TURN/STUN](https://github.com/webrtc/apprtc#turnstun).
