### ISSUE TITLE
Memcache sometimes inconsistent and lost room record

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#41]
I got a report of two users in two countries cannot connect to each other, each sitting in a room waiting as the first user. 
It's possible because the memcache is not guaranteed to be consistent across data centers.
I've not found any documentation around this.
Needs investigation.

**Comment by jiayliu** [comment]
Did a quick test between KIR and STO. Call succeeded 4 out of 5, where the failed room somehow lost its memcache record and a new user cannot see the initiator even on the same machine. So the memcache inconsistency may be unrelated to geo-distribution or data center.

**Comment by juberti** [comment]
My understanding was that for a given app, you get a single memcache server (somewhere in the world), and all calls are serialized. So that is consistent with what you are seeing.

Can you tell anything about why the memcache record was lost?

**Comment by jiayliu** [comment]
Not reproducible.
