### ISSUE TITLE
How to setup TURN,STUN,ICE servers easy elaborated documentation available? 

### ISSUE THREAD

**Issue by phoenixvk** [webrtc/apprtc#411]
**I get successful in creating collider.** 

How should I setup TURN,STUN,ICE servers? 

I'm doing all this stuff on my local machine.

**HERE IS OUTPUT OF MY  grunt --verbose**
`/apprtc$ grunt --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-contrib-csslint" local Npm module tasks.
Reading /home/suhas/apprtc/node_modules/grunt-contrib-csslint/package.json...OK
Parsing /home/suhas/apprtc/node_modules/grunt-contrib-csslint/package.json...OK
Loading "csslint.js" tasks...OK
+ csslint

Registering "grunt-htmlhint" local Npm module tasks.
Reading /home/suhas/apprtc/node_modules/grunt-htmlhint/package.json...OK
Parsing /home/suhas/apprtc/node_modules/grunt-htmlhint/package.json...OK
Loading "htmlhint.js" tasks...OK
+ htmlhint

Registering "grunt-shell" local Npm module tasks.
Reading /home/suhas/apprtc/node_modules/grunt-shell/package.json...OK
Parsing /home/suhas/apprtc/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell

Registering "grunt-closurecompiler" local Npm module tasks.
Reading /home/suhas/apprtc/node_modules/grunt-closurecompiler/package.json...OK
Parsing /home/suhas/apprtc/node_modules/grunt-closurecompiler/package.json...OK
Loading "closurecompiler.js" tasks...OK
+ closurecompiler

Registering "grunt-eslint" local Npm module tasks.
Reading /home/suhas/apprtc/node_modules/grunt-eslint/package.json...OK
Parsing /home/suhas/apprtc/node_modules/grunt-eslint/package.json...OK
Loading "eslint.js" tasks...OK
+ eslint

Registering "build/grunt-chrome-build" tasks.

Registering "grunt-contrib-compress" local Npm module tasks.
Reading /home/suhas/apprtc/node_modules/grunt-contrib-compress/package.json...OK
Parsing /home/suhas/apprtc/node_modules/grunt-contrib-compress/package.json...OK
Loading "compress.js" tasks...OK
+ compress

Registering "grunt-jinja" local Npm module tasks.
Reading /home/suhas/apprtc/node_modules/grunt-jinja/package.json...OK
Parsing /home/suhas/apprtc/node_modules/grunt-jinja/package.json...OK
Loading "jinja.coffee" tasks...OK
+ jinja
Loading "grunt-chrome-build.js" tasks...OK
+ grunt-chrome-build, grunt-chrome-build-compress, grunt-chrome-build-package, grunt-chrome-build-transform
Loading "Gruntfile.js" tasks...OK
+ build, default, runLinting, runPythonTests, runUnitTests

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "runLinting" task

Running "csslint" task

Running "csslint:strict" (csslint) task
Verifying property csslint.strict exists in config...OK
Files: src/web_app/css/main.css
Options: csslintrc="build/.csslintrc", import=2
Reading build/.csslintrc...OK
Reading src/web_app/css/main.css...OK
Linting src/web_app/css/main.css...OK
>> 1 file lint free.

Running "csslint:lax" (csslint) task
Verifying property csslint.lax exists in config...OK
Files: src/web_app/css/main.css
Options: csslintrc="build/.csslintrc", import=false
Reading build/.csslintrc...OK
Reading src/web_app/css/main.css...OK
Linting src/web_app/css/main.css...OK
>> 1 file lint free.

Running "htmlhint" task

Running "htmlhint:html1" (htmlhint) task
Verifying property htmlhint.html1 exists in config...OK
Files: src/web_app/html/full_template.html, src/web_app/html/index_template.html
Options: force=false
Reading src/web_app/html/full_template.html...OK
Reading src/web_app/html/index_template.html...OK
OK
>> 2 files lint free.

Running "eslint" task

Running "eslint:target" (eslint) task
Verifying property eslint.target exists in config...OK
Files: src/web_app/js/analytics.js, src/web_app/js/analytics_test.js, src/web_app/js/appcontroller.js, src/web_app/js/appcontroller_test.js, src/web_app/js/appwindow.js, src/web_app/js/background.js, src/web_app/js/background_test.js, src/web_app/js/call.js, src/web_app/js/call_test.js, src/web_app/js/constants.js, src/web_app/js/infobox.js, src/web_app/js/infobox_test.js, src/web_app/js/loopback.js, src/web_app/js/peerconnectionclient.js, src/web_app/js/peerconnectionclient_test.js, src/web_app/js/remotewebsocket.js, src/web_app/js/remotewebsocket_test.js, src/web_app/js/roomselection.js, src/web_app/js/roomselection_test.js, src/web_app/js/sdputils.js, src/web_app/js/sdputils_test.js, src/web_app/js/signalingchannel.js, src/web_app/js/signalingchannel_test.js, src/web_app/js/stats.js, src/web_app/js/storage.js, src/web_app/js/test_mocks.js, src/web_app/js/testpolyfills.js, src/web_app/js/util.js, src/web_app/js/utils_test.js, src/web_app/js/windowport.js -> target
Options: outputFile=false, quiet=false, maxWarnings=-1, configFile="build/.eslintrc"

Running "runPythonTests" task

Running "shell:pipInstall" (shell) task
Verifying property shell.pipInstall exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: pip install --user --requirement requirements.txt
Requirement already satisfied: urllib3[secure]==1.19.1 in /home/suhas/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests==2.12.4 in /home/suhas/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: webtest==2.0.24 in /home/suhas/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: idna>=2.0.0; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: cryptography>=1.3.4; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: certifi; extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: ipaddress; python_version <= "2.7" and extra == "secure" in /home/suhas/.local/lib/python2.7/site-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: WebOb>=1.2 in /home/suhas/.local/lib/python2.7/site-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied: beautifulsoup4 in /home/suhas/.local/lib/python2.7/site-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied: waitress>=0.8.5 in /home/suhas/.local/lib/python2.7/site-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied: pyasn1>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]==1.19.1->-r requirements.txt (line 1))

Running "shell:ensureGoogleAppEngineIsInstalled" (shell) task
Verifying property shell.ensureGoogleAppEngineIsInstalled exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: python build/ensure_google_app_engine_is_installed.py
Already has google_appengine_1.9.49.zip, skipping

Running "shell:buildAppEnginePackageWithTests" (shell) task
Verifying property shell.buildAppEnginePackageWithTests exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: python ./build/build_app_engine_package.py src out/app_engine --include-tests
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
Copying socket.io.js
File found socket.io.js

Running "shell:runPythonTests" (shell) task
Verifying property shell.runPythonTests exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: python build/run_python_tests.py temp/google_appengine/ out/app_engine
testModule (analytics_test.AnalyticsModuleTest) ... ok
testEventAll (analytics_test.AnalyticsTest) ... ok
testEventAsString (analytics_test.AnalyticsTest) ... ok
testEventRoom (analytics_test.AnalyticsTest) ... ok
testOnlyEvent (analytics_test.AnalyticsTest) ... ok
testUnknowEventNumber (analytics_test.AnalyticsTest) ... ok
testBigquerySchemaClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
testEnumClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
testBuildColliderNoHostsUp (probers_test.ProbersTest) ... ok
testBuildColliderStatus (probers_test.ProbersTest) ... ok
testBuildColliderStatusEmpty (probers_test.ProbersTest) ... ok
testHandleColliderResponse (probers_test.ProbersTest) ... ERROR
testGetStatus (compute_page_test.ComputePageHandlerTest) ... ok
testPostRestartWhenNotRunning (compute_page_test.ComputePageHandlerTest)
Test restart action in a non-running state. ... ok
testPostRestartWhenRunning (compute_page_test.ComputePageHandlerTest)
Test restart action in a running state. ... ok
testPostStartNotRunningOrTerminated (compute_page_test.ComputePageHandlerTest)
Test start action in an intermediate state. ... ok
testPostStartWhenRunning (compute_page_test.ComputePageHandlerTest)
Test start action when instance in the RUNNING state. ... ok
testPostStartWhenTerminated (compute_page_test.ComputePageHandlerTest)
Test start action with instance in the TERMINATED state. ... ok
testCallerMessagesForwardedToCallee (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testConnectingWithRoomIdServesIndex (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testConnectingWithoutRoomIdServesIndex (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testGetWssHostParameters (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: "abc"
WARNING:root:Invalid or no value returned from memcache, using fallback: ["abc", "def"]
ERROR
testJoinAndLeave (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testGenerateRandomGeneratesStringOfRightLength (apprtc_test.AppRtcUnitTest) ... ok
testAnalyticsPage (analytics_page_test.AnalyticsPageHandlerTest) ... ok
testAnalyticsPageFail (analytics_page_test.AnalyticsPageHandlerTest) ... ok

======================================================================
ERROR: testHandleColliderResponse (probers_test.ProbersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suhas/apprtc/out/app_engine/probers_test.py", line 112, in testHandleColliderResponse
    name = instance[constants.WSS_INSTANCE_NAME_KEY]
AttributeError: 'module' object has no attribute 'WSS_INSTANCE_NAME_KEY'

======================================================================
ERROR: testGetWssHostParameters (apprtc_test.AppRtcPageHandlerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suhas/apprtc/out/app_engine/apprtc_test.py", line 177, in testGetWssHostParameters
    self.setWssHostStatus(0, False, 1, False)
  File "/home/suhas/apprtc/out/app_engine/apprtc_test.py", line 151, in setWssHostStatus
    constants.WSS_HOST_IS_UP_KEY: status2
IndexError: list index out of range

----------------------------------------------------------------------
Ran 26 tests in 0.033s

FAILED (errors=2)
Warning: Command failed: python build/run_python_tests.py temp/google_appengine/ out/app_engine
testModule (analytics_test.AnalyticsModuleTest) ... ok
testEventAll (analytics_test.AnalyticsTest) ... ok
testEventAsString (analytics_test.AnalyticsTest) ... ok
testEventRoom (analytics_test.AnalyticsTest) ... ok
testOnlyEvent (analytics_test.AnalyticsTest) ... ok
testUnknowEventNumber (analytics_test.AnalyticsTest) ... ok
testBigquerySchemaClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
testEnumClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
testBuildColliderNoHostsUp (probers_test.ProbersTest) ... ok
testBuildColliderStatus (probers_test.ProbersTest) ... ok
testBuildColliderStatusEmpty (probers_test.ProbersTest) ... ok
testHandleColliderResponse (probers_test.ProbersTest) ... ERROR
testGetStatus (compute_page_test.ComputePageHandlerTest) ... ok
testPostRestartWhenNotRunning (compute_page_test.ComputePageHandlerTest)
Test restart action in a non-running state. ... ok
testPostRestartWhenRunning (compute_page_test.ComputePageHandlerTest)
Test restart action in a running state. ... ok
testPostStartNotRunningOrTerminated (compute_page_test.ComputePageHandlerTest)
Test start action in an intermediate state. ... ok
testPostStartWhenRunning (compute_page_test.ComputePageHandlerTest)
Test start action when instance in the RUNNING state. ... ok
testPostStartWhenTerminated (compute_page_test.ComputePageHandlerTest)
Test start action with instance in the TERMINATED state. ... ok
testCallerMessagesForwardedToCallee (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testConnectingWithRoomIdServesIndex (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testConnectingWithoutRoomIdServesIndex (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testGetWssHostParameters (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: "abc"
WARNING:root:Invalid or no value returned from memcache, using fallback: ["abc", "def"]
ERROR
testJoinAndLeave (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testGenerateRandomGeneratesStringOfRightLength (apprtc_test.AppRtcUnitTest) ... ok
testAnalyticsPage (analytics_page_test.AnalyticsPageHandlerTest) ... ok
testAnalyticsPageFail (analytics_page_test.AnalyticsPageHandlerTest) ... ok

======================================================================
ERROR: testHandleColliderResponse (probers_test.ProbersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suhas/apprtc/out/app_engine/probers_test.py", line 112, in testHandleColliderResponse
    name = instance[constants.WSS_INSTANCE_NAME_KEY]
AttributeError: 'module' object has no attribute 'WSS_INSTANCE_NAME_KEY'

======================================================================
ERROR: testGetWssHostParameters (apprtc_test.AppRtcPageHandlerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suhas/apprtc/out/app_engine/apprtc_test.py", line 177, in testGetWssHostParameters
    self.setWssHostStatus(0, False, 1, False)
  File "/home/suhas/apprtc/out/app_engine/apprtc_test.py", line 151, in setWssHostStatus
    constants.WSS_HOST_IS_UP_KEY: status2
IndexError: list index out of range

----------------------------------------------------------------------
Ran 26 tests in 0.033s

FAILED (errors=2)
 Use --force to continue.

Aborted due to warnings.
`

A little help is really appreciable thank you :)

**Comment by phuminsingla** [comment]
+1

**Comment by KaptenJansson** [comment]
Please follow step 4 in https://github.com/webrtc/apprtc#deployment after you have done the previous steps successfully (if you see an error related to npm, grunt or something like that, fix it before continuing). 

Also when you want to add log output to Github, please either make sure it escapes the markdown parser or use pastebin instead. It's very hard to read.

**Comment by phoenixvk** [comment]
@KaptenJansson thank you for your precious response. 
I've settled up the collider. Will you please tell me How to setup COTURN,STUN server and how to start it? and how to setup credentials for STUN server? 

here as per documentation the credentials are 
`TURN_SERVER_OVERRIDE = [
  {
    "urls": [
      "turn:hostnameForYourTurnServer:19305?transport=udp",
      "turn:hostnameForYourTurnServer:19305?transport=tcp"
    ],
    "username": "TurnServerUsername",
    "credential": "TurnServerCredentials"
  },
  {
    "urls": [
      "stun:hostnameForYourStunServer:19302"
    ]
  }
]`
thanks in advance.

**Comment by KaptenJansson** [comment]
How to start turn depends on the turn server you use, it's not part of this project as pointed out in step 3 https://github.com/webrtc/apprtc#deployment.

When you have installed and configured your turn server, add it's credentials and IP address/hostname+port to the TURN_SERVER_OVERRIDE section.
