### ISSUE TITLE
Warning: Error: Unable to access jarfile undefined

### ISSUE THREAD

**Issue by appunnicer13** [webrtc/apprtc#416]
Running "csslint:strict" (csslint) task
>> 1 file lint free.

Running "csslint:lax" (csslint) task
>> 1 file lint free.

Running "htmlhint:html1" (htmlhint) task
>> 2 files lint free.

Running "eslint:target" (eslint) task

Running "shell:pipInstall" (shell) task
Requirement already satisfied (use --upgrade to upgrade): urllib3[secure]==1.19.1 in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
  Installing extra requirements: 'secure'
Requirement already satisfied (use --upgrade to upgrade): requests==2.12.4 in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): webtest==2.0.24 in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=0.14 in /root/.local/lib/python2.7/site-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.3.4 in /root/.local/lib/python2.7/site-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0.0 in /root/.local/lib/python2.7/site-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): certifi in /root/.local/lib/python2.7/site-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /root/.local/lib/python2.7/site-packages (from urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): six in /root/.local/lib/python2.7/site-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): WebOb>=1.2 in /root/.local/lib/python2.7/site-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): waitress>=0.8.5 in /root/.local/lib/python2.7/site-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /root/.local/lib/python2.7/site-packages (from webtest==2.0.24->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in /root/.local/lib/python2.7/site-packages (from cryptography>=1.3.4->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib/python2.7/dist-packages (from cryptography>=1.3.4->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): enum34 in /root/.local/lib/python2.7/site-packages (from cryptography>=1.3.4->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /root/.local/lib/python2.7/site-packages (from cryptography>=1.3.4->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pycparser in /root/.local/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.3.4->urllib3[secure]==1.19.1->-r requirements.txt (line 1))
Cleaning up...

Running "shell:ensureGcloudSDKIsInstalled" (shell) task

All components are up to date.

All components are up to date.
Already has google-cloud-sdk, skipping the download

Running "shell:buildAppEnginePackageWithTests" (shell) task
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
File found socket.io.js

Running "shell:runPythonTests" (shell) task
/root/.local/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module six was already imported from /home/chat/work/src/github.com/webrtc/apprtc/temp/google-cloud-sdk/platform/google_appengine/lib/six/six/__init__.pyc, but /root/.local/lib/python2.7/site-packages is being added to sys.path
  import pkg_resources
testBigquerySchemaClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
testEnumClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
testAnalyticsPage (analytics_page_test.AnalyticsPageHandlerTest) ... ok
testAnalyticsPageFail (analytics_page_test.AnalyticsPageHandlerTest) ... ok
testCallerMessagesForwardedToCallee (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testConnectingWithRoomIdServesIndex (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testConnectingWithoutRoomIdServesIndex (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testGetWssHostParameters (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: "abc"
WARNING:root:Invalid or no value returned from memcache, using fallback: ["abc", "def"]
WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testJoinAndLeave (apprtc_test.AppRtcPageHandlerTest) ... WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
WARNING:root:Invalid or no value returned from memcache, using fallback: null
ok
testGenerateRandomGeneratesStringOfRightLength (apprtc_test.AppRtcUnitTest) ... ok
testBuildColliderNoHostsUp (probers_test.ProbersTest) ... ok
testBuildColliderStatus (probers_test.ProbersTest) ... ok
testBuildColliderStatusEmpty (probers_test.ProbersTest) ... ok
testHandleColliderResponse (probers_test.ProbersTest) ... WARNING:root:Collider prober error: FakeError for apprtc-ws.webrtc.org:443
WARNING:root:Collider prober error: FakeError for apprtc-ws.webrtc.org:443
ok
testModule (analytics_test.AnalyticsModuleTest) ... ok
testEventAll (analytics_test.AnalyticsTest) ... ok
testEventAsString (analytics_test.AnalyticsTest) ... ok
testEventRoom (analytics_test.AnalyticsTest) ... ok
testOnlyEvent (analytics_test.AnalyticsTest) ... ok
testUnknowEventNumber (analytics_test.AnalyticsTest) ... ok
testGetStatus (compute_page_test.ComputePageHandlerTest) ... ok
testPostRestartWhenNotRunning (compute_page_test.ComputePageHandlerTest)
Test restart action in a non-running state. ... ok
testPostRestartWhenRunning (compute_page_test.ComputePageHandlerTest)
Test restart action in a running state. ... ok
testPostStartNotRunningOrTerminated (compute_page_test.ComputePageHandlerTest)
Test start action in an intermediate state. ... ok
testPostStartWhenRunning (compute_page_test.ComputePageHandlerTest)
Test start action when instance in the RUNNING state. ... ok
testPostStartWhenTerminated (compute_page_test.ComputePageHandlerTest)
Test start action with instance in the TERMINATED state. ... ok

----------------------------------------------------------------------
Ran 26 tests in 0.100s

OK

Running "shell:removePythonTestsFromOutAppEngineDir" (shell) task
Removing out/app_engine/analytics_enums_test.py.
Removing out/app_engine/analytics_page_test.py.
Removing out/app_engine/apprtc_test.py.
Removing out/app_engine/probers_test.py.
Removing out/app_engine/analytics_test.py.
Removing out/app_engine/compute_page_test.py.
Removing out/app_engine/test_util.py.

Running "shell:buildAppEnginePackage" (shell) task
Downloading and copying callstats dependencies...
Downloading https://cdnjs.cloudflare.com/ajax/libs/jsSHA/1.5.0/sha.js to out/app_engine/third_party/callstats/...
Downloading https://api.callstats.io/static/callstats.min.js to out/app_engine/third_party/callstats/...
Copying socket.io.js
File found socket.io.js

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: Error: Unable to access jarfile undefined
 Use --force to continue.

Aborted due to warnings.

Can you help me with this ? I can't figure out why

**Comment by MirkoBonadei** [comment]
Hi, can you please give more details about `node` and `npm` versions and also the list of `npm` packages installed (run `npm list`).

Thanks

**Comment by appunnicer13** [comment]
solved by #285 . It was a grunt version issue . Thank you.
