### ISSUE TITLE
Bind collider with a single IP address

### ISSUE THREAD

**Issue by vremenno** [webrtc/apprtc#417]
is it possible to bind a collider service with a single IP address? If not, can we add such option?, for example:
 /bin/collidermain **-ip=10.10.0.5** -port=443 -tls=true

In this case other services can be ran on the same server, same port, but different IP's

**Comment by KaptenJansson** [comment]
Pull requests are welcome ;) FYI You can listen on a different port and use port forwarding/mapping to map to a different external port.

**Comment by vremenno** [comment]
With pleasure when my skills in Golang get to that level. I'll explore port forwarding/mapping options, thanks.

**Comment by KaptenJansson** [comment]
Closing due to age.
