### ISSUE TITLE
Loudspeaker stays silent on Android API 16 device

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [webrtc/apprtc#421]
When establishing a video call with a Samsung SIII mini (GT-I8190; running on Android 4.1.2 or API 16), the Samsung device's loudspeaker stays silent.

Its microphone works fine, i.e. the other party can hear the Samsung device. Also, the video functionality works flawlessly.

I've read [here](https://cs.chromium.org/chromium/src/third_party/webrtc/sdk/android/AndroidManifest.xml?sq=package:chromium) that API 16 should be supported. May I ask whether that's true? If so, is this a known issue?

I hope this is the right place to ask this question. I could provide logs if wanted.

(Background: I tested the AppRTCMobile.apk in order to look for the source of the identical problematic behavior which I encountered in a different, WebRTC-based app.)

**Comment by KaptenJansson** [comment]
This repo is for the web version of AppRTC and it's backend. AppRTCMobile is part of the WebRTC repo. You can use https://bugs.webrtc.org for filing bugs.

Technical questions pertaining to WebRTC belong in https://groups.google.com/forum/#!forum/discuss-webrtc.

To answer your question: the min version is 16 hence it should work but we do not spend much time testing on a 4 year old OS version.
