### ISSUE TITLE
 AppRTC Audio and Video sending/receiving codecs are not displayed in stats window

### ISSUE THREAD

**Issue by cvranjani** [webrtc/apprtc#422]
Chrome Version:  57.0.2987.54  / 9202.28.0 beta
Chrome OS

What steps will reproduce the problem?
1. Browse to https://appr.tc/?debug=loopback
2. Listen for audio disruptions and watch for video stutter
3. Press "i" to open up the stats data, while in the call 
(alternatively, expand the ssrc_<>_send, ssrc_<>_recv in chrome://webrtc-internals)

Expected result:
a) Audio and video quality should be good
b) In the apprtc call stats window, Audio Rx,Audio Tx, Video Rx, Video Tx should display audio receiving, sending codecs and Video receiving and sending codecs respectively (also displayed in ssrc_<>_send, recv(audio) and ssrc_<>_send,recv(video) in chrome://webrtc-internals)

Actual result:
a) Audio and video quality is good
b) Apprtc call stats window does not display audio receiving, sending codecs and Video receiving and sending codecs (but displayed in ssrc_<>_send, recv(audio) and ssrc_<>_send,recv(video) in chrome://webrtc-internals)

Notes:
1.This issue is also observed with apprtc peer2peer back calls
2. Feedback submitted for this issue:id: 53391793542
[loopback_webrtc_internals_dump.txt](https://github.com/webrtc/apprtc/files/778839/loopback_webrtc_internals_dump.txt)
[Loopback_js_logs.txt](https://github.com/webrtc/apprtc/files/778841/Loopback_js_logs.txt)

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by KaptenJansson** [comment]
argh this is a result of me updating to adapter 3.0, will fix. Thanks for reporting!

**Comment by cvranjani** [comment]
@KaptenJansson : I still see this issue in Chrome OS with M58 58.0.3029.40 / 9334.24.0 beta. Can you please confirm if the fix got merged ?

**Comment by cvranjani** [comment]
Sorry..updated wrong issue. Please ignore the recent comment.

**Comment by cvranjani** [comment]
Updated the correct bug. Sorry for the confusion.

@KaptenJansson : I still see this issue in Chrome OS with M58 58.0.3029.40 / 9334.24.0 beta. Can you please confirm if the fix got merged ?

**Comment by KaptenJansson** [comment]
This has not been fixed yet.
