### ISSUE TITLE
Deployment Instructions(EC2)

### ISSUE THREAD

**Issue by iakashpaul** [webrtc/apprtc#424]
**Browsers and versions affected**
All I guess

**Description**
1. The deployment instructions don't articulate what path(GOROOT+GOPATH) values are to be set in this context, they just point to the general Go instructions. Could this be a little more hands-on with a sample set of instructions right after the git clone step.

2. Although I've installed Go on the EC2 instance & setup GOPATH to $HOME too, after running 'go get collidermain,' I get-
> package collidermain: unrecognized import path "collidermain" (import path does not begin with hostname)

**Steps to reproduce**
Run the Deployment method of AppRTC with Collider on a free-tier EC2/Ubuntu16.04 instance

**Expected results**
Should run the apprtc demo on localhost:8080

**Actual results**
Stuck at collider installation

**Comment by MirkoBonadei** [comment]
@KaptenJansson I can take this. It is not high priority but we talked about this kind of issue a lot in past two months.

**Comment by KaptenJansson** [comment]
Keep in mind ApPRTC is designed to run on App engine, not on a VM using the dev_appserver tool which is for local testing and development (hence the name dev_).

**Comment by KaptenJansson** [comment]
I followed the general Go and the [collider](https://github.com/webrtc/apprtc/tree/master/src/collider) instructions and they worked for me.You can set any GOPATH and GOROOT as long as you export them properly but just setting it to the same as described in the collider instructions should work.

Could you specify the Go version you are using and the exact steps you have done?

**Comment by KaptenJansson** [comment]
Ping

**Comment by iakashpaul** [comment]
Sorry, I almost forgot about this. I followed the steps from the go pages. 
Were you able to run this outside of the App engine/gcloud?

**Comment by rootmonty** [comment]
Hi,I am trying to follow the instructions given in the deployment section under Collider Build but I am stuck at the point where I need to import the collidermain package,as I am getting this error
package collidermain: unrecognized import path "collidermain" (import path does not begin with hostname)

Can you help me get along with the deployment procedure.

My $GOPATH = $HOME/goWorkspace 
then i mkdir $GOPATH/src
and then go get collidermain but got this error
Pl help

**Comment by KaptenJansson** [comment]
You must have missed a step, please redo the steps and list them here exactly as you perform them.

**Comment by rootmonty** [comment]
Thanks KaptenJansson. this time it worked!
