### ISSUE TITLE
when i open apprtc index webpage cannot see any button and edittext

### ISSUE THREAD

**Issue by chengzong** [webrtc/apprtc#426]
chrome source code show error as below:
 
Uncaught SyntaxError: Unexpected identifier
(index):168 Uncaught ReferenceError: AppController is not defined
    at initialize ((index):168)
    at (index):179

as its said javascript cannot find  new AppController(loadingParams) method ,how can i do

**Comment by KaptenJansson** [comment]
Hi,
Could you please elaborate a little on what you are doing?

**Comment by chengzong** [comment]
I just deployment apprtc server on ubuntu 32bit by myself,my steps as follow：
1.install Node.js, install Grunt, add app engine sdk to path evironment
2.start server by cmd:dev_appserver.py --host=myip ./out/app_engine
3.Then navigate to http://myip:8080 in my browser
in my brower i cannot find anything, but gray bg.it is javascript error i think

**Comment by KaptenJansson** [comment]
You do not need to specify --host=myip unless you want to access it from a different machine (in that case you need to do --host=0.0.0.0 in order for it to be exposed externally since it defaults to localhost).

**Comment by w3tra** [comment]
same problem, trying to proxy via nginx to localhost and get same js error

**Comment by SGCreations** [comment]
I am facing the same issue! Please help...

**Comment by SharvariGC** [comment]
Hi I am facing the issue. Why was this closed with no comments whatso ever?

**Comment by EliosSs** [comment]
Hi! I am facing the same issue too, some of you achieved any solution?
Please, and thanks in advance
