### ISSUE TITLE
can you add a apprtc docker

### ISSUE THREAD

**Issue by izouxv** [webrtc/apprtc#427]
**Browsers and versions affected**

**Description**

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by izouxv** [comment]
rt

**Comment by izouxv** [comment]
for test

**Comment by KaptenJansson** [comment]
That's definitely worth investigating. Cannot give you an ETA.

**Comment by vesper8** [comment]
I also want this because the manual installations seem a bit complicated.

But there are already 3 apprtc docker images, this one being the latest one updated 9 months ago

https://hub.docker.com/r/benjamin94/apprtc-docker/

@izouxv have you tried this? is it not working?

**Comment by KaptenJansson** [comment]
Keep in mind AppRTC is meant to run on cloud hosted App Engine, not using dev_appserver.py on a VM (the hint is in the name that its not for production).

**Comment by KaptenJansson** [comment]
Someone else did this in #457
