### ISSUE TITLE
chrome brower:Failed to get access to local media

### ISSUE THREAD

**Issue by chengzong** [webrtc/apprtc#428]
@KaptenJansson 
Failed to get access to local media.Error name was NotSupportedError.Continuing without sending a stream.

Messages:  
Error getting user media: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
getUserMedia error: Failed to get access to local media. Error name was NotSupportedError. Continuing without sending a stream.
WebSocket open error: WebSocket error.
WebSocket register error: WebSocket error.

Version:    
branch:     master
time:       Mon Mar 6 07:49:29 2017 +0100
gitHash:    3aaa27dbb025f53e00e19172b7d3704ce719271e

**Comment by phamvanlam** [comment]
Using firefox instead. you can get access to local media from chrome with https or localhost

**Comment by KaptenJansson** [comment]
@phamvanlam is correct.

**Comment by diegobill** [comment]
How to solve this problem to chrome?

**Comment by adnanhemani** [comment]
@diegobill found a workaround: if you look at the example on https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes#TOC-To-continue-to-use-permissions-from-iframes-on-your-website...

Put 'allow="microphone; camera"' in the tag where you are loading this. Works fine for me now!
