### ISSUE TITLE
Using apprtc locally

### ISSUE THREAD

**Issue by curiouser001** [webrtc/apprtc#429]
I want to use the AppRTC without the internet connection from the local network.
AppRTC works locally when there is internet connection.
Even when I disconnected the internet connection while apprtc was running, the connection between the two devices continues. But when I get out of the room and re-enter a new room, I get the following errors:

![image](https://cloud.githubusercontent.com/assets/26377400/23848126/632951d0-07de-11e7-8823-33973646f124.png)

**Comment by KaptenJansson** [comment]
Hi,

In order for apprtc to work locally you need to setup your own signalling server (and STUN/TURN server if you want to be able to leave the network). Check out the [Deployment](https://github.com/webrtc/apprtc#deployment) instructions.
