### ISSUE TITLE
installing Collider

### ISSUE THREAD

**Issue by rootmonty** [webrtc/apprtc#430]
**Browsers and versions affected**

**Description**
  I am seeking some help in the installation of collider for deployment of apprtc server locally.I have seen the instructions and have followed till deployment.I dont understand the auto restart section of collider and how to install the start.sh script.Can you tell me the perspective for this and the necessity

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by KaptenJansson** [comment]
This is due to if the collider instance would crash, that script would restart it automatically. You can do it other ways if you want, this is what we have done on Debian but it might vary depending on Linux dist.
