### ISSUE TITLE
runtime process for instance running on port 41446 has unexpectedly quit

### ISSUE THREAD

**Issue by bandish2189** [webrtc/apprtc#431]
**runtime process for instance running on port 41446 has unexpectedly quit**

I've apprtc setup on linux server. Running and performing well. but some time this error occurs and stops working apprtc and displaying logs instead of running.
![moodchimp](https://cloud.githubusercontent.com/assets/24892802/24746872/313fb378-1ad8-11e7-9cf4-401e78d12084.png)

**Comment by KaptenJansson** [comment]
dev_appserver is for development, it's not a production server and will not be supported as such.

**Comment by bandish2189** [comment]
@KaptenJansson 
How can i solve this issue? 
is there any version that can be used for production?

**Comment by bandish2189** [comment]
Is that solve this issue. 
mean it will not crash after setup in google cloud. right?

**Comment by KaptenJansson** [comment]
Yes, follow the Google app engine instructions.

**Comment by bandish2189** [comment]
do i need whole setup on google cloud?
as i am new with this all please give me instructions for setup it.

**Comment by KaptenJansson** [comment]
Please read the deployment instructions in the README.MD file. General Google App Engine instructions can be found at https://cloud.google.com/appengine/.

There is no shortcut, read all the the documentation.
