### ISSUE TITLE
side-by-side option no longer available?

### ISSUE THREAD

**Issue by vesper8** [webrtc/apprtc#433]
I think in a previous version there was a url parameter ?ssr=true that made the two videos (local and remote) appear side-by-side instead of the local video being in a mini window in the corner.

This option seems to no longer be available.. or is it hidden?

I would really like to have the two images side-by-side so that I can then record the video and put it up on youtube.

right now I'm looking at using Tampermonkey or other chrome extensions that allow you to save in-debugger css modifications but if there's an easier way I'd love to know about it.

Thanks!

**Comment by KaptenJansson** [comment]
I have never seen that option before, must have been several years ago if it ever existed.

**Comment by vesper8** [comment]
yes I found it here https://github.com/webrtc/samples/wiki/AppRTC-URL-parameter-guide

I think it didn't even do what I wanted in any case.

I created this little tampermonkey script to achieve side-by-side video with the latest version of the apprtc demo.. in case it comes in handy for anyone else.

```
// ==UserScript==
// @name         Apprtc
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://appr.tc/r/725888386
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    
    function addGlobalStyle(css) {
        var head, style;
        head = document.getElementsByTagName('head')[0];
        if (!head) { return; }
        style = document.createElement('style');
        style.type = 'text/css';
        style.innerHTML = css;
        head.appendChild(style);
    }
    
    addGlobalStyle('#remote-video { height:50% !important; width:50% !important; max-height:50% !important; max-width:50% !important; right:0px !important; }');
    addGlobalStyle('#mini-video { height:50% !important; width:50% !important; max-height:50% !important; max-width:50% !important; bottom: inherit !important; left: inherit !important; border: none !important; object-fit: cover !important; }');
})();
```

Then with Quicktimes and Soundflower I'm able to record a video chat with sound. Maybe I'm making things harder than they need to be but anyway it works well enough

**Comment by KaptenJansson** [comment]
I see, feel free to create a PR and we can review and consider it there.
