### ISSUE TITLE
Dropped frames on iOS client while receive h264 from Chrome

### ISSUE THREAD

**Issue by vpoddubchak** [webrtc/apprtc#436]
**Browsers and versions affected**
Chrome 57.
WebRTC in iOS is the latest.

**Description**
When I connect iOS client to the room with Chrome client in it, sometimes I see errors:
(h264_video_toolbox_decoder.cc:62): Failed to decode frame. Status: -12909
on the iOS side. In this time receiving video from Chrome is freezing.
Looks like iOS HW h.264 decoder sometimes can't decode samples from Chrome.

If use Firefox instead of Chrome it works fine.

**Steps to reproduce**
- Create room by Chrome
- Connect to room by iOS client

**Expected results**
- Smoothly video

**Actual results**
- Freezing on iOS client

**Comment by KaptenJansson** [comment]
This should be filed in https://bugs.webrtc.org
