### ISSUE TITLE
How to configure HTTPS access

### ISSUE THREAD

**Issue by hnyashiro** [webrtc/apprtc#439]
I follow  the internet's methods configured to http: // url: 8080 use nginx reverse proxy into http: // url, can see the video, but suggested websocket wrong, I do not know how to configure the back, there is no online Related tutorial, help please ! thanks for all

`Messages:  
WebSocket open error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
WebSocket register error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

Version:    
time:       Mon Mar 6 07:49:29 2017 +0100
gitHash:    3aaa27dbb025f53e00e19172b7d3704ce719271e
branch:     master`

**Comment by VinceOPS** [comment]
You need to set up collider to use your SSL certificate, in order to use the secure websocket protocol (wss://).
You'll find details about the certificate in the collider README.

**Comment by KaptenJansson** [comment]
You cannot mix HTTP/WS and HTTPS/WSS.
