### ISSUE TITLE
Apprtc loopback calls failing to connect (500 server error)

### ISSUE THREAD

**Issue by cvranjani** [webrtc/apprtc#441]
Browsers and versions affected : 59.0.3071.33 / 9460.20.0 dev
OS: Chrome OS, Linux

**Description**
Apprtc loopback calls failing to connect (500 server error)

**Steps to reproduce**
1. Start an apprtc loopback call using https://appr.tc/?debug=loopback
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors

**Expected results**
- Apprtc loopback call should connect
- Audio and video should be clear

**Actual results**
- Apprtc loopback call does not connect
- Apprtc call window shows : "Waiting for someone to join this room: https://appr.tc/r/roomname?debug=loopback"
- JS logs shows error : 
"apprtc.debug.js:2699 POST https://appr.tc/message/618666855/97785958?debug=loopback 500 ()
Call.sendSignalingMessage_ @ apprtc.debug.js:2699
PeerConnectionClient.setLocalSdpAndNotify_ @ apprtc.debug.js:3092"

Note:
1. Feedback report  id: 59210960610
2. JS logs attached
[Apprtc_loopback_Call_js_logs.txt](https://github.com/webrtc/apprtc/files/971698/Apprtc_loopback_Call_js_logs.txt)

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by iBicha** [comment]
I don't think this is related to loopback
![console](https://d2ppvlu71ri8gs.cloudfront.net/items/321P411K3f1R2a2t1F0O/Image%202017-05-02%20at%201.23.47%20PM.png)

**Comment by iBicha** [comment]
#440

**Comment by Saradomin** [comment]
i can safely say that installing the collider server will solve the issue. Its not for the faint of hearts though if you had a previus version of "go " (be sure to purge any previus versions , and check the GOPATH to be corect ) . Also i would like to point out it needs to be on a secure port. So , you either install collider on another machine or use apache to proxy the ports to 443 with an alias .

**Comment by KaptenJansson** [comment]
This is fixed, was due to a global firewall change that blocked all traffic to Collider.
