### ISSUE TITLE
Sorry,this room is full

### ISSUE THREAD

**Issue by Shysoong** [webrtc/apprtc#444]
**Browsers and versions affected**
58.0.3029.96 (64bit)

**Description**
when 3 client entered one room,we got a "sorry,this room is full" message

question1:
as metioned in https://github.com/webrtc/apprtc/issues/397 ,how can i reduce the timeout as KaptenJansson said.

question2:
according to the code in "https://github.com/webrtc/apprtc/blob/master/src/app_engine/apprtc.py",as hard coded,if i want more than 2 client to join one room,the only way i can do is changing the number in the code ?

**Comment by KaptenJansson** [comment]
The whole app is built on premise of two users, you would need to fork AppRTC and most likely rewrite quite a lot to accommodate for more users.

**Comment by c526537207** [comment]
Hello, I am also studying this, how to implement the third user to join, which code to modify, please help?
