### ISSUE TITLE
appRTC on AWS

### ISSUE THREAD

**Issue by anilmaddala** [webrtc/apprtc#446]
I am following [instruction](https://github.com/webrtc/apprtc) and am able to build, run apprtc on my local ubuntu machine.

I am trying to implement the same on AWS. I have added ports 8000 and 8080 to the instance security group. On AWS when I execute `<path to sdk>/dev_appserver.py ./out/app_engine` I get console message 

> Starting API server at: http://localhost:45920
Starting module "default" running at: http://localhost:8080
Starting admin server at: http://localhost:8000

I check ec2...compute-1.amazonaws.com:8000,  ec2...compute-1.amazonaws.com:8080 and see nothing. Could you please point to what I am missing?

**Comment by KaptenJansson** [comment]
Its by default bound to localhost, you need to specify` --host 0.0.0.0` in order to expose it outside of the machine.
