### ISSUE TITLE
ImportError: No module named apiclient

### ISSUE THREAD

**Issue by Immortalpk** [webrtc/apprtc#451]
Hello,

I am configuring the apprtc using google app engine and followed the below steps and got stuck as I am getting **ImportError: No module named apiclient** . (I am using Mac system)

1. Download the code.
2. Install latest node.js.
<img width="338" alt="screen shot 2017-06-07 at 2 34 29 pm" src="https://user-images.githubusercontent.com/6000982/26870706-7bf6beb6-4b8e-11e7-95a1-0225511fcc23.png">

3. Installed latest python.
<img width="358" alt="screen shot 2017-06-07 at 2 34 42 pm" src="https://user-images.githubusercontent.com/6000982/26870713-804d6708-4b8e-11e7-878a-a1348737bfe6.png">

4. install pip (to upgrade the google-api-python-client).
5. download the google app engine.
6. Configured it on my local system (mac).
7. Now I tried to run the apprtc using google app engine and open http://localhost:8080/ than I got below error (attached screen shot)

<img width="1016" alt="screen shot 2017-06-07 at 2 31 16 pm" src="https://user-images.githubusercontent.com/6000982/26870659-50623d48-4b8e-11e7-951c-8750926d4e2c.png">

As I can see I have third_party folder which contain apiclient with all files.
<img width="814" alt="screen shot 2017-06-07 at 2 36 58 pm" src="https://user-images.githubusercontent.com/6000982/26870809-cec3f226-4b8e-11e7-8df0-128cb3809709.png">

I am new to it. Please let me know where I am wrong which things I missed while configuring.

**Comment by KaptenJansson** [comment]
Hi,

You need to build AppRTC first, please follow the https://github.com/webrtc/apprtc#development instructions.
