### ISSUE TITLE
No detailed stats (codec, bitrate, etc) in info panel in M61

### ISSUE THREAD

**Issue by juberti** [webrtc/apprtc#452]
Start and connect a call in AppRTC (using Chrome Version 61.0.3124.0 (Official Build) canary (64-bit))

Bring up the info panel. 

Observe just this (note no detailed stats on codecs, bitrates, etc, which used to be present)

States:     
Signaling:  stable
Gathering:  complete
Connection: completed
Local:      host:2 srflx:1 relay:4
Remote:     host:2 srflx:1 relay:4

Stats:      
Call time:  08:17
Setup time: 1008 ms

Version:    
gitHash:    8aa99b92a1fb8eefa9a21051a660a53e36013769
branch:     master
time:       Wed May 3 16:23:48 2017 +0200

**Comment by KaptenJansson** [comment]
We need to update the stats parsing for the infobox.
