### ISSUE TITLE
How to use TURN_SERVER_OVERRIDE config in AppRTC-Android client?

### ISSUE THREAD

**Issue by Piasy** [webrtc/apprtc#456]
**Browsers and versions affected**
AppRTC-Android,  https://chromium.googlesource.com/external/webrtc/+/832e67a2c35f20de648bc4b532ef15092ae912f0

**Description**
The [AppRTC-Android client](https://chromium.googlesource.com/external/webrtc/+/832e67a2c35f20de648bc4b532ef15092ae912f0/webrtc/examples/androidapp/src/org/appspot/apprtc/RoomParametersFetcher.java#132) would expects `pc_config.iceServers` field from response for TURN and STUN server urls, but [apprtc server](https://github.com/webrtc/apprtc/blob/master/src/app_engine/apprtc.py#L47) will always return empty `pc_config.iceServers`, should I modify AppRTC-Android code or apprtc server code? Thanks!

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by KaptenJansson** [comment]
So if you uncomment https://github.com/webrtc/apprtc/blob/master/src/app_engine/constants.py#L26 and populate it with your own turn server, pc_config.iceServers is empty?

**Comment by Piasy** [comment]
Thanks for your response! I tried that, and then `turn_server_override` becomes not empty, but `pc_config.iceServers` still empty.

**Comment by Piasy** [comment]
I think, if we don't modify code of [AppRTC-Android client](https://chromium.googlesource.com/external/webrtc/+/832e67a2c35f20de648bc4b532ef15092ae912f0/webrtc/examples/androidapp/src/org/appspot/apprtc/RoomParametersFetcher.java#132), then we should not return `turn_server_override` field in room params, we should read `TURN_SERVER_OVERRIDE` value then put it into `pc_config.iceServers`, like below:

``` python
TURN_SERVER_OVERRIDE = [
  {
    "urls": "turn:192.168.11.85",
    "username": "ninefingers",
    "credential": "youhavetoberealistic"
  },
  {
    "urls": "stun:stun.l.google.com:19302"
  }
]
```

==>

``` python
  config = {
  'iceServers': [{"urls":"stun:stun.l.google.com:19302"},{"urls":"turn:ninefingers@192.168.11.85","credential":"youhavetoberealistic"}],
  'bundlePolicy': 'max-bundle',
  'rtcpMuxPolicy': 'require'
  }
```

I've tested, it works!

**Comment by Piasy** [comment]
And the ICE server's code:

``` javascript
var express = require('express')
var crypto = require('crypto')
var app = express()

var hmac = function (key, content) {
  var method = crypto.createHmac('sha1', key)
  method.setEncoding('base64')
  method.write(content)
  method.end()
  return method.read()
}

app.get('/iceconfig', function (req, resp) {
  var query = req.query
  var key = '4080218913'
  var time_to_live = 600
  var timestamp = Math.floor(Date.now() / 1000) + time_to_live
  var turn_username = timestamp + ':ninefingers'
  var password = hmac(key, turn_username)

  return resp.send({
    iceServers: [
      {
        urls: [
          'turn:ICE_SERVER_ADDR:3478?transport=udp',
          'turn:ICE_SERVER_ADDR:3478?transport=tcp',
          'turn:ICE_SERVER_ADDR:3479?transport=udp',
          'turn:ICE_SERVER_ADDR:3479?transport=tcp'
        ],
        username: turn_username,
        credential: password
      }
    ]
  })
})

app.listen('3033', function () {
  console.log('server started')
})
```

**Comment by Pizza67** [comment]
I solved the issue by modifying the [AppRTC Android client](https://chromium.googlesource.com/external/webrtc/+/master/examples/androidapp/src/org/appspot/apprtc/RoomParametersFetcher.java#209) where the error is to get a String instead of a JSON Array as it's done in the [requestTurnServers ](https://chromium.googlesource.com/external/webrtc/+/master/examples/androidapp/src/org/appspot/apprtc/RoomParametersFetcher.java#184)method.

In the [AppRTC server](https://github.com/webrtc/apprtc/blob/master/src/app_engine/apprtc.py#L45)  modify the code as follows:
```
# iceServers will be filled in by the TURN HTTP request.
def make_pc_config(ice_transports, ice_servers_override = None):
  config = {
  'iceServers': [],
  'bundlePolicy': 'max-bundle',
  'rtcpMuxPolicy': 'require'
  };
  #begin: patch
  #add the following block of code
  if ice_servers_override:
    config['iceServers'] = ice_servers_override
  #end: patch
  if ice_transports:
    config['iceTransports'] = ice_transports
  return config

```
And in get_room_parameters function change the following assignment:

`pc_config = make_pc_config(ice_transports)`
into:
`pc_config = make_pc_config(ice_transports, turn_server_override)`

Regards.

**Comment by KaptenJansson** [comment]
Just to clarify terminology here, TURN server override allows you to add a TURN/STUN server URL directly whilst ICE server is a URL for a web server that returns TURN/STUN server URLs and credentials.

Changing ICE servers is done in constants.py by changing the ICE_SERVER constants (if you have a web server returning TURN/STUN URLS and credentials).

Turn server override disables the ICE server fetching logic and apprtc will use the TURN/STUN servers provided in the TURN_SERVER_OVERRIDE constant in constants.py (if you only have TURN & STUN server like coturn).

I will take a look at this and see if we can get it to work on AppRTCMobile as well.

**Comment by KaptenJansson** [comment]
I've made the change as suggested in https://github.com/webrtc/apprtc/issues/456#issuecomment-351020935.
