### ISSUE TITLE
iframe-apprtc page gives JS Error appr.tc/r/454648382:1 Uncaught (in promise) DOMException: Not a top-level browsing context."

### ISSUE THREAD

**Issue by JaspalK** [webrtc/apprtc#458]
**Browsers and versions affected**
Chrome 61.0.3124.4 (Mac), Chrome 61.0.3124.10 (Windows 7, Windows 10)

**Steps to reproduce**
1. Browse to https://test.webrtc.org/manual/iframe-apprtc/index.html 
2. Open the javascript console (alt+cmd+j or ctrl+shift+j) 
3. Enter a enter a room name and press "JOIN" and watch for any JS errors

**Expected results**
- No JS Errors

**Actual results**
-  JS Error "appr.tc/r/454648382:1 Uncaught (in promise) DOMException: Not a top-level browsing context."

I can re-produce this bug every time 

![screenshot-js-error-iframe-appartc](https://user-images.githubusercontent.com/22443950/27073928-d46caf74-5025-11e7-9237-29fd6448842d.png)

**Comment by KaptenJansson** [comment]
Could be Chrome tightening the security for iframes. @guidou @samdutton do you know anything about this?

**Comment by samdutton** [comment]
I can't reproduce this in Chrome 59.0.3071.86 or 61.0.3129.0 on Mac.

I don't have a Windows box handy, but I can check if there's been a change.

**Comment by JaspalK** [comment]
After doing some quick tests, I do NOT see the bug on Mac or Linux using Chrome 61.0.3130.0 (canary)

However, on Linux , I do still see the bug using Chrome 61.0.3129.0

**Comment by fippo** [comment]
@KaptenJansson https://groups.google.com/forum/? utm_medium=email&utm_source=footer#!msg/discuss-webrtc/32natnrbP6U/0dgpWLMkAwAJ -- possibly related?
