### ISSUE TITLE
collider: crypto/tls: failed to parse private key

### ISSUE THREAD

**Issue by getcontigo** [webrtc/apprtc#463]
**Description**
Still not able to setup collider - related issue -->  https://github.com/webrtc/apprtc/issues/442

I followed the workaround given at: https://issuetracker.google.com/issues/35901176, running the following command:

On linux you can use the following command: 
wget https://curl.haxx.se/ca/cacert.pem -O {Root of Python SDK}/lib/cacerts/urlfetch_cacerts.txt 

but still see the following error in /collider/collider.log file:
"crypto/tls: failed to parse private key"

* Would you please explain how to use let's encrypt to generate the fullchain.pem?  I used my APPNAME.appspot.com when generating let's encrypt:
sudo -H ./letsencrypt-auto certonly --standalone -d APPNAME.appspot.com
But was not able to generate keys

**Comment by KaptenJansson** [comment]
Sorry have never used letsencrypt, maybe you could ask them?

**Comment by KaptenJansson** [comment]
Ping?
