### ISSUE TITLE
Support uppercase VSC parameter

### ISSUE THREAD

**Issue by wuchengli** [webrtc/apprtc#464]
**Browsers and versions affected**
All

**Description**
http://apprtc.appspot.com/?debug=loopback&vsc=VP8 will use VP8 but http://apprtc.appspot.com/?debug=loopback&VSC=VP8 will still use the default VP9 codec. It's a bit confusing. Several vendors use the wrong uppercase and spent time debugging. I myself was also confused several times. Does it make sense to support both VSC and vsc?

**Steps to reproduce**
Run http://apprtc.appspot.com/?debug=loopback&VSC=VP8

**Expected results**
Expect to use VP8.

**Actual results**
VP9 is chosen.

Wu-Cheng Li (wuchengli@google.com)

**Comment by KaptenJansson** [comment]
All url parameters are in lowercase: https://appr.tc/params.html. 

I think it's quite succinct and clear to have all parameters in one case, the value provided however is arbitrary.
