### ISSUE TITLE
Server is up but pages do not load - please help

### ISSUE THREAD

**Issue by the-interactive-company** [webrtc/apprtc#466]
**Browsers and versions affected**
chrome/ff/safari/all

**Description**

The Collider service is up and running.
The App engine is up and running.

When i load the web page i get "Invalid path: /"

on the server in my terminal window, if I use "lynx http://localhost:8080" .  I do see the https://appr.tc webpage... 

Please let me know if you need any code files here, I just don't know what or where my issue is!?

**Steps to reproduce**
I followed this guide and all the tests are OK
https://github.com/webrtc/apprtc

**Expected results**
I assumed I would see something more like this...
https://appr.tc/

**Actual results**
at the uri, i get "Invalid path: /"

**Comment by KaptenJansson** [comment]
Have you started apprtc using GAE dev appserver?

**Comment by greggor88** [comment]
@KaptenJansson no. I am using a Ubuntu 16.04 server ec2 instance. Would you recommend that I use Google App Engine?

**Comment by KaptenJansson** [comment]
You have to use Google app engine dev server in order to run it locally, when hosting it, yes you need to deploy it to Google app engine, it's a Google app engine app.
