### ISSUE TITLE
Re-connection session after getting ICE state failure error.

### ISSUE THREAD

**Issue by AmitKasundra** [webrtc/apprtc#471]
Hi,

I work with RTCMultiConnection.

Is there any standard way to reconnect to the initiator after getting ICE state failure issue.?

There are two pages in our project, After establishing the connection if he faces any issue like ICE state failure issue or any error. He or she can join automatically.

I have tried to call connection.join('') but didn't join the conference.

Can you please suggest any idea on the same?

Thank you!

**Comment by KaptenJansson** [comment]
Hmm we have not thought of that use case, when ICE state goes into failure, you need to do a new ice negotiation since it cannot be recovered.
