### ISSUE TITLE
AudioOptions does not seem to work

### ISSUE THREAD

**Issue by minyuel** [webrtc/apprtc#473]
**Browsers and versions affected**
all

**Description**
Things like
appr.tc/?audio=googDAEchoCancellation=true 
does not seem to take any effect

**Steps to reproduce**
appr.tc/?audio=googDAEchoCancellation=true
and read Chrome logs for AudioOptions

**Expected results**
Delay agnostic AEC can be turned on.

**Actual results**
Delay agnostic AEC is not turned on.

**Comment by KaptenJansson** [comment]
I guess this has to do more spec like handling in adapter and chrome. Will look into it.

**Comment by KaptenJansson** [comment]
Works for me on 60.0.3112.113
http://localhost:8080/r/370423756?audio=googDAEchoCancellation=true&debug=loopback

From webrtc-internals:
Caller origin: http://localhost:8080
Caller process id: 44461
Audio Constraints
{advanced: [{googDAEchoCancellation: {exact: true}}]}
Video Constraints
{advanced: [{width: {min: 1280}}, {height: {min: 720}}]}

**Comment by minyuel** [comment]
How did you verify DAEchoCancellation? I would suggest making an AEC dump and check the config (containing DAEchoCancellation effective or not) by unpacking the dump.

**Comment by KaptenJansson** [comment]
But as you can see, the constraint is passed to Chrome, if it does not work then, it's a Chrome bug, not AppRTC.

**Comment by KaptenJansson** [comment]
Closing this since it appears to be a Chrome or WebRTC bug.
