### ISSUE TITLE
Firefox shows *Failed to get access to local media.* with Logitech QuickCam

### ISSUE THREAD

**Issue by paulmenzel** [webrtc/apprtc#474]
**Browsers and versions affected**

1.  Firefox ESR 52.2.0
2.  Chromium 60.0.3112.78

**Description**

Using a Logitech QuickCam connected over USB creating or joining a room on https://appr.tc gives the error below despite allowing access to the microphone and camera.

> Failed to get access to local media. Error name was InternalError. Continuing without sending a stream

The browser console shows the message below.

> non-maplike pc.getStats access is deprecated! See http://w3c.github.io/webrtc-pc/#example for usage.

**Comment by KaptenJansson** [comment]
Works now.
