### ISSUE TITLE
grunt build fail

### ISSUE THREAD

**Issue by HaoRuiK** [webrtc/apprtc#476]
[root@localhost apprtc]# grunt build

/home/apprtc/node_modules/grunt-shell/tasks/shell.js:2
const exec = require('child_process').exec;
^^^^^
Loading "shell.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Loading "compress.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Warning: Task "shell:buildAppEnginePackage" not found. Use --force to continue.

Aborted due to warnings.

**Comment by KaptenJansson** [comment]
You have enabled ES6 it seems?

**Comment by KaptenJansson** [comment]
and perhaps not done npm install?

**Comment by whsgzcy** [comment]
How did you solve it?

my

Loading "html.js" tasks...ERROR
>> SyntaxError: Unexpected token {
Loading "shell.js" tasks...ERROR
>> SyntaxError: Unexpected token {
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Unexpected token {
Warning: Task "shell:buildAppEnginePackage" not found. Use --force to continue.

Aborted due to warnings.
