### ISSUE TITLE
New way of building doesn't work on Windows

### ISSUE THREAD

**Issue by phoglund** [webrtc/apprtc#48]
We need to invoke grunt build on Windows to run the AppRTC test. Unfortunately grunt build ends up calling bash scripts, which fail badly on Windows:

Running "shell:buildVersion" (shell) task
'.' is not recognized as an internal or external command,
operable program or batch file.
Warning: Command failed: '.' is not recognized as an internal or external command,
operable program or batch file.

Please rewrite as python scripts.

**Comment by KaptenJansson** [comment]
Also avoid linking in files linux/unix path (adapter.js with "../../../") etc like we had for adapter.js in testrtc when it was part of the samples repo.

**Comment by phoglund** [comment]
The new apprtc seems to have adapter.js checked in so there are no symlinks now I think.

Also, I should probably look into the python test workflows, etc on Windows; those have .sh files too. It makes sense to support development on Windows too.

**Comment by phoglund** [comment]
Ok, it could be possible to solve this on Windows, but we need to write everything as self-contained python scripts. Fortunately grunt-shell essentially runs your command verbatim in the shell you're in, and both cmd.exe and bash will accept 'python build/some_script.py'.

Sorry, it's my fault for having started to write shell scripts :) I can start by rewriting run-python-tests.sh and one of you can rewrite the build-version script to a python script. Shell scripts are bad anyway and python scripts are better, so it's a net improvement besides making things better for any windows devs.

**Comment by jiayliu** [comment]
I'll work on the GAE build script.

On Fri, Feb 6, 2015 at 8:59 AM, phoglund <notifications@github.com> wrote:

> Ok, it could be possible to solve this on Windows, but we need to write
> everything as self-contained python scripts. Fortunately grunt-shell
> essentially runs your command verbatim in the shell you're in, and both
> cmd.exe and bash will accept 'python build/some_script.py'.
>
> Sorry, it's my fault for having started to write shell scripts :) I can
> start by rewriting run-python-tests.sh and one of you can rewrite the
> build-version script to a python script. Shell scripts are bad anyway and
> python scripts are better, so it's a net improvement besides making things
> better for any windows devs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/48#issuecomment-73271270>.
>



-- 
Jiayang Liu

**Comment by phoglund** [comment]
Cool.

I started rewriting run_python_tests.sh to python. It sure looks nicer. I need to figure out so that it becomes a lot clearer for devs so they don't get the "import bs4" error when they try to run webtests. Will think more about that on Monday.

Here's the code I wrote for now: https://github.com/phoglund/apprtc/compare/better_pytest?expand=1

**Comment by jiayliu** [comment]
build_app_engine_package is updated to python. I'll work on build_version next.

**Comment by KaptenJansson** [comment]
@jiayliu did you push your changes?

**Comment by KaptenJansson** [comment]
@phoglund informed me that this is done, only thing that remains is the tests runner.
