### ISSUE TITLE
Deploy on windows 2012

### ISSUE THREAD

**Issue by zahov99** [webrtc/apprtc#484]
The steps mentioned in the deployment section (https://github.com/webrtc/apprtc#deployment) lists lot things that should be installed and set and they assume deploy on debian.

What are the required steps to deploy and set an AppRTC project to production on windows 2012?

Is there a simple list of what exactly do i need to install and set on server 2012 in order to get it working?

**Comment by kooldemtech** [comment]
yeah need help on this issue guys. please

**Comment by KaptenJansson** [comment]
Sorry for the late response. The entire project assumes POSIX based systems (testing framework and build tools) and the backend and app is designed for Google App Engine specifically (collider I guess can run on any OS supported by GO, for the turn server it depends on the turn server you use).

For building, testing and development you could use a Debian VM on your Windows server, for actual production deployment you should use Google App Engine.
