### ISSUE TITLE
Failed to get access to local media ( Appr.tc)

### ISSUE THREAD

**Issue by VietPham87** [webrtc/apprtc#485]
**Browsers and versions affected**
Chromium V60.0.3112.89
OS : Debian Jessie 
Hardware : Raspberry Pi 3

**Description**
Got error Failed to get access to local media ( Appr.tc) while entering chat room at https://appr.tc

**Steps to reproduce**
Open  https://appr.tc on chromium V60.0.3112.89 

**Expected results**
Video call working without any error,

**Actual results**
Got error Failed to get access to local media , and can't stream local video

**Comment by KaptenJansson** [comment]
Please include javascript logs. What camera do you have?

**Comment by barcristian** [comment]
I've got the same issue with USB camera Logitech HD Pro Webcam C920
Browsers and versions affected
Chromium V60.0.3112.89
OS : Debian Strecht
Hardware : Raspberry Pi 3

Description
Got error Failed to get access to local media ( Appr.tc) while entering chat room at https://appr.tc

Steps to reproduce
Open https://appr.tc on chromium V60.0.3112.89

Expected results
Video call working without any error,

Actual results
Got error Failed to get access to local media , and can't stream local video
