### ISSUE TITLE
Android Chrome 61, video freezes after connecting

### ISSUE THREAD

**Issue by rukavina** [webrtc/apprtc#487]
**Browsers and versions affected**
Chrome for Android 61

**Description**
After a connection is made to the other peer, eg. Desktop Chrome, remote video is black and local video freezes. Audio still works. Funny enough, after setting up remote debugging, all works fine.

**Steps to reproduce**
- Connect to a room with desktop Chrome
- Connect to the same room with android chrome 61

**Expected results**
Should be able to see both local and remote video on android chrome

**Actual results**
Remote video is black and local video freezes

**Comment by piitaya** [comment]
It's a WebRTC issue : https://bugs.chromium.org/p/chromium/issues/detail?id=769148

**Comment by ozgunlu** [comment]
+1 +1 +1 +1 +1 +1

**Comment by ozgunlu** [comment]
we can not share on chrome anymore.

**Comment by navinkumarg** [comment]
has someone been able to resolve this issue?
