### ISSUE TITLE
Uncaught TypeError: Cannot read property

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/apprtc#495]
**Description**
Can't read property error while running apprtc loopback test URL. 

**Steps:**

0. Browse to https://appr.tc/?debug=loopback
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Listen for audio disruptions and watch for video stutter

**Expected result:**
Audio quality should be good without any hitches.
Video framerate should be constant and smooth without too much jitter and freezes.
No javascript errors

**Actual results**
In Javascript Console:

Uncaught TypeError: Cannot read property 'addIceCandidate' of null
    at a.value (callstats.min.js:22)
    at a.<anonymous> (callstats.min.js:22)
    at RTCPeerConnection.wrappedCallback (apprtc.debug.js:2358)
callstats.min.js:22 Uncaught TypeError: Cannot read property 'addIceCandidate' of null
    at a.value (callstats.min.js:22)
    at a.<anonymous> (callstats.min.js:22)
    at RTCPeerConnection.wrappedCallback (apprtc.debug.js:2358)

Attachment : WebRTC Internals Dump
[webrtc_internals_dump_20_oct_2017.txt]

**Env / Browsers and versions affected**
HP Chromebook
Google Chrome | 62.0.3202.63 (Official Build) beta (64-bit)
Revision | 0
JavaScript | V8 6.2.414.32
Flash | 27.0.0.170 /opt/google/chrome/pepper/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; CrOS x86_64 9901.49.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.63 Safari/537.36

**Comment by rantonysamy** [comment]
callstats.min.js:22 Uncaught TypeError: Cannot read property 'addIceCandidate' of null

**Comment by rantonysamy** [comment]
[can-not-read-property.log](https://github.com/webrtc/apprtc/files/1431001/can-not-read-property.log)

**Comment by rantonysamy** [comment]
Javascript error happens If I try to use apprtc debug loopback with h264. 

Uncaught TypeError : Cannot read property
addIceCandidate of null
at a.value (callstats.min.js:22)
at.a.<anonymous> (callstats.min.ja:22)
at RTCPeerconnection.wrapperCallback (apprtc.debug.js:2358)

**Comment by rantonysamy** [comment]
Still available. Observed in 2 more devices.

**Comment by KaptenJansson** [comment]
This is an issue in the external callstats lib, might need an update.

**Comment by rantonysamy** [comment]
Great ! I will wait for this to get fixed and re-test.

**Comment by KaptenJansson** [comment]
callstats is removed.
