### ISSUE TITLE
I had following webrtc/apptc installation steps, but collider.server cannot enable, I do know what happing.

### ISSUE THREAD

**Issue by goounaluna** [webrtc/apprtc#497]
**Browsers and versions affected**
turnserver-4.5.0.3-CentOS7.1-x86_64.tar.gz

**Description**
collider.service cannot enable

**Steps to reproduce**
I had follow the installation step by:
https://github.com/webrtc/apprtc/tree/master/src/collider

**Expected results**
[root@tsnien ~]# systemctl status collider.service
● collider.service - AppRTC signalling server (Collider)
   Loaded: loaded (/usr/lib/systemd/system/collider.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 三 2017-10-25 19:23:33 CST; 2h 35min ago
  Process: 7994 ExecStart=/root/collider/start.sh (code=exited, status=1/FAILURE)
 Main PID: 7994 (code=exited, status=1/FAILURE)

10月 25 19:23:33 tsnien.mis.csu.edu.tw systemd[1]: Started AppRTC signalling server (Collider).
10月 25 19:23:33 tsnien.mis.csu.edu.tw systemd[1]: Starting AppRTC signalling server (Collider)...
10月 25 19:23:33 tsnien.mis.csu.edu.tw systemd[1]: collider.service: main process exited, code=exited, status=1/FAILURE
10月 25 19:23:33 tsnien.mis.csu.edu.tw systemd[1]: Unit collider.service entered failed state.
10月 25 19:23:33 tsnien.mis.csu.edu.tw systemd[1]: collider.service failed.

**Actual results**

**Comment by KaptenJansson** [comment]
What does your /collider/start.sh file look like? Have you set the appropriate file rights?

**Comment by goounaluna** [comment]
OK，我已經處理好了  謝謝

2018-01-12 16:26 GMT+08:00 Christoffer Jansson <notifications@github.com>:
