### ISSUE TITLE
Jitter / Glitchy & Unacceptable performance - AppRTC Video Calls

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/apprtc#498]
**Browsers and versions affected**
Chromebook HP
Macbook Pro

**Description**
Unacceptable performance for the AppRTC Calls between Chromebooks (Also Chromebook to MAC Book). The same environment, I can do better video calls with Hangouts. 

**Steps to reproduce**
Use two Chromebooks or One of the test device is Chromebook and One is MAC Book Pro
Start a AppRTC Call between them
Check the Video feed for Jitter / Performance

**Expected results**
Good Performance, No Jitter / performance issue, Smooth frame rate for a good quality video call.

**Actual results**
Terrible performance, Not at all acceptable quality. With this quality, AppRTC can't be used as a reference to test WebRTC Video.

**Comment by rantonysamy** [comment]
Ask me for the Logs.

**Comment by KaptenJansson** [comment]
This is related to the hardware capabilities of the machines themselves.
