### ISSUE TITLE
No way to get back to landing page when waiting for other user

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#5]
https://github.com/GoogleChrome/webrtc/issues/445

When you enter a room and no one else has joined, or if the remote side hangs up, there is no way to get back to the landing page. (You can hit back in a browser, but not in the Chrome App)

jiayliu commented 5 days ago
There is a shortcut key 'q' to hangup while waiting, but we probably should make it a visible UI element.

**Comment by KaptenJansson** [comment]
There are now rejoin and new room buttons at the bottom after hanging up, is this enough?
