### ISSUE TITLE
OSError : Error no 2

### ISSUE THREAD

**Issue by SravanKumar09** [webrtc/apprtc#500]
in WebRTC
while i was on "working with Release Branches" 
 i have done 
**$:git checkout -b my_branch refs/remotes/branch-heads/43
$:gclient sync**

after gclient sync i was getting the following error
**File "/webrtc-checkout/depot_tools/gclient_scm.py", line 918, in _Clone
    if os.listdir(tmp_dir):
OSError: [Errno 2] No such file or directory: '/path/to/webrtc/src/third_party/_gclient_junit_7InySC'**

what might be the reason?
i'm working on ubuntu 14.04 system

**Comment by KaptenJansson** [comment]
This is not related to apprtc, please post in https://groups.google.com/d/pendingmsg/discuss-webrtc
