### ISSUE TITLE
AppRTC seems to crash 

### ISSUE THREAD

**Issue by stich86** [webrtc/apprtc#506]
**Browsers and versions affected**
Using custom implementation of iOS and Android Devices using webRTC

**Description**
After some attempts, it seems that AppRTC cannot bind new session and throw this error:

> INFO     2017-11-14 09:57:15,971 apprtc.py:392] Added client 36000753 in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries = 0
> INFO     2017-11-14 09:57:15,972 apprtc.py:95] Applying media constraints: {'audio': True, 'video': True}
> WARNING  2017-11-14 09:57:15,974 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
> INFO     2017-11-14 09:57:15,974 apprtc.py:535] User 36000753 joined room bae1c9d2-8448-42de-9ef9-667d23cc9d28
> INFO     2017-11-14 09:57:15,974 apprtc.py:536] Room bae1c9d2-8448-42de-9ef9-667d23cc9d28 has state ['36000753']
> INFO     2017-11-14 09:57:15,978 module.py:821] default: "POST /join/bae1c9d2-8448-42de-9ef9-667d23cc9d28 HTTP/1.0" 200 1130
> INFO     2017-11-14 09:57:17,422 apprtc.py:460] Saved message for client 36000753:{True, 1} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,431 apprtc.py:460] Saved message for client 36000753:{True, 2} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,461 apprtc.py:460] Saved message for client 36000753:{True, 3} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,476 apprtc.py:460] Saved message for client 36000753:{True, 4} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=2
> INFO     2017-11-14 09:57:17,489 apprtc.py:460] Saved message for client 36000753:{True, 5} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=2
> INFO     2017-11-14 09:57:17,493 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,493 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,494 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,501 apprtc.py:460] Saved message for client 36000753:{True, 6} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,504 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,507 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,511 apprtc.py:460] Saved message for client 36000753:{True, 7} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=1
> INFO     2017-11-14 09:57:17,519 apprtc.py:460] Saved message for client 36000753:{True, 8} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=1
> INFO     2017-11-14 09:57:17,522 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,526 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,529 apprtc.py:460] Saved message for client 36000753:{True, 9} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=2
> INFO     2017-11-14 09:57:17,529 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,532 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,724 apprtc.py:460] Saved message for client 36000753:{True, 10} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,736 apprtc.py:460] Saved message for client 36000753:{True, 11} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,747 apprtc.py:460] Saved message for client 36000753:{True, 12} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,759 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,762 apprtc.py:460] Saved message for client 36000753:{True, 13} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,778 apprtc.py:460] Saved message for client 36000753:{True, 14} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,779 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,780 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,794 apprtc.py:460] Saved message for client 36000753:{True, 15} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:17,798 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,808 apprtc.py:460] Saved message for client 36000753:{True, 16} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=3
> INFO     2017-11-14 09:57:17,809 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,820 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,827 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:17,827 apprtc.py:460] Saved message for client 36000753:{True, 17} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=1
> INFO     2017-11-14 09:57:17,835 apprtc.py:460] Saved message for client 36000753:{True, 18} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=3
> INFO     2017-11-14 09:57:17,869 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:18,353 apprtc.py:460] Saved message for client 36000753:{True, 22} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:18,436 apprtc.py:460] Saved message for client 36000753:{True, 23} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:18,485 apprtc.py:460] Saved message for client 36000753:{True, 24} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:18,546 apprtc.py:460] Saved message for client 36000753:{True, 25} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=1
> INFO     2017-11-14 09:57:18,551 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:18,553 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:18,712 apprtc.py:460] Saved message for client 36000753:{True, 26} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:18,727 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:18,796 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:18,899 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:18,948 apprtc.py:460] Saved message for client 36000753:{True, 27} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=1
> INFO     2017-11-14 09:57:19,240 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:19,324 apprtc.py:460] Saved message for client 36000753:{True, 28} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=1
> INFO     2017-11-14 09:57:19,578 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:19,685 apprtc.py:460] Saved message for client 36000753:{True, 29} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=2
> INFO     2017-11-14 09:57:19,921 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:19,929 apprtc.py:460] Saved message for client 36000753:{True, 30} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=2
> INFO     2017-11-14 09:57:20,008 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,014 apprtc.py:460] Saved message for client 36000753:{True, 31} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=2
> INFO     2017-11-14 09:57:20,095 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,110 apprtc.py:460] Saved message for client 36000753:{True, 32} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=3
> INFO     2017-11-14 09:57:20,163 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,170 apprtc.py:460] Saved message for client 36000753:{True, 33} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=3
> INFO     2017-11-14 09:57:20,203 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,218 apprtc.py:460] Saved message for client 36000753:{True, 34} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=4
> INFO     2017-11-14 09:57:20,247 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,273 apprtc.py:460] Saved message for client 36000753:{True, 35} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=5
> INFO     2017-11-14 09:57:20,300 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,323 apprtc.py:460] Saved message for client 36000753:{True, 36} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=8
> INFO     2017-11-14 09:57:20,343 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,370 apprtc.py:460] Saved message for client 36000753:{True, 37} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=9
> INFO     2017-11-14 09:57:20,419 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,422 apprtc.py:460] Saved message for client 36000753:{True, 38} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:20,431 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,458 apprtc.py:460] Saved message for client 36000753:{True, 39} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:20,467 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> INFO     2017-11-14 09:57:20,566 apprtc.py:460] Saved message for client 36000753:{True, 40} in room bae1c9d2-8448-42de-9ef9-667d23cc9d28, retries=0
> INFO     2017-11-14 09:57:20,569 module.py:821] default: "POST /message/bae1c9d2-8448-42de-9ef9-667d23cc9d28/36000753 HTTP/1.0" 200 21
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 103, in <module>
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 103, in <module>
>         _run_file(__file__, globals())
> _run_file(__file__, globals())
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 97, in _run_file
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 97, in _run_file
>         execfile(_PATHS.script_file(script_name), globals_)
> execfile(_PATHS.script_file(script_name), globals_)
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 192, in <module>
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 192, in <module>
>         main()
> main()
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 181, in main
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 181, in main
>         server.start()
> server.start()
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 330, in start
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 330, in start
>         self._start_all_fixed_port(host_ports)
> self._start_all_fixed_port(host_ports)
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 367, in _start_all_fixed_port
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 367, in _start_all_fixed_port
>         raise BindError('Unable to bind %s:%s' % self.bind_addr)
> raise BindError('Unable to bind %s:%s' % self.bind_addr)
> google.appengine.tools.devappserver2.wsgi_servergoogle.appengine.tools.devappserver2.wsgi_server..BindErrorBindError: : Unable to bind localhost:21270Unable to bind localhost:21270

Anyone can help me?
Reboot the server seems to solve this issue.. but it not so stable

**Comment by KaptenJansson** [comment]
Looks like you are exhausting the sockets on the machine.
