### ISSUE TITLE
"Failed to load resource" errors in Javascript logs during apprtc calls

### ISSUE THREAD

**Issue by cvranjani** [webrtc/apprtc#507]
Browsers and versions affected: M64  64.0.3265.0 / 10128.0.0 dev
OS: Chrome, Linux

**Steps to reproduce**
Start an apprtc loopback call or peer2peer call from chrome device

**Expected results**
Apprtc call should connect successfully and there should not be any errors in javascript console

**Actual results**
Apprtc call connects successfully but javascript console shows errors: 
"Failed to load resource: net::ERR_TIMED_OUT
callstats.min.js:23 OPTIONS https://appsettings.callstats.io/v1/apps/110765241 net::ERR_TIMED_OUT
callstats.min.js:24 Uncaught TypeError: Cannot read property 'submissionIntervalMs' of undefined
    at d (callstats.min.js:24)
    at XMLHttpRequest.Bb.j.onload (callstats.min.js:23)"

[ Caroline Apprtc call js logs M64.txt](https://github.com/webrtc/apprtc/files/1476526/Caroline.Apprtc.call.js.logs.M64.txt)

**Comment by KaptenJansson** [comment]
callstats is removed.
