### ISSUE TITLE
Document to describe the signaling protocol

### ISSUE THREAD

**Issue by leslie-qiwang** [webrtc/apprtc#508]
**Browsers and versions affected**
general

**Description**
Is there a document to describe the signaling protocol? We are thinking to modify native peer connection client code to work with mobile and web. Thus the protocol would be very useful.

**Steps to reproduce**
N/A

**Expected results**
N/A

**Actual results**
N/a

**Comment by KaptenJansson** [comment]
Could you elaborate? Do you mean the signalling protocol that AppRTC uses? Signalling is outside of the WebRTC spec and is up to eachone to solve themselves. Not sure how that relates to peerconnections since it already works on mobile and web. Please clarify.
