### ISSUE TITLE
The remote side hung up. Both Chrome users.

### ISSUE THREAD

**Issue by veer-suthar** [webrtc/apprtc#509]
Mac OS X - Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Windows - Version 62.0.3202.94 (Official Build) (64-bit)

[](https://appr.tc/r/677573877)

It was joined by both users and gave the same error. 
One was in UAE region, while other was in Pakistan region.

It was working two weeks ago, on the same network, same regions. 
[client1.txt](https://github.com/webrtc/apprtc/files/1495168/client1.txt)
[client2.txt](https://github.com/webrtc/apprtc/files/1495169/client2.txt)

Anything changed?

**Comment by KaptenJansson** [comment]
No, nothing should have changed from our side.

In the client1 log I only see an ARPA address (169) and a local private network address (192.x), both host candidates meaning you will only be able to connect to someone on the same network or machine.

In the client2 log I can see it srflx and host candidates meaning it should be reachable on the local network and from the internet given that there is no restrictive NAT device in between.

I would check why client1 seemingly cannot to connect to the turn servers, maybe the turn servers AppRTC provides are being blocked in UAE or Pakistan (not sure which client connected from where)?

**Comment by veer-suthar** [comment]
client 1 was UAE
client 2 was Pakistan.

How can I rectify that AppRTC turn servers are blocked or not, & if blocked than at which level?

**Comment by KaptenJansson** [comment]
You cannot, ask your internet service provider.
