### ISSUE TITLE
Only part of the remote video is displayed on a mobile device with hardware acceleration

### ISSUE THREAD

**Issue by milenyordanov** [webrtc/apprtc#511]
**Browsers and versions affected**
Tested with:
- Desktop - Chrome 62 on OS X 10.13.1
- Mobile:
  - Chrome 62 on Android 6, codec: VP8, device: Nexus 5
  - Chrome 62 on Android 6, codec: VP8, device: Samsung Galaxy J5
  - Chrome 62 on Android 7, codec: VP9, device: Samsung Galaxy Tab S3

**Description**
Only part of the remote video is displayed on the mobile device if WebRtc scales down the video resolution while the connection is active.
This happens only if the mobile device uses hardware acceleration. If the mobile device does not use hardware acceleration then everything works fine. 

**Steps to reproduce**

1) On desktop Chrome 62 open the link: https://appr.tc/r/test0001?vsc=VP8&hd=true

2) On mobile Chrome 62 (Nexus 5) open the link https://appr.tc/r/test0001?vsc=VP8&hd=true

3) Join both browser in the room test0001

4) Now the connection is established at 720p and everything works fine. See the Screenshot_mobile_720p.png

5) Wait 1-2 minutes till WebRtc scales down the video resolution. If that does not happen then use an appropriate tool to limit the network bandwidth to 500 Kbps.

6) WebRtc scales down the desktop Video Tx from 720p to 540p. See ScreenShot_desktop_540p.png and Screenshot_mobile_540p.png. Now the video on the mobile device does not look good. The bottom right part of the video is missing.

7) WebRtc scales down the desktop Video Tx from 540p to 360p. See Screenshot_mobile_360p.png. Now the video on the mobile device looks even worse. Only 25% of the original video is displayed.

If the connection is between two desktop browsers then the remote video is always good.

If the mobile device does not use hardware acceleration then the remote video is good. For example if chrome://flags is used to  Disable "Hardware-accelerated video decode" then the issue disappears.

**Expected results**

The whole remote video the be displayed on a mobile device with hardware acceleration for VP8 and VP9.

**Actual results**

Only part of the remote video is displayed on a mobile device with hardware acceleration for VP8 and VP9.

screenshot_mobile_720p
![screenshot_mobile_720p](https://user-images.githubusercontent.com/11314287/33230678-8a21f2ce-d1f0-11e7-878d-ae6f768b3b2c.png)

screenshot_mobile_540p
![screenshot_mobile_540p](https://user-images.githubusercontent.com/11314287/33230677-8a0919ca-d1f0-11e7-8009-f95593983e63.png)

screenshot_mobile_360p
![screenshot_mobile_360p](https://user-images.githubusercontent.com/11314287/33230676-89efd6d6-d1f0-11e7-90ba-1d6b723da2ec.png)

screenshot_desktop_540p
![screenshot_desktop_540p](https://user-images.githubusercontent.com/11314287/33230872-ea65a362-d1f3-11e7-86fe-1f92cb70e3e4.png)

**Comment by KaptenJansson** [comment]
Thanks for the thorough report!

@magjed do you what know what the reason could be? I know nothing about HW encoders/decoders.

**Comment by milenyordanov** [comment]
I tried the same scenario with Firefox 57 on Android 6, codec: VP8, device: Nexus 5
It worked fine even when the WebRtc scaled down the video resolution.
I checked the Firefox settings in about:config. Its default setting are:

media.navigator.hardware.vp8_decode.acceleration_enabled FALSE
media.navigator.hardware.vp8_encode.acceleration_enabled TRUE

I modified these to 

media.navigator.hardware.vp8_decode.acceleration_enabled TRUE
media.navigator.hardware.vp8_encode.acceleration_enabled TRUE

and tried again. The result is below. After a minute Firefox crashed.

![screenshot_20171129-062350](https://user-images.githubusercontent.com/11314287/33358213-e2785616-d4cf-11e7-855f-829f682a8647.png)

**Comment by magjed** [comment]
It sounds like something is broken with the Android Chrome HW encoder.
CC:ing braveyao@.

**Comment by braveyao** [comment]
It's can be reproduced easily with a test between two Android phones.
It looks like a rendering issue, maybe hw decoding. I'm not familiar with  HW decoding/rendering in chromium, but I can help to narrow it down whether it's a chromium issue or apprtc issue.
