### ISSUE TITLE
i got this error when downloand ClosureCompiler,

### ISSUE THREAD

**Issue by acenodie** [webrtc/apprtc#514]
i got this error when downloand ClosureCompiler,
and i can install compiler-latest.tar.gz by wget??
what should i do??

Configuring ClosureCompiler.js 1.6.1 ...

  Downloading https://dl.google.com/closure-compiler/compiler-latest.tar.gz ...
  ✖ Download failed: Error: read ECONNRESET

  ✖ Unfortunately, ClosureCompiler.js could not be configured.
    See: https://github.com/dcodeIO/ClosureCompiler.js (create an issue maybe)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! closurecompiler@1.6.1 configure: `node scripts/configure.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the closurecompiler@1.6.1 configure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acenodie/.npm/_logs/2017-12-03T15_05_52_505Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! closurecompiler@1.6.1 install: `npm run-script configure`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the closurecompiler@1.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acenodie/.npm/_logs/2017-12-03T15_05_53_291Z-debug.log

**Comment by acenodie** [comment]
my system is Ubuntu 16.04.1

**Comment by acenodie** [comment]
i do like this:
sudo apt-get install nodejs

sudo apt-get install npm

sudo npm install -g npm

sudo apt-get install nodejs-legacy

sudo npm -g install grunt-cli

cd apprtc

npm install

**Comment by KaptenJansson** [comment]
Download failed: Error: read ECONNRESET indicates a network issue. 

Can you click on the link directly: https://dl.google.com/closure-compiler/compiler-latest.tar.gz ?

**Comment by acenodie** [comment]
That's not network issue ，because i can download the compiler-latest.tar.gz by wget.

$ wget https://dl.google.com/closure-compiler/compiler-latest.tar.gz
--2017-12-09 04:48:35--  https://dl.google.com/closure-compiler/compiler-latest.tar.gz
Resolving dl.google.com (dl.google.com)... 203.208.43.97, 203.208.43.102, 203.208.43.100, ...
Connecting to dl.google.com (dl.google.com)|203.208.43.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6868395 (6.5M) [application/octet-stream]
Saving to: ‘compiler-latest.tar.gz’

compiler-latest.tar.gz                100%[=======================================================================>]   6.55M  11.9MB/s    in 0.6s    

2017-12-09 04:48:36 (11.9 MB/s) - ‘compiler-latest.tar.gz’ saved [6868395/6868395]

**Comment by KaptenJansson** [comment]
ECONNRESET indicates the remote side is hanging up. It could be the node version you are using, try to install a later one from nodejs (version 6 or later) directly rather than apt-get as it might install an old version.

**Comment by acenodie** [comment]
# acenodie @ VM-119-248-ubuntu in ~/webrtc_server/apprtc/apprtc on git:master x [11:41:51] 
$ node --version
v9.2.0

# acenodie @ VM-119-248-ubuntu in ~/webrtc_server/apprtc/apprtc on git:master x [14:46:57] 
$ npm --version
5.5.1

**Comment by acenodie** [comment]
This is my version about node and npm, This is the newlest version...

**Comment by acenodie** [comment]
This is my version about node and npm, This is the newlest version...
$ node --version
v9.2.0

$ npm --version
5.5.1

**Comment by radhey1994** [comment]
intel@pnp-server-2:~/apprtc$ sudo npm install --proxy https://proxy-chain.intel.com:911

> closurecompiler@1.6.1 install /home/intel/apprtc/node_modules/closurecompiler
> npm run-script configure


> closurecompiler@1.6.1 configure /home/intel/apprtc/node_modules/closurecompiler
> node scripts/configure.js

Configuring ClosureCompiler.js 1.6.1 ...

  Downloading https://dl.google.com/closure-compiler/compiler-latest.tar.gz ...
  ✖ Download failed: Error: connect ETIMEDOUT 172.217.31.46:80

  ✖ Unfortunately, ClosureCompiler.js could not be configured.
    See: https://github.com/dcodeIO/ClosureCompiler.js (create an issue maybe)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! closurecompiler@1.6.1 configure: `node scripts/configure.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the closurecompiler@1.6.1 configure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/intel/.npm/_logs/2018-01-09T07_13_10_192Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! closurecompiler@1.6.1 install: `npm run-script configure`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the closurecompiler@1.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



Hey i am aslo facing the same issue..
Please do the needful help..

**Comment by KaptenJansson** [comment]
I'm using node v8.4.0 and NPM 5.6.0 and it works fine (just deleted my node_modules folder and did npm install).

Could you try the LTS version, i.e. 8.9.4 rather than the latest?

https://nodejs.org/en/

**Comment by radhey1994** [comment]
Hi I already have the same version which you have suggested. But still getting the same error.
Actually i am trying to install this under the corporate network, Is it a problem??
Please help me out..

**Comment by KaptenJansson** [comment]
yes it could be a problem. Anyway its definitely a network problem that I cannot help solve.

**Comment by chinalinbo** [comment]
same problem in China
