### ISSUE TITLE
Heard some news about App rejection in iOS.

### ISSUE THREAD

**Issue by karuppasamypandian0856** [webrtc/apprtc#516]
Hi all,

Currently i'm going to integrate this webRTC into my app. i have some doubts,Any body faced this problem. The below contents are true? if i use other video streaming Framework my app will reject ?

"Video streaming content over a cellular network longer than 10 minutes must use HTTP Live Streaming and include a baseline 192 kbps or lower HTTP Live stream."

Note Reference :  https://developer.apple.com/library/content/qa/qa1767/_index.html

I hope you can understand my problem.

**Comment by KaptenJansson** [comment]
Not related to AppRTC, https://groups.google.com/d/pendingmsg/discuss-webrtc is the forum for questions like this.
