### ISSUE TITLE
Post 503 error thrown 

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/apprtc#518]
**Browsers and versions affected**
M64 Dev ToT
10172.0.0 / 64.0.3282.11 : Peppy

chrome browser and chrome device

**Description**
0. Browse to https://appr.tc/?deb
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Speak over mic (or scratch the mc) and Listen for audio disruptions
3. Wait for a min or so. This 100% reproducible. 

**Expected results**
no error should be thrown

**Actual results**
503 error is thrown for Post event.

![screenshot 2017-12-11 at 5 03 28 pm](https://user-images.githubusercontent.com/34342420/33840591-a2a855d4-de95-11e7-849d-4a2a5942bcd3.png)

**Comment by vkkkumar** [comment]
Same issue in doing the similar test case for video. I have attached the apprtc log and screen shot for video Post 503. 

[apprtc log video.log](https://github.com/webrtc/apprtc/files/1548477/apprtc.log.video.log)
![screenshot 2017-12-11 at 5 20 41 pm](https://user-images.githubusercontent.com/34342420/33841363-d1bbd966-de97-11e7-9cc5-880f992af3c8.png)

0. Browse to https://appr.tc/?debug=loopback&audio=false
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Speak over mic (or scratch the mic) 
3. Once in a while keep muting the video. It happens only with ~10 second interval between muting and un-muting the video.

**Comment by KaptenJansson** [comment]
I believe this is in a intermittent issue in the one the backends.

**Comment by KaptenJansson** [comment]
Also the url in the original description is incorrect, there is no ?deb URL parameter.
