### ISSUE TITLE
[new feature request] Need the video dimensions for QVGA, VGA, HD, Full Hd and 4K

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/apprtc#521]
**Browsers and versions affected**
10176.13.1 / 64.0.3282.24 

**Description**
Need to see all the corresponding dimensions from QVGA to 4K resolutions. 

**Steps to reproduce**
0. Browse to https://webrtc.github.io/samples/src/content/getusermedia/resolution/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Follow the instructions on the page

**Expected results**
Add UI field and show what are the dimensions for each resolutions from QVGA to 4K.

**Actual results**
Nothing is displayed. 

It is a new feature request which could be very useful for testing.

**Comment by KaptenJansson** [comment]
Incorrect repo, should be filed in the samples repo. Also either you or @rantonysamy can make a PR with these changes.
