### ISSUE TITLE
[Feature Request] Selecting Video / Audio Codex - Loopback  

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/apprtc#522]
**Browsers and versions affected**
All

**Description**
It will be nice to have list box that has the video audio codex in the call view, so that the user could be able to start a call with the below combinations.

List Box 1: Possible Audio Codex (Opus, iSAC 16k, G722), PCMU
List Box 2: Video Codex (Vp8, VP9, H264, H265, MPEG
Check box (Enable): Loopback

Example a User could start call combinations with the below right from the homepage. 

Opus + VP8
Opus + VP9
Opus + H264

and so on.

**Comment by KaptenJansson** [comment]
https://appr.tc/params.html
