### ISSUE TITLE
Unable to rejoin room after unexpected disconnection (Room full error)

### ISSUE THREAD

**Issue by ramrandhawa** [webrtc/apprtc#526]
**Browsers and versions affected**

All (note that the issue described here is the same as the issue described in 251 and 397; the fix proposed below should work for those issues as well)

**Description**

When a client does not cleanly disconnect, but just looses connectivity, they are not cleanly removed from the room. The room state therefore still has two clients in it, and the room is reported as "full" when the disconnected client tries to rejoin.

**Steps to reproduce**

Open two windows to the same room in Chrome. In the second window, press F12 to open developer tools and in the Network tab select "offline" to take that browser window offline; hit refresh, and you will be disconnected from the room. Close the developer tools and then try to reconnect. You will be told the room is full.

**Expected results**

When a client is unexpectedly disconnected, they should be cleanly removed from the room.

**Actual results**

The collider sends a "bye" message to AppRTC -- however, this message does not include the id of the client who has left, and therefore the application has no way of removing that client from the room.

**Stop gap solution**

This is a solution that works for now:

in "peerconnectionclient.js" find the lines:

    if (messageObj.type === "bye") {
      if (this.onremotehangup) {
        this.onremotehangup();
      }

and below them add the following code

      var roomserver = this.params_.roomLink;
      roomserver = roomserver.substring( 0, roomserver.indexOf('/r/') );
      var path = roomserver + "/clear/" + this.params_.roomId + "/" + this.params_.clientId;
      return sendUrlRequest("POST", path, true);

This code will call a new function known as "clear" when a "bye" signal is received. The clear function should drop the **other** caller from the room. Now we have to create the clear function.

In apprtc.py, find the lines:

    def get_other_client(self, client_id):
      for key, client in self.clients.items():
        if key is not client_id:
          return client
      return None

and below them add the lines:

    def get_other_client_id(self, client_id):
      for key, client in self.clients.items():
        if key is not client_id:
          return key
      return None

Note that we are returning **key** and not **client**.

Also in apprtc.py, after the function "remove_client_from_room" and before the function "save_message_from_client" add the following function:

```
def remove_other_client_from_room(host, room_id, client_id):
  key = get_memcache_key_for_room(host, room_id)
  memcache_client = memcache.Client()
  retries = 0
  # Compare and set retry loop.
  while True:
    room = memcache_client.gets(key)
    other_client = room.get_other_client_id(client_id)
    if room is None:
      logging.warning('remove_client_from_room: Unknown room ' + room_id)
      return {'error': constants.RESPONSE_UNKNOWN_ROOM, 'room_state': None}
    if not room.has_client(other_client):
      logging.warning('remove_client_from_room: Unknown client ' + other_client + \
          ' for room ' + room_id)
      return {'error': constants.RESPONSE_UNKNOWN_CLIENT, 'room_state': None}

    room.remove_client(other_client)

    if memcache_client.cas(key, room, constants.ROOM_MEMCACHE_EXPIRATION_SEC):
      logging.info('Removed client %s from room %s, retries=%d' \
          %(other_client, room_id, retries))
      return {'error': None, 'room_state': str(room)}
    retries = retries + 1
```

Then, in the same file, after the function LeavePage and before the function MessagePage **EDIT:** Sorry, an earlier version of this ClearPage function was causing problems; this one has been updated (see below for details).

```
class ClearPage(webapp2.RequestHandler):
  def post(self, room_id, client_id):
    room = memcache.get(
        get_memcache_key_for_room(self.request.host_url, room_id))
    if room is not None:
      if room.get_occupancy() >= 2:
        result = remove_other_client_from_room(
            self.request.host_url, room_id, client_id)
        if result['error'] is None:
          logging.info('Unexpected disconnection')
          logging.info('Room ' + room_id + ' has state ' + result['room_state'])
```

And finally, at the very end of the file, after the line

    ('/leave/([a-zA-Z0-9-_]+)/([a-zA-Z0-9-_]+)', LeavePage),

add the line

    ('/clear/([a-zA-Z0-9-_]+)/([a-zA-Z0-9-_]+)', ClearPage),

**How does this work and what are the pitfalls?**

This temporary solution fixes the problem for me -- when someone is unexpectedly disconnected from a room, the application removes that client cleanly, and they are then able to reconnect without getting the "room is full" message.

If at some point the code is modified to allow more than two clients, this will probably break. Also, I don't know what other effects this may have, so until someone smarter than me has chimed in, use it at your own risk.

**Edit**

The original version of the ClearPage function I posted did not bother checking if the room still had two occupants; as such, it would get fired when one person intentionally left the room, and would kick the the other person out of the room as well. Checking to make sure there are still two people in the room seems to fix this, I think.

**Comment by KaptenJansson** [comment]
Yes we rely on a clean disconnect in order to clear the room, otherwise a timeout will clear it after a while.

**Comment by koushikg14** [comment]
so, will this be working fine now ??

"The original version of the ClearPage function I posted did not bother checking if the room still had two occupants; as such, it would get fired when one person intentionally left the room, and would kick the the other person out of the room as well. Checking to make sure there are still two people in the room seems to fix this, I think."

**Comment by jxcr** [comment]
> Yes we rely on a clean disconnect in order to clear the room, otherwise a timeout will clear it after a while.

For this issue, can we reduce wsReadTimeoutSec 's value in collider.go to accelerate clean disconnect? Because the default value of wsReadTimeoutSec is 60 * 60 * 24, it means that if this client disconnected, we know that timeout one day later. It's too later.
