### ISSUE TITLE
AppRTC android sdk working with Chrome but not with Firefox. android app showing "Connection error: ICE connection failed".

### ISSUE THREAD

**Issue by Mangesh92** [webrtc/apprtc#527]
I am exploring googles webrtc demo project (AppRTC) for Android to Web video conferencing. 

I have setup server by following instruction [https://github.com/webrtc/apprtc](url) on Google Cloud Platform i.e.  AppRTC server code on app-engine and  required components (Coturn, Collider) on compute-engine VM. everything is working fine on browsers, but facing some issue with android native app (AppRTC android sdk found on [https://github.com/njovy/AppRTCDemo]() )to Firefox browser communication . it is showing "**Connection error: ICE connection failed.**"

 I have done lot of research on this and come up with following observations:

1.using [https://appr.tc](url) on both side Firefox and Android sdk working fine.
2. If I use Numb free stun/turn server then also it is working on both Firefox and Android sdk. 
3.By using Coturn server (setup on google compute-engine VM) then Android sdk working with chrome browser but not with firefox.

Please help in doing this.

**Comment by KaptenJansson** [comment]
Please provide logs from the firefox call.

**Comment by Mangesh92** [comment]
Hi Kapten,

Thanks for quick reply.Please find attached logs from Firefox and from Android studio.

![androiderror](https://user-images.githubusercontent.com/35487747/34990583-a60418c6-faec-11e7-83df-dbf6b883f0a5.PNG)
[AndroidWithCoturn.txt](https://github.com/webrtc/apprtc/files/1635195/AndroidWithCoturn.txt)
[FirefoxWithCoturn.txt](https://github.com/webrtc/apprtc/files/1635196/FirefoxWithCoturn.txt)

**Comment by Mangesh92** [comment]
Chrome and Android sdk working fine with the same setup.

Please find attached Chrome and Android Logs.
[AndroidWorkingFineWithChrome.txt](https://github.com/webrtc/apprtc/files/1635256/AndroidWorkingFineWithChrome.txt)
[ChromeCoturn_workingFine.txt](https://github.com/webrtc/apprtc/files/1635257/ChromeCoturn_workingFine.txt)

**Comment by Mangesh92** [comment]
Any Updates on this? Please provide some direction so that I can go ahead.

**Comment by Mangesh92** [comment]
Any updates?

**Comment by KaptenJansson** [comment]
It seems like firefox does not like your coturn server, are there any known issues with this?
