### ISSUE TITLE
Room full Error

### ISSUE THREAD

**Issue by sam0hack** [webrtc/apprtc#532]
Hi There. I've successfully installed it on my server and it is working.

The problem is I can't add more than 2 users in the room it gives me room full error.
I'm making this app for multi-user conference purpose for ios and android.

Can anyone tell me where I should modify the code so it can accept multi-users?

**Comment by tengg** [comment]
Also interested. But I don't think it's small change to take more than 2 people in one room.

**Comment by sam0hack** [comment]
is it possible @milkypostman @ptman @louquillio @rbeene @tengg ?

**Comment by ptman** [comment]
Don't just add random people to your issue

**Comment by KaptenJansson** [comment]
Sorry to many assumptions of a 2 person call only to just point to pieces of code.

**Comment by aleafboat** [comment]
i want to multi-users
