### ISSUE TITLE
Java error during dev server installation.

### ISSUE THREAD

**Issue by WildHagai** [webrtc/apprtc#535]
**Browsers and versions affected**
Windows 7 x64

**Description**
While following the dev server installation guide in the documentation, I have installed nodejs and grunt, running `npm install` was succesful, and all the dependencies were downloaded, and Java was installed as well, but after running `grunt build` I got an error for not having python "requests" module, so I installed it and the next error was presented:

> C:\Projects\apprtc-master>grunt build
> Running "shell:buildAppEnginePackage" (shell) task
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> 
> Running "shell:genJsEnums" (shell) task
> src >>> src/web_app/js
> 
> Running "closurecompiler:debug" (closurecompiler) task
> 
> Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine
> /js/apprtc.debug.js
> Warning: java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:480)
> Exception in thread "main"  Use --force to continue.
> 
> 
> Aborted due to warnings.

I've tried to reinstall java a few times but it didn't work.

I have also tried to rerun `npm install`, and the result is as such:

> C:\Projects\apprtc-master>npm install
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules\fsevents\node_modules\os-tmpdir):
> npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open 'C:\Projects\apprtc-master\node_modules\fsevents\node_modules\os-tmpdir\package.json.2559731568'
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osenv@0.1.4 (node_modules\fsevents\node_modules\osenv):
> npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Projects\apprtc-master\node_modules\fsevents\node_modules\osenv\package.json.549617697' -> 'C:\Projects\apprtc-master\node_modules\fsevents\node_modules\osenv\package.json'
> 
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  any
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: x64
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-02-12T18_19_54_737Z-debug.log
> 

the log file:
[2018-02-12T18_19_54_737Z-debug.log](https://github.com/webrtc/apprtc/files/1717304/2018-02-12T18_19_54_737Z-debug.log)

**Comment by KaptenJansson** [comment]
It looks like a NPM dependency we use do not support Windows.

Windows is not supported (not saying it could not work but would probably need a bit of work) hence it's using on your own risk.

Better to just spin up a VM or use Linux in Windows in Windows 10.

**Comment by kauly** [comment]
```
Warning: java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0 
```
This warning occur in ubuntu too, requets error also occur.

**Comment by SharvariGC** [comment]
Yes. This warning occurs in ubuntu 18.04 as well. Why was this issue closed with no resolution or guidelines about what to do??

**Comment by kauly** [comment]
This app is very outdated, it's a chrome app for God sake. We can't use this anymore.

**Comment by SharvariGC** [comment]
@kauly can you direct me to other resources to build a video chat app. Are there any other demo apps available?

**Comment by kauly** [comment]
Unfortunately I can't find a demo like this.  In the webrtc website you will find some.

**Comment by WildHagai** [comment]
I have found a "framework" for video chats. I'm using websync (ASP.NET) as a signaling server and RTCMultiConnection.js version 1.6 as client. nowadays there's newer signaling servers and clients. but I needed something that works on .NET environment.

https://github.com/muaz-khan/RTCMultiConnection - in the demos he's using a free public signaling server.
