### ISSUE TITLE
Getting Blank screen while accessing AppRTC URL...

### ISSUE THREAD

**Issue by radhey1994** [webrtc/apprtc#536]
**Description**
I have installed and configured AppRTC, Collider, turn-server successfully.
But getting the blank screen only with AppRTC Logo while accessing the AppRTC URL
Please find the console logs :
~/shubham/apprtc/src/app_engine$ sudo python /usr/lib/google-cloud-sdk/platform/google_appengine/dev_appserver.py /home/intel/shubham1/apprtc/out/app_engine --host=10.223.107.113

INFO     2018-02-15 09:46:33,542 sdk_update_checker.py:231] Checking for updates to the SDK.
INFO     2018-02-15 09:46:36,625 sdk_update_checker.py:247] Update check failed: <urlopen error [Errno 101] Network is unreachable>
INFO     2018-02-15 09:46:36,645 api_server.py:308] Starting API server at: http://localhost:35776
INFO     2018-02-15 09:46:36,651 dispatcher.py:255] Starting module "default" running at: http://10.223.107.113:8080
INFO     2018-02-15 09:46:36,651 admin_server.py:146] Starting admin server at: http://localhost:8000
INFO     2018-02-15 09:46:43,004 apprtc.py:95] Applying media constraints: {'audio': True, 'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}}
WARNING  2018-02-15 09:46:43,006 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
INFO     2018-02-15 09:46:43,015 module.py:835] default: "GET / HTTP/1.1" 200 8269
INFO     2018-02-15 09:46:43,109 module.py:835] default: "GET /css/main.css HTTP/1.1" 304 -
INFO     2018-02-15 09:46:43,157 module.py:835] default: "GET /js/apprtc.debug.js HTTP/1.1" 404 -
INFO     2018-02-15 09:46:43,679 module.py:835] default: "GET /images/webrtc-icon-192x192.png HTTP/1.1" 200 31806
INFO     2018-02-15 09:46:46,187 apprtc.py:95] Applying media constraints: {'audio': True, 'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}}
WARNING  2018-02-15 09:46:46,189 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
INFO     2018-02-15 09:46:46,191 module.py:835] default: "GET / HTTP/1.1" 200 8269
INFO     2018-02-15 09:46:46,277 module.py:835] default: "GET /css/main.css HTTP/1.1" 304 -
INFO     2018-02-15 09:46:46,277 module.py:835] default: "GET /js/apprtc.debug.js HTTP/1.1" 404 -
INFO     2018-02-15 09:46:46,731 module.py:835] default: "GET /images/webrtc-icon-192x192.png HTTP/1.1" 200 31806
INFO     2018-02-15 09:55:38,384 apprtc.py:95] Applying media constraints: {'audio': True, 'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}}
WARNING  2018-02-15 09:55:38,386 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
INFO     2018-02-15 09:55:38,389 module.py:835] default: "GET / HTTP/1.1" 200 8269
INFO     2018-02-15 09:55:39,177 module.py:835] default: "GET /css/main.css HTTP/1.1" 304 -
INFO     2018-02-15 09:55:39,382 module.py:835] default: "GET /js/apprtc.debug.js HTTP/1.1" 404 -
INFO     2018-02-15 09:55:40,274 module.py:835] default: "GET /images/webrtc-icon-192x192.png HTTP/1.1" 200 31806

Have also attached the browser screenshot while accessing AppRTC URL.

![image](https://user-images.githubusercontent.com/35101122/36251036-b9ca95fc-1265-11e8-8b9a-36264e7afd3d.png)

Please help me out to identify what i am missing??

Thanks in advance

**Comment by radhey1994** [comment]
@KaptenJansson  Please help me out

**Comment by KaptenJansson** [comment]
Why have you specified the hostflag? What happens when you try without it?

Also could you do `ls` in the out/app_engine folder and list the contents here?

**Comment by radhey1994** [comment]
I have specified the host flag because i want to access AppRTC on multiple machines. Without Specifying host flag i am able to access AppRTC only on the host machine through localhost.

I have resolved the previous issue and getting the AppRTC homepage as:
![image](https://user-images.githubusercontent.com/35101122/36419460-ed994ac2-1657-11e8-92a2-eeb04d7e0585.png)

with the console logs as:
pnp-server-2:~/shubham/apprtc$ sudo python /usr/lib/google-cloud-sdk/platform/google_appengine/dev_appserver.py /home/intel/shubham/apprtc/out/app_engine/ --host=10.223.107.113
INFO     2018-02-20 10:35:10,014 sdk_update_checker.py:231] Checking for updates to the SDK.
INFO     2018-02-20 10:35:13,094 sdk_update_checker.py:247] Update check failed: <urlopen error [Errno 101] Network is unreachable>
INFO     2018-02-20 10:35:13,114 api_server.py:308] Starting API server at: http://localhost:39321
INFO     2018-02-20 10:35:13,120 dispatcher.py:255] Starting module "default" running at: http://10.223.107.113:8080
INFO     2018-02-20 10:35:13,121 admin_server.py:146] Starting admin server at: http://localhost:8000
INFO     2018-02-20 10:35:17,811 apprtc.py:95] Applying media constraints: {'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}, 'audio': True}
WARNING  2018-02-20 10:35:17,814 apprtc.py:138] Invalid or no value returned from memcache, using fallback: null
INFO     2018-02-20 10:35:17,823 module.py:835] default: "GET / HTTP/1.1" 200 8237
INFO     2018-02-20 10:35:17,924 module.py:835] default: "GET /css/main.css HTTP/1.1" 304 -
INFO     2018-02-20 10:35:17,924 module.py:835] default: "GET /js/apprtc.debug.js HTTP/1.1" 304 -
...................................................................................................................................
On clicking on Join Button getting the below Error:
![image](https://user-images.githubusercontent.com/35101122/36419582-54bb9912-1658-11e8-9470-362603f5f8b1.png)

.....................................................................................................................................
Have successfully deployed turn server and collider . They are up and running. You can see that below:
![image](https://user-images.githubusercontent.com/35101122/36419670-98a6e7f8-1658-11e8-8b18-b9c2ac631d31.png)

......................................................................................................................................
Also if i access turnserver ULR i.e 10.223.107.113:3478 getting the output in browser as:
![image](https://user-images.githubusercontent.com/35101122/36419747-cefea73c-1658-11e8-9da0-b7e1271583cd.png)
and with https://10.223.107.113:3478
![image](https://user-images.githubusercontent.com/35101122/36419793-f27a87e4-1658-11e8-84be-9e729250a297.png)

@KaptenJansson : Please help me out to trace what else i am missing..

**Comment by radhey1994** [comment]
After setting up all the things why i am getting like this:
![image](https://user-images.githubusercontent.com/35101122/36419919-51e5d788-1659-11e8-8a62-749d6e3c8ae6.png)

**Comment by radhey1994** [comment]
Chrome browser Console Logs:
![image](https://user-images.githubusercontent.com/35101122/36421109-4860f784-165d-11e8-88da-6022897a2980.png)
0.327: Initializing; server= undefined.
16:41:32.192 apprtc.debug.js:5585 0.328: Initializing; room=undefined.
16:41:36.608 apprtc.debug.js:2344 [Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
(anonymous) @ apprtc.debug.js:2344
16:41:36.609 apprtc.debug.js:5585 4.745: Opening signaling channel.
16:41:36.611 apprtc.debug.js:5585 4.747: Error getting user media: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
16:41:36.612 apprtc.debug.js:5585 4.748: getUserMedia error: Failed to get access to local media. Error name was NotSupportedError. Continuing without sending a stream.
16:41:46.415 apprtc.debug.js:5585 14.551: ICE server request error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
16:41:46.447 apprtc.debug.js:5094 WebSocket connection to 'ws://10.223.107.113:8089/ws' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE
(anonymous) @ apprtc.debug.js:5094
16:41:46.448 apprtc.debug.js:5585 14.583: Joined the room.
16:41:46.448 apprtc.debug.js:5585 14.584: WebSocket open error: WebSocket error.
16:41:46.448 apprtc.debug.js:5585 14.584: WebSocket register error: WebSocket error.

**Comment by radhey1994** [comment]
Any Update???

**Comment by KaptenJansson** [comment]
GetUserMedia requires HTTPS or localhost, read the warning in the logs.

**Comment by radhey1994** [comment]
Yes i know that... Could yon please tell me how to do Turnserver configuration for AppRTC

**Comment by einsteinarbert** [comment]
> Yes i know that... Could yon please tell me how to do Turnserver configuration for AppRTC

Hey radhey1994 can you give me some link for the guide of deloy your turnserver?

**Comment by roshansabale** [comment]
Hello @radhey1994 ,

Have solved your problems regarding Browser error and a blank screen.

**Comment by einsteinarbert** [comment]
> Hello @radhey1994 ,
> 
> Have solved your problems regarding Browser error and a blank screen.

I think collinder has invalid cert files in /cert or in apprtc wrong config of collinder: using web address instead of ip address will resolve issue failed: Error during WebSocket handshake (Collinder must add -tls=true)

**Comment by vikramravindhran** [comment]
How did you get it working, i am facing the same issue, blank page is getting loaded

**Comment by einsteinarbert** [comment]
> How did you get it working, i am facing the same issue, blank page is getting loaded

Take some pictures of F12 console log and give me some details in log of Coliderman, Apprtc..
