### ISSUE TITLE
Add Dockerfile and image on Dockerhub

### ISSUE THREAD

**Issue by kevin-cantwell** [webrtc/apprtc#537]
> Running AppRTC locally requires Google App Engine SDK for Python, Node.js and Grunt.

It would be _great_ if there was a Dockerfile in this repo and/or an image to pull from Dockerhub for running this server locally or in production behind a reverse proxy. For me, it was simply too many steps to get up and running without great effort.

**Comment by KaptenJansson** [comment]
This is google app engine app and that configuration is the only supported one. Running dev_appserver in production is not recommended.

For dev purposes it's fine with a docker container and I do agree that the setup steps could be simplified.

This is an open source project, it's a demo product that works hence we will not spend time on simplifying the setup but PR's are welcome and we will happily review ideas and solutions.

**Comment by kevin-cantwell** [comment]
Fair enough. There are a few examples in the wild. If I can come up with a painless solution I'll submit a PR. Closing.
