### ISSUE TITLE
people from the Middle East cant connect

### ISSUE THREAD

**Issue by aartoul** [webrtc/apprtc#539]
we made an iOS app but people from the Middle East cant connect ... 
we have no idea how to fix ... because we don't know how to find the problem...
we think it may be that webrtc is blocked in Middle East but we don't know how to test it
we tried many turn and stun server from twilio and others nothing is working ... 
we made some turn servers on the port 443 or 80 and its not working either ... 
how can we debug this and if webbrtc is blocked in the Middle East how are they blocking it and what can we do ??

the only think I can see is this warning from the signalling server log ... this happens many times
WARNING  2018-02-19 01:14:21,041 apprtc.py:136] Invalid or no value returned from memcache, using fallback: null
I dont know if it has to do with the problem

**Comment by KaptenJansson** [comment]
I do not know for sure how they do it but certain known services could be blocked by domain and some even by traffic classification.

You could setup your own turn servers.
