### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by droidstered** [webrtc/apprtc#541]
I have installed and configured AppRTC, Collider, turn-server successfully.
But I am facing an issue of Websocket Error. Google chrome console errors are as follows:

**Initializing; server= undefined.
apprtc.debug.js:5583 1.413: Initializing; room=undefined.
apprtc.debug.js:5583 5.209: Opening signaling channel.
apprtc.debug.js:5583 5.390: Got access to local media with mediaConstraints:
  '{"audio":true,"video":{"optional":[{"minWidth":"1280"},{"minHeight":"720"}],"mandatory":{}}}'
apprtc.debug.js:5583 5.390: User has granted access to local media.
apprtc.debug.js:5583 5.391: Attaching local stream.
apprtc.debug.js:5092 WebSocket connection to 'wss://104.198.4.111:8089/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ apprtc.debug.js:5092
apprtc.debug.js:5583 5.578: WebSocket open error: WebSocket error.
apprtc.debug.js:5583 5.584: WebSocket register error: WebSocket error.
apprtc.debug.js:5583 5.636: Joined the room.**

Following is the screenshot of WebSocket error, which I am facing

![screenshot from 2018-02-21 18-38-41](https://user-images.githubusercontent.com/34933394/36482782-5a85bc28-173a-11e8-94d5-2086575aae6f.png)

Collider and AppRTC are on Google VM instance and I have used my own turn-server which has been setup on AWS EC2 instance.
Please help me to resolve this issue. 
Is there any setting in Google APP engine, where I deployed an APP?

**Comment by KaptenJansson** [comment]
See answer in #545
