### ISSUE TITLE
grunt build and runPythonTests rewrite constants.py

### ISSUE THREAD

**Issue by WildHagai** [webrtc/apprtc#542]
**Browsers and versions affected**

**Description**
I have tried to deploy a server, my turn server is running and so is collider,
I tried pythonTests to test the server, and I got many 

> ImportError: Failed to import test module: analytics_test
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
>     module = self._get_module_from_name(name)
>   File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
>     __import__(name)
>   File "/root/apprtc/out/app_engine/analytics_test.py", line 9, in <module>
>     import analytics
>   File "/root/apprtc/out/app_engine/analytics.py", line 14, in <module>
>     import apiauth
>   File "/root/apprtc/out/app_engine/apiauth.py", line 17, in <module>
>     import constants
>   File "/root/apprtc/out/app_engine/constants.py", line 26
>     {
>     ^
> IndentationError: unexpected indent
> 

this is the output of the task:

> root@rtcserver:~/apprtc# grunt runPythonTests
> Running "shell:pipInstall" (shell) task
> Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: webtest in /root/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 1))
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 1))
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 1))
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 1))
> Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from webtest->-r requirements.txt (line 2))
> Requirement already satisfied: waitress>=0.8.5 in /root/.local/lib/python2.7/site-packages (from webtest->-r requirements.txt (line 2))
> Requirement already satisfied: WebOb>=1.2 in /root/.local/lib/python2.7/site-packages (from webtest->-r requirements.txt (line 2))
> Requirement already satisfied: beautifulsoup4 in /root/.local/lib/python2.7/site-packages (from webtest->-r requirements.txt (line 2))
> 
> Running "shell:ensureGcloudSDKIsInstalled" (shell) task
> 
> All components are up to date.
> 
> All components are up to date.
> Already has google-cloud-sdk, skipping the download
> 
> Running "shell:buildAppEnginePackageWithTests" (shell) task
> 
> Running "shell:runPythonTests" (shell) task
> analytics_test (unittest.loader.ModuleImportFailure) ... ERROR
> testBigquerySchemaClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
> testEnumClass (analytics_enums_test.AnalyticsEnumsTest) ... ok
> analytics_page_test (unittest.loader.ModuleImportFailure) ... ERROR
> probers_test (unittest.loader.ModuleImportFailure) ... ERROR
> apprtc_test (unittest.loader.ModuleImportFailure) ... ERROR
> compute_page_test (unittest.loader.ModuleImportFailure) ... ERROR
> 

I have checked my file over and over each time I build, and the `ICE_SERVER_OVERRIDE = None` was uncommented and the the usually commented line which I uncommented was commented again.
which ended up as:

`# ICE_SERVER_OVERRIDE  = [
  {
    "urls": [
      "turn:<ip>:19305?transport=udp",
      "turn:<ip>:19305?transport=tcp"
    ],
    "username": "admin",
    "credential": "admin"
  },
  {
    "urls": [
      "stun:stun.l.google.com:19302"
    ]
  }
]
`
which results in an indentation error

**Steps to reproduce**
build apprtc after editing the constants.py

**Expected results**
a successful build with the new TURN server defined.

**Actual results**
a successful build without the TURN server, and the constants.py is edited unwantedly.

**Comment by KaptenJansson** [comment]
Yes, its python, please fix your indendation, its critical for python in order to work.
