### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by zjudongze** [webrtc/apprtc#545]
**Browsers and versions affected**
all: chrome in mac, android; edge in windows

**Description**
using appr.tc to do p2p call or loopback test, all failed to establish connection, showing "websocket error"

**Steps to reproduce**
add two clients into appr.tc; or use https://appr.tc/?debug=loopback

**Expected results**
call succeeded

**Actual results**
call failed:
Messages:  
WebSocket open error: WebSocket error.
WebSocket register error: WebSocket error.

Version:    
gitHash:    15ca18959931d2d822216310bac12ed373f2e362
branch:     master
time:       Fri Dec 15 10:28:27 2017 +0100

**Comment by KaptenJansson** [comment]
There was an intermittent outage in the Collider signalling server due to it running out sockets, some rogue client seems to have created lots of rooms and disconnect uncleanly very fast and thus the timeout for the sockets vs socket creation was to great.

**Comment by einsteinarbert** [comment]
Does Collider was down again? or some other error?

> Messages:  
> WebSocket open error: WebSocket error.
> WebSocket register error: WebSocket error.
> 
> Version:    
> gitHash:    cd0ca28fd3b9835ec18645699de4c6a0d5649617
> branch:     KaptenJansson-patch-1
> time:       Tue Feb 26 13:42:14 2019 +0100
