### ISSUE TITLE
Ask a question about coturn server

### ISSUE THREAD

**Issue by daniclyuan** [webrtc/apprtc#550]
A:
This instance can be run in the LAN, but not with 4G, the concrete operation is as follows:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Console:
The SSL certificate used to load resources from https://xx.xxx.org will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
apprtc.debug.js:5814 0.292: Initializing; server= undefined.
apprtc.debug.js:5814 0.295: Initializing; room=undefined.
(index):177 GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ (index):177
(anonymous) @ (index):178
apprtc.debug.js:5814 26.861: Opening signaling channel.
apprtc.debug.js:5814 26.887: Retrieved ICE server information.
apprtc.debug.js:5814 26.924: Joined the room.
apprtc.debug.js:5814 26.926: Signaling channel opened.
apprtc.debug.js:5814 26.927: Registering signaling channel.
apprtc.debug.js:5814 26.927: Signaling channel registered.
apprtc.debug.js:5814 27.140: Got access to local media with mediaConstraints:
  '{"video":true,"audio":true}'
apprtc.debug.js:5814 27.141: User has granted access to local media.
apprtc.debug.js:5814 27.141: Attaching local stream.
apprtc.debug.js:5814 27.143: Starting signaling.
apprtc.debug.js:5814 27.148: ECDSA certificate generated successfully.
apprtc.debug.js:5814 27.149: Creating RTCPeerConnnection with:
  config: '{"iceServers":[{"username":"1521445840:","credential":"bDisQuBQZD1psRGUGFkKWHAeQ70=","urls":["stun:XX.37.24.124:3478?transport=udp","turn:XX.37.24.124:3478?transport=tcp"],"uris":["stun:XX.37.24.124:3479?transport=udp","turn:XX.37.24.124:3479?transport=tcp"]}],"bundlePolicy":"max-bundle","rtcpMuxPolicy":"require","certificates":[{}]}';
  constraints: '{"optional":[]}'.
apprtc.debug.js:5814 27.163: Created PeerConnectionClient
apprtc.debug.js:5814 27.164: Adding local stream.
apprtc.debug.js:5814 27.166: No preference on audio send codec.
apprtc.debug.js:5814 27.167: No preference on video send codec.
apprtc.debug.js:5814 27.170: Sending answer to peer.
apprtc.debug.js:5814 27.186: No preference on audio receive codec.
apprtc.debug.js:5814 27.186: Prefer video receive codec: VP9
apprtc.debug.js:5814 27.190: C->WSS: {"sdp":"v=0\r\no=- 7519568623706370599 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS vsttLzixlWkw4ciErcmw8kFjJzXr5S1pLY7d\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 0 8 110 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:fXci\r\na=ice-pwd:DkCYeIogkR0pQfyV3xFLaEx1\r\na=ice-options:trickle\r\na=fingerprint:sha-256 67:D9:9C:FF:67:BB:13:B3:6C:E3:4B:47:A2:E3:DD:05:E2:52:9C:70:1B:09:5D:14:71:15:27:55:FF:3F:44:34\r\na=setup:active\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:3315272054 cname:Jg/gZ3GcctgxYzuD\r\na=ssrc:3315272054 msid:vsttLzixlWkw4ciErcmw8kFjJzXr5S1pLY7d 173d7e71-c6d8-4bd8-aa55-9894c27808af\r\na=ssrc:3315272054 mslabel:vsttLzixlWkw4ciErcmw8kFjJzXr5S1pLY7d\r\na=ssrc:3315272054 label:173d7e71-c6d8-4bd8-aa55-9894c27808af\r\nm=video 9 UDP/TLS/RTP/SAVPF 98 96 97 99 100 101 102 127 104\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:fXci\r\na=ice-pwd:DkCYeIogkR0pQfyV3xFLaEx1\r\na=ice-options:trickle\r\na=fingerprint:sha-256 67:D9:9C:FF:67:BB:13:B3:6C:E3:4B:47:A2:E3:DD:05:E2:52:9C:70:1B:09:5D:14:71:15:27:55:FF:3F:44:34\r\na=setup:active\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 H264/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 red/90000\r\na=rtpmap:127 rtx/90000\r\na=fmtp:127 apt=102\r\na=rtpmap:104 ulpfec/90000\r\na=ssrc-group:FID 2236928297 4207740415\r\na=ssrc:2236928297 cname:Jg/gZ3GcctgxYzuD\r\na=ssrc:2236928297 msid:vsttLzixlWkw4ciErcmw8kFjJzXr5S1pLY7d c585b206-bed5-4e84-b1c6-97c277ea35bb\r\na=ssrc:2236928297 mslabel:vsttLzixlWkw4ciErcmw8kFjJzXr5S1pLY7d\r\na=ssrc:2236928297 label:c585b206-bed5-4e84-b1c6-97c277ea35bb\r\na=ssrc:4207740415 cname:Jg/gZ3GcctgxYzuD\r\na=ssrc:4207740415 msid:vsttLzixlWkw4ciErcmw8kFjJzXr5S1pLY7d c585b206-bed5-4e84-b1c6-97c277ea35bb\r\na=ssrc:4207740415 mslabel:vsttLzixlWkw4ciErcmw8kFjJzXr5S1pLY7d\r\na=ssrc:4207740415 label:c585b206-bed5-4e84-b1c6-97c277ea35bb\r\n","type":"answer"}
apprtc.debug.js:5814 27.192: Remote candidate added successfully.
apprtc.debug.js:5814 27.194: Signaling state changed to: have-remote-offer
apprtc.debug.js:5814 27.195: Remote stream added.
apprtc.debug.js:5814 27.196: Remote stream added.
apprtc.debug.js:5814 27.198: Set remote session description success.
apprtc.debug.js:5814 27.199: Waiting for remote video.
apprtc.debug.js:5814 27.206: Signaling state changed to: stable
apprtc.debug.js:5814 27.207: Set session description success.
apprtc.debug.js:5814 27.209: ICE connection state changed to: checking
apprtc.debug.js:5814 27.210: C->WSS: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:1493399139 1 udp 2122260223 192.168.1.12 51325 typ host generation 0 ufrag fXci network-id 2"}
apprtc.debug.js:5814 27.211: C->WSS: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:4093142497 1 udp 2122194687 192.168.95.1 51326 typ host generation 0 ufrag fXci network-id 1 network-cost 10"}
apprtc.debug.js:5814 42.304: ICE connection state changed to: failed
apprtc.debug.js:5814 66.958: End of candidates.

+++++++++++++++++++++++++++++++++++++++++++++++
3.My coturn server state is as follows
![qq 20180319155156](https://user-images.githubusercontent.com/21326887/37583723-7c36d674-2b8d-11e8-8819-5c3306651e57.png)

![qq 20180319153948](https://user-images.githubusercontent.com/21326887/37583669-4a34e6f2-2b8d-11e8-9d39-063e8539d68b.png)

**Comment by KaptenJansson** [comment]
What is your question?

**Comment by einsteinarbert** [comment]
Hey, did you config ok for connect via 4G, help me please:
https://github.com/webrtc/apprtc/issues/615

**Comment by einsteinarbert** [comment]
Hey, I resolve issue when connect via mobile network:
https://github.com/webrtc/apprtc/issues/615
