### ISSUE TITLE
AppRTC between android and IOS device

### ISSUE THREAD

**Issue by hesijie** [webrtc/apprtc#555]
When I try to do video chat between Android-Android,IOS-IOS devices ,it is working,But If i try from Android-IOS,IOS-Android,It is not working.

Can anyone help me to resolve this problem?

**Comment by eldurihari** [comment]
Did you got solution for this ??

**Comment by MukFlex** [comment]
Did you got solution for this

**Comment by hesijie** [comment]
Sorry, it still stands unresolved. Here is an article about my problem,you can refer it.
https://stackoverflow.com/questions/47462247/webrtc-is-not-working-connecting-safari-with-chrome-for-android
