### ISSUE TITLE
Firefox can’t establish a connection to the server at wss://192.168.1.171:8089/ws.

### ISSUE THREAD

**Issue by sltruman** [webrtc/apprtc#561]
**Browsers and versions affected**
Firefox 59.0.2 x64

**Description**
I was deployed apprtc and collider 
then this error appeared on the bottom after visited http://192.168.1.171:8080/ when join room 

**Expected results**
![screenshot from 2018-06-06 15-31-42](https://user-images.githubusercontent.com/12881971/41023712-bef67c12-699f-11e8-8031-bb60459d76b5.png)

**Actual results**
no red.

**Comment by ArnaudIntern2018** [comment]
you have to run collider

**Comment by techsin** [comment]
so what happened

**Comment by Axingx** [comment]
If you have this problem with collider, you can modify the WSS_INSTANCE_HOST_KEY of constants.py for your domain:8089 or domain:443

**Comment by NeelamParmar** [comment]
I am facing same error. I have installed collider, apprtc, coturn, stun.
Modified WSS_INSTANCE_HOST_KEY  also.
Stun, Turn and collider all are running on server.
When I hit wss url it shows "Invalid Path/" on browser.

And in console shows "Firefox can’t establish a connection to the server at wss://192.168.43.146:8089/ws."

Any help would be appreciated .

**Comment by techsin** [comment]
https://stackoverflow.com/a/52470378/1319799

**Comment by techsin** [comment]
https://github.com/websockets/ws/issues/1446
