### ISSUE TITLE
Is https://appr.tc down?

### ISSUE THREAD

**Issue by sumanc** [webrtc/apprtc#565]
**Browsers and versions affected**
Chrome V66

**Description**
Getting the following error;

WebSocket open error: WebSocket error.
WebSocket register error: WebSocket error.

**Steps to reproduce**
access https://appr.tc

**Expected results**
No errors

**Actual results**
Web socket failures

Messages:  
WebSocket open error: WebSocket error.
WebSocket register error: WebSocket error.

Version:    
gitHash:    20cdd7652d58c9cf47ef92ba0190a5505760dc05
branch:     master
time:       Fri Mar 9 17:06:42 2018 +0100

**Comment by fippo** [comment]
the certificate expired. someone is on it.

**Comment by GalaevAlexey** [comment]
Same issue...

**Comment by sumanc** [comment]
Thank you. Is it also the cause for iOS app failures when connecting to
https://appr.tc?

Thanks,

--Suman

**Comment by fippo** [comment]
Most likely. See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/31d0BovQssE/iMaLsRMuBAAJ

**Comment by fippo** [comment]
seems to be resolved now. send #hugops to @MirkoBonadei

**Comment by juberti** [comment]
Resolving.

**Comment by sumanc** [comment]
Yes, I am able to verify on AppRTCMobile sample and my own app.

Thanks a lot!

--Suman

**Comment by fippo** [comment]
note that you should run your own server

**Comment by LorenzoMcMaster** [comment]
The issue has been closed, but it's still not working for me using appRTCMobile and firefox.
to run my own server, where is  the certificate that need to be changed?

**Comment by sumanc** [comment]
Yes, I am in the process of setting it up. It is a bit complicated than I
thought (for me) and taking more time than I expected.

Thanks,

--Suman

**Comment by einsteinarbert** [comment]
Please, this issue is now appear, someone fixes that?
