### ISSUE TITLE
WebSocket open error

### ISSUE THREAD

**Issue by winterbro** [webrtc/apprtc#57]
So this happened. Everything worked well yesterday, now I can't see the room url or connect with people.

![screen-apprtc](https://cloud.githubusercontent.com/assets/1440104/6144623/0aaecfdc-b1da-11e4-8ca9-559c0b861cc8.jpg)

**Comment by KaptenJansson** [comment]
Latest push seems to have broken signalling, I noticed the room name is not appended to the URL anymore.

**Comment by KaptenJansson** [comment]
0.304: Initializing; server= undefined.
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 0.304: Initializing; room=982495439.
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 0.348: Got access to local media with mediaConstraints:
  '{"audio":true,"video":{"optional":[{"minWidth":"1280"},{"minHeight":"720"}],"mandatory":{}}}'
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 0.348: User has granted access to local media.
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 0.513: Retrieved TURN server information.
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 1.685: Opening signaling channel.
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 1.831: Joined the room.
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 WebSocket connection to 'wss://apprtc-ws.webrtc.org/ws' failed: Error in connection establishment: net::ERR_TIMED_OUT
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 31.821: WebSocket open error: WebSocket error.
apprtc.debug.js.pagespeed.jm.tFx8UtP6de56uECGa3-X.js:1 31.822: WebSocket register error: WebSocket error.

**Comment by KaptenJansson** [comment]
I do not think server= should be undefined.

**Comment by KaptenJansson** [comment]
This commit 5a287975f2b132c4b3eca63b8d5eadfd5fe85fd7 changes: 
WSS_HOST = 'apprtc-ws.webrtc.org'
-WSS_PORT = '8089'

To:
WSS_HOST_PORT_PAIR = 'apprtc-ws.webrtc.org:443'

Could it be a just a connection issue to the websocket server?

**Comment by KaptenJansson** [comment]
So when I try using https://www.websocket.org/echo.html I get ERR_CONNECTION_REFUSED for wss://apprtc-ws.webrtc.org:8089 while I get ERR_TIMED_OUT for wss://apprtc-ws.webrtc.org:443.

Was this port change intentional?

**Comment by chuckhays** [comment]
server=undefined is expected for apprtc, it is only defined in the Chrome app.

**Comment by chuckhays** [comment]
The room is not appended because of what you later found, the websocket connection is timing out:

Error from console: WebSocket connection to 'wss://apprtc-ws.webrtc.org/ws' failed: Error in connection establishment: net::ERR_TIMED_OUT

**Comment by juberti** [comment]
I suppose this is related to the collider prober errors?

**Comment by jiayliu** [comment]
The service has recovered. The code bug in Collider is tracked in a separate bug.

**Comment by n0per** [comment]
Go to  src/app_engine/constants.py remove the old line and replace it with the line below instead, it should work:

WSS_HOST_PORT_PAIRS = ['apprtc-ws.webrtc.org:8089', 'apprtc-ws.webrtc.org:8089']

I got this from the android app sample

**Comment by alisidaniel** [comment]
Hello pleas is apprtc  open source cos am getting this WebSocket register error: Failed to join the room: Status=404, response
