### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by HasnainAD** [webrtc/apprtc#586]
**Browsers and versions affected**
Android native app

**Description** 
All devices with my app installed on them are getting same error. Previously, I was getting the recent issue, /issues/585 (apprtc expired certificate). Now that that issue seems to be fixed, and now I am starting to get this one.

**Steps to reproduce**
Running the same app that worked previously

**Expected results**
Should initiate chat between two peers.

**Actual results**
Connection Error: HTTP POST to https://appr.tc/join/9f48fcc6-30e0-47f2-ba35-f6cb8da19a7b error: ja
va.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by maxvuluy** [comment]
I think it's the COMODO untrusted certification on Android issue
https://support.comodo.com/index.php?/Knowledgebase/Article/View/1019/1/untrusted-certificate-error-on-android
Can anyone solve this?

**Comment by HasnainAD** [comment]
Does apprtc provides any certificate files, like the ones used in this [official android documentation](https://developer.android.com/training/articles/security-ssl#CommonProblems)

**Comment by maxvuluy** [comment]
Open https://appr.tc with a browser.
Click the lock icon, then you can see the detail of certification.
You can find the url to download the certification file somewhere (depend on browser).
I'm not sure, but I think it is.

I will try this way later.
If you tried, please let me know the result.
Thank you.

**Comment by elixiroflife4u** [comment]
+1 for this issue. I am also getting "Trust anchor for certification path not found" when attempting any kind of call from AppRTC Android demo app (approx release 63 and rel 68). The same app on same android device had worked till around October 30.

**Comment by maxvuluy** [comment]
The solution @HasnainAD mentioned worked.
1. Download [certification file](http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt) and put in asset of android project.
2. Run the following code to make android trust this certification.
```Java
httpsURLConnection.setSSLSocketFactory(trustCert().getSocketFactory());

private SSLContext trustCert() throws CertificateException,IOException,KeyStoreException,
	NoSuchAlgorithmException,KeyManagementException {
	AssetManager assetManager = getAssets();
	CertificateFactory cf = CertificateFactory.getInstance("X.509");
	Certificate ca = cf.generateCertificate(assetManager.open("COMODORSADomainValidationSecureServerCA.crt"));

	// Create a KeyStore containing our trusted CAs
	String keyStoreType = KeyStore.getDefaultType();
	KeyStore keyStore = KeyStore.getInstance(keyStoreType);
	keyStore.load(null, null);
	keyStore.setCertificateEntry("ca", ca);

	// Create a TrustManager that trusts the CAs in our KeyStore
	String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
	TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
	tmf.init(keyStore);

	// Create an SSLContext that uses our TrustManager
	SSLContext context = SSLContext.getInstance("TLS");
	context.init(null, tmf.getTrustManagers(), null);
	return context;
}
```

But I think it's just a compromise solution for those who cannot wait.
The ultimate way is the server need to correct it to make certification work on android.

**Comment by devedgarKim** [comment]
> The solution @HasnainAD mentioned worked.
> 
> 1. Download [certification file](http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt) and put in asset of android project.
> 2. Run the following code to make android trust this certification.
> 
> ```java
> httpsURLConnection.setSSLSocketFactory(trustCert().getSocketFactory());
> 
> private SSLContext trustCert() throws CertificateException,IOException,KeyStoreException,
> 	NoSuchAlgorithmException,KeyManagementException {
> 	AssetManager assetManager = getAssets();
> 	CertificateFactory cf = CertificateFactory.getInstance("X.509");
> 	Certificate ca = cf.generateCertificate(assetManager.open("COMODORSADomainValidationSecureServerCA.crt"));
> 
> 	// Create a KeyStore containing our trusted CAs
> 	String keyStoreType = KeyStore.getDefaultType();
> 	KeyStore keyStore = KeyStore.getInstance(keyStoreType);
> 	keyStore.load(null, null);
> 	keyStore.setCertificateEntry("ca", ca);
> 
> 	// Create a TrustManager that trusts the CAs in our KeyStore
> 	String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
> 	TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
> 	tmf.init(keyStore);
> 
> 	// Create an SSLContext that uses our TrustManager
> 	SSLContext context = SSLContext.getInstance("TLS");
> 	context.init(null, tmf.getTrustManagers(), null);
> 	return context;
> }
> ```
> 
> But I think it's just a compromise solution for those who cannot wait.
> The ultimate way is the server need to correct it to make certification work on android.

great it working well

**Comment by HasnainAD** [comment]
> The solution @HasnainAD mentioned worked.
> 
> 1. Download [certification file](http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt) and put in asset of android project.
> 2. Run the following code to make android trust this certification.
> 
> ```java
> httpsURLConnection.setSSLSocketFactory(trustCert().getSocketFactory());
> 
> private SSLContext trustCert() throws CertificateException,IOException,KeyStoreException,
> 	NoSuchAlgorithmException,KeyManagementException {
> 	AssetManager assetManager = getAssets();
> 	CertificateFactory cf = CertificateFactory.getInstance("X.509");
> 	Certificate ca = cf.generateCertificate(assetManager.open("COMODORSADomainValidationSecureServerCA.crt"));
> 
> 	// Create a KeyStore containing our trusted CAs
> 	String keyStoreType = KeyStore.getDefaultType();
> 	KeyStore keyStore = KeyStore.getInstance(keyStoreType);
> 	keyStore.load(null, null);
> 	keyStore.setCertificateEntry("ca", ca);
> 
> 	// Create a TrustManager that trusts the CAs in our KeyStore
> 	String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
> 	TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
> 	tmf.init(keyStore);
> 
> 	// Create an SSLContext that uses our TrustManager
> 	SSLContext context = SSLContext.getInstance("TLS");
> 	context.init(null, tmf.getTrustManagers(), null);
> 	return context;
> }
> ```
> 
> But I think it's just a compromise solution for those who cannot wait.
> The ultimate way is the server need to correct it to make certification work on android.

Hey max, thanks for the code, do I need to run it one time per session or everytime before starting a call?

**Comment by remyasics** [comment]
httpsURLConnection.setSSLSocketFactory(trustCert().getSocketFactory());
where should I add this line of code.I am using AsyncHttpURLConnection in my code

**Comment by HasnainAD** [comment]
@remyasics Use Https instead of Http

**Comment by maxvuluy** [comment]
@HasnainAD 
trustCert() only called once, then you can use the produced SSLContext multiple times.

@remyasics 
```Java
private void sendHttpMessage() {
    try {
      HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
      ...
      if (connection instanceof HttpsURLConnection) {
        ((HttpsURLConnection) connection).setSSLSocketFactory(sslContext.getSocketFactory());
      }
      ...
      // Get response.
      int responseCode = connection.getResponseCode();
      ...
    } catch (SocketTimeoutException e) {
      events.onHttpError("HTTP " + method + " to " + url + " timeout");
    } catch (IOException e) {
      events.onHttpError("HTTP " + method + " to " + url + " error: " + e.getMessage());
    }
  }
```

**Comment by HasnainAD** [comment]
@maxvuluy how to use it with AsyncHttpURLConnection?

Following is my code:
`   httpConnection =
                new AsyncHttpURLConnection("POST", roomUrl, roomMessage, new AsyncHttpEvents() {
                    @Override
                    public void onHttpError(String errorMessage) {
                        Log.e(TAG, "Room connection error: " + errorMessage);
                        events.onSignalingParametersError(errorMessage);
                    }

                    @Override
                    public void onHttpComplete(String response) {
                        roomHttpResponseParse(response);
                    }
                });
        httpConnection.send();`

**Comment by remyasics** [comment]
> @remyasics
> 
> ```java
> private void sendHttpMessage() {
>     try {
>       HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
>       ...
>       if (connection instanceof HttpsURLConnection) {
>         ((HttpsURLConnection) connection).setSSLSocketFactory(sslContext.getSocketFactory());
>       }
>       ...
>       // Get response.
>       int responseCode = connection.getResponseCode();
>       ...
>     } catch (SocketTimeoutException e) {
>       events.onHttpError("HTTP " + method + " to " + url + " timeout");
>     } catch (IOException e) {
>       events.onHttpError("HTTP " + method + " to " + url + " error: " + e.getMessage());
>     }
>   }
> ```
Thank you

**Comment by remyasics** [comment]
AssetManager assetManager = getAssets();
is giving me error

**Comment by maxvuluy** [comment]
@HasnainAD I modified AsyncHttpURLConnection as below
@remyasics I'm sorry. [getAssets()](https://developer.android.com/reference/android/content/Context#getAssets()) is a function of [Context](https://developer.android.com/reference/android/content/Context).
You can put turstCert() in a Activity.
```Java
public class AsyncHttpURLConnection {
    private static SSLContext sslContext;

    public static setSSLContext(SSLContext sslContext) {
        this.sslContext = sslContext;
    }

    private void sendHttpMessage() {
        try {
            HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
            ...
            if (connection instanceof HttpsURLConnection) {
                ((HttpsURLConnection) connection).setSSLSocketFactory(sslContext.getSocketFactory());
            }
            ...
            // Get response.
            int responseCode = connection.getResponseCode();
            ...
        }
    }
}

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onResume() {
        super.onResume();
        AsyncHttpURLConnection.setSSLContext(trustCert());
    }

    private SSLContext trustCert() throws CertificateException,IOException,KeyStoreException,NoSuchAlgorithmException,KeyManagementException {
        AssetManager assetManager = getAssets();
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        Certificate ca = cf.generateCertificate(assetManager.open("COMODORSADomainValidationSecureServerCA.crt"));

        // Create a KeyStore containing our trusted CAs
        String keyStoreType = KeyStore.getDefaultType();
        KeyStore keyStore = KeyStore.getInstance(keyStoreType);
        keyStore.load(null, null);
        keyStore.setCertificateEntry("ca", ca);

        // Create a TrustManager that trusts the CAs in our KeyStore
        String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
        TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
        tmf.init(keyStore);

        // Create an SSLContext that uses our TrustManager
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(null, tmf.getTrustManagers(), null);
        return context;
    }
}
```

**Comment by HasnainAD** [comment]
@maxvuluy 
Not working for me:
```
Log.e("Asynchttpurl", "sendhttpmessage");
            HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
            byte[] postData = new byte[0];
            if (message != null) {
                postData = message.getBytes("UTF-8");
            }
            if (connection instanceof HttpsURLConnection) {
                Log.e("Asynchttpurl", "connection instanceof HttpsURLConnection");
                ((HttpsURLConnection) connection).setSSLSocketFactory(Certification.sslContext.getSocketFactory());
            }
//            connection .setSSLSocketFactory(Certification.sslContext.getSocketFactory());

            //connection.setSSLSocketFactory(Certification.sslContext.getSocketFactory());
            connection.setRequestMethod(method);
            connection.setUseCaches(false);
            connection.setDoInput(true);
            connection.setConnectTimeout(HTTP_TIMEOUT_MS);
            connection.setReadTimeout(HTTP_TIMEOUT_MS);
```

Is it possible that the certificate file may not be valid?

**Comment by remyasics** [comment]
@HasnainAD  Thanks a lot

**Comment by remyasics** [comment]
I think since it has certificate verification we can use it for production also.Any idea?

**Comment by maxvuluy** [comment]
I thought this issue is not completely solved.
I use [openssl](https://www.openssl.org/docs/manmaster/man1/openssl.html) to trace certificate chain of [appr.tc](https://appr.tc)
```
openssl s_client -connect appr.tc:443 -servername appr.tc
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=appr.tc
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
```

According to [COMODO's explanation](https://support.comodo.com/index.php?/Knowledgebase/Article/View/1019/1/untrusted-certificate-error-on-android) and [android guide](https://developer.android.com/training/articles/security-ssl#MissingCa), the certificate chain of server seems to be incomplete.
Is there any member of WebRTC can help confirm this issue?

The solution with TrustManager is just a compromise. I don't think it's a good solution.
It would be great if manager of [appr.tc](https://appr.tc) could help solve this issue.
@HasnainAD could you help re-open this issue? Thanks.

**Comment by einsteinarbert** [comment]
Does appr.tc website error cert?

**Comment by valon91** [comment]
> ```java
> httpsURLConnection.setSSLSocketFactory(trustCert().getSocketFactory());
> ```

where to write this code, how to call it? I am using volley for parsing JSON , please help

**Comment by vj12354** [comment]
I had similar issue and mange to solve it by following steps described in https://developer.android.com/training/articles/security-config

But the config changes, without any complicated code logic, would only work on Android version 24 & above.

So for android lower then N (version 24) the solution is to via code changes as mentioned above. If you are using OkHttp, then follow the customTrust:
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java
