### ISSUE TITLE
appr.tc is not presenting the complete certificate chain

### ISSUE THREAD

**Issue by maxvuluy** [webrtc/apprtc#587]
**Browsers and versions affected**
Android app

**Description**
Android doesn't trust new certificate.
According to [COMODO's explanation](https://support.comodo.com/index.php?/Knowledgebase/Article/View/1019/1/untrusted-certificate-error-on-android) and [android guide](https://developer.android.com/training/articles/security-ssl#MissingCa), new certificate of appr.tc seems not presenting the complete certificate chain.

I use openssl to trace certificate chain of appr.tc and get the following result.
```
openssl s_client -connect appr.tc:443 -servername appr.tc
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=appr.tc
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
```

There is a solution at #586 to make android app works, but still the new certificate has something wrong.

**Steps to reproduce**
HTTP POST to https://appr.tc/join/[ROOM_ID]

**Expected results**
Get result successfully.

**Actual results**
Get error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by einsteinarbert** [comment]
I think the appr.tc web error, because my code is not update but suddenly error

**Comment by KaptenJansson** [comment]
Should be fixed now. Please try again.

**Comment by einsteinarbert** [comment]
did It fixed? We pull from master?

Vào 17:12, T.4, 28 Th11, 2018 Christoffer Jansson <notifications@github.com>
đã viết:

**Comment by KaptenJansson** [comment]
Fixed the certificate itself, no need to pull down anything.

**Comment by maxvuluy** [comment]
I checked it has been fixed, thank you.
