### ISSUE TITLE
Promise polyfill in testpolyfills can't chain

### ISSUE THREAD

**Issue by chuckhays** [webrtc/apprtc#59]
Our implementation of Promise in testpolyfills doesn't chain promises. I ran into this error a while back and had to restructure the app code so unit tests would pass. I didn't realize what the cause was until now.

Example code that won't work:

var p = new MyPromise(function(resolve, reject) {
    console.log('starting timer');
    setTimeout(function() { resolve('a'); }, 2000);
  });

  p.then(function(v) {
    console.log(v);
    return 'b';
  }).then(function(s) {
    console.log(s);
  })

Only the last .then will be used because .then always returns the same promise, it should return a new promise or keep a list of deferred promises.

It might be simpler to see if we can use one of the existing promise polyfills.

**Comment by KaptenJansson** [comment]
Closing due to age.
