### ISSUE TITLE
Add robots.txt to apprtc

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#6]
https://github.com/GoogleChrome/webrtc/issues/438

(See the original issue for full comment thread)

 samdutton commented 7 days ago
If no objections, I think we should run the Webmaster Tools robots.txt
tester <https://support.google.com/webmasters/answer/6062598>.

This requires adding an HTML verification file first:
apprtc.appspot.com/google1b7eb21c5b594ba0.html.
…

**Comment by jiayliu** [comment]
I see that we already have the google*.html file in the repo. What should be the next step?

**Comment by samdutton** [comment]
Next step is for that file to be deployed for verification by Webmaster Tools, so we can then check robots.txt functionality with Webmaster Tools.  

See https://github.com/webrtc/samples/pull/439.

@marwahvikas

**Comment by marwahvikas** [comment]
Let me try deploy apprtc.

**Comment by KaptenJansson** [comment]
I assume this is obsolete now.
