### ISSUE TITLE
apprtc websocket server down?

### ISSUE THREAD

**Issue by fippo** [webrtc/apprtc#602]
currently getting websocket timeouts, the red box says
```
WebSocket open error: WebSocket error
WebSocket register error: WebSocket error
```
after a while (~30s - 60s). @ggarber can see the same.

@MirkoBonadei @KaptenJansson can you please take a look? @juberti said there were cert errors recently.

**Comment by fippo** [comment]
and its back up. You might still want to investigate why.

**Comment by fippo** [comment]
@NeelamParmar if you run apprtc in production you should absolutely run your own signaling server. apprtc uses https://github.com/webrtc/apprtc/tree/master/src/collider

**Comment by NeelamParmar** [comment]
Ok, thank you .

I will check it out .

**Comment by NeelamParmar** [comment]
Collider is created using Go, can we create signaling server using node.js ?

**Comment by fippo** [comment]
there are a bunch of nodejs signaling servers, but they use a different protocol than apprtc.

**Comment by NeelamParmar** [comment]
ohh ok.
It means we need to use only collider with Apprtc ? Others won't work with it as protocols are different ?

**Comment by brianpeiris** [comment]
Just wanted to report that the websocket server is down again. Timeout connecting to wss://apprtc-ws.webrtc.org/ws

**Comment by elixiroflife4u** [comment]
I am not hitting websocket timeouts persay, but it seems something really strange is going on with the webserver. The loopback calls in the Android Apprtc demo app are failing to connect since the offer gets sent to some abyss.

**Comment by KaptenJansson** [comment]
What happens is some client goes rogue or maliciously creates thousands of bogus TLS connections to the signalling server and it runs out of sockets. Once those timeout it works again. Load balancing between the two instances was broken due to a VM name change but that has been rectified. Not sure if that will help in this situation though.

**Comment by ArnavVashisthCodingAccountnew** [comment]
apprtc has been shutdown, according to their GitHub repository. Farewell , **AppRTC**

**Comment by fippo** [comment]
this has been overtaken by events indeed

**Comment by ArnavVashisthCodingAccountnew** [comment]
It has also shocked me

**Comment by paragpatel** [comment]
If you are missing https://appr.tc/ , give a try to https://hub.docker.com/r/pegome/apprtc It has support for SSL and inbuilt TURN server.
