### ISSUE TITLE
Can anyone explain why the latency in this site is soooooo low?

### ISSUE THREAD

**Issue by xwa130** [webrtc/apprtc#621]
**Browsers and versions affected**
Chrome

**Description**
Why the latency achieved by appr.tc is soooo low?

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by einsteinarbert** [comment]
because p2p: no need replay from server except turnsever, the call go directly between two peer.

**Comment by xwa130** [comment]
@einsteinarbert 
I'm sorry for my confusing expression. I know the P2P topology. I have a working P2P but the latency is roughly 500 ms. However, this one looks like around 100 ms. I'm curious, how it could achieve this.
Thanks for your reply though.
