### ISSUE TITLE
When I open AppRTC in the local host it does not show anything, error: AppController is not defined at initialize. 

### ISSUE THREAD

**Issue by EliosSs** [webrtc/apprtc#635]
**Browsers and versions affected**
Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Description**

Hey guys, good evening. I am new in WebRTC and I am trying to launch as it says in the page 
https://github.com/webrtc/apprtc. 

I am following all the steps of the "development" section. I am not doing the deployment steps because them are not necessary, right? or those steps are necessarry to run the demo locally?

When I install all the tools, google sdk, node and grunt I run the command

pip command to install requirements.txt file run without problems.

$ dev_appserver.py ./out/app_engine/
And when I go to the link --> https://localhost:8080
the screen keeps black and nothing appears in the site, no buttons, no video. Just the hyper links of "terms, privacy, code repo".
And in the chrome console it says: Uncaught ReferenceError: AppController is not defined
    at initialize ((index):159)
    at (index):170

Back in the linux terminal it says the following:
INFO     2019-08-11 02:40:49,939 apprtc.py:95] Applying media constraints: {'video': {'optional': [{'minWidth': '1280'}, {'minHeight': '720'}], 'mandatory': {}}, 'audio': True}
WARNING  2019-08-11 02:40:49,963 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
INFO     2019-08-11 02:40:50,070 module.py:861] default: "GET / HTTP/1.1" 200 8269
INFO     2019-08-11 02:40:50,203 module.py:861] default: "GET /css/main.css HTTP/1.1" 304 -
INFO     2019-08-11 02:40:50,223 module.py:861] default: "GET /js/apprtc.debug.js HTTP/1.1" 404 -
INFO     2019-08-11 02:40:52,027 module.py:861] default: "GET /manifest.json HTTP/1.1" 304 -
INFO     2019-08-11 02:40:52,238 module.py:861] default: "GET /images/webrtc-icon-192x192.png HTTP/1.1" 304 -
INFO     2019-08-11 02:43:25,107 module.py:861] default: "GET /css/main.css HTTP/1.1" 304 -

What am I doing wrong? Should I do the deployment steps first? 
collider steps, Turn server steps and constants.py steps first?

Please all the help I would appreciate.

**Steps to reproduce**

The steps to reproduce are the following.
I am installing standard Google sdk for python, nodejs v12.7.0 and grunt.

when I run npm install it yields some vulneravilities that I fix with "npm audit fix"

when I run $grunt in the main directory it yields the following in the console

Running "csslint:strict" (csslint) task
>> 1 file lint free.

Running "csslint:lax" (csslint) task
>> 1 file lint free.

Running "eslint:target" (eslint) task

Running "shell:pipInstall" (shell) task
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
Warning: Command failed: pip install --user --requirement requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
 Use --force to continue.

Aborted due to warnings.

After that I run with --force option 
and it finishes with the message: 

Done, but with warnings.

Now, when I run the command 
$grunt runPythonTests

the command throws:

Running "shell:pipInstall" (shell) task
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
Warning: Command failed: pip install --user --requirement requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
 Use --force to continue.

Aborted due to warnings.

I don't understand that error, because when I run the command pip install --user --requirement requirements.txt it runs successfully.

then I run the command with the --force option

$grunt runPythonTests --force

Running "shell:pipInstall" (shell) task
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
Warning: Command failed: pip install --user --requirement requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
 Used --force, continuing.

Running "shell:ensureGcloudSDKIsInstalled" (shell) task
ERROR: gcloud crashed (SSLHandshakeError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
ERROR: gcloud crashed (SSLHandshakeError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
Already has google-cloud-sdk, skipping the download

Running "shell:buildAppEnginePackageWithTests" (shell) task

Running "shell:runPythonTests" (shell) task
Missing temp/google-cloud-sdk/platform/google_appengine: try grunt shell:getPythonTestDeps.
Warning: Command failed: python build/run_python_tests.py temp/google-cloud-sdk/platform/google_appengine out/app_engine
Missing temp/google-cloud-sdk/platform/google_appengine: try grunt shell:getPythonTestDeps.
 Used --force, continuing.

Running "shell:removePythonTestsFromOutAppEngineDir" (shell) task
Removing out/app_engine/analytics_page_test.py.
Removing out/app_engine/apprtc_test.py.
Removing out/app_engine/test_util.py.
Removing out/app_engine/compute_page_test.py.
Removing out/app_engine/analytics_test.py.
Removing out/app_engine/analytics_enums_test.py.
Removing out/app_engine/probers_test.py.

Done, but with warnings.

Can you explain me what does it means the error --> ERROR: gcloud crashed (SSLHandshakeError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Expected results**
May I should see at least the video of my webcam locally, right? or the options to take a roon right?

**Actual results**
Nothing, the whole screen goes grey and it does not even show the room buttons.

I appreciate all the help that you can give me, thanks in advance.

While I wait for any help here I will be doing all the deployment steps, collider, TURN, etc. Just to test if after that I can run the demo code locally with success.

Regards.

**Comment by AlekRuzic** [comment]
I'm having the exact same issue

**Comment by EliosSs** [comment]
Hi Alek, I am still having that issue, could you achieve any solution? the support of this project is very poor.

Regards.

**Comment by AlekRuzic** [comment]
I actually meant to comment earlier today and forgot. What was causing me the problem was I was using Java 6 (or 1.6 I don’t really know anything about java lol) and that seemed to be messing things up when running grunt build. I upgraded to java 8 which I think required some weird workaround on Mac but after I did that it just managed to work. I hope this helps, good luck!!

Sent from my iPhone

On Sep 1, 2019, at 1:58 AM, Eliomar Conde <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alek, I am still having that issue, could you achieve any solution? the support of this project is very poor.

Regards.

**Comment by EliosSs** [comment]
hmmm ok ok. I understand, at this moment I'm running java 11.0.4. I guess I have to try with that Java 8.

Another question, are you running the collidermain and turnserver as denoted in the tutorial guide? if yes, are you running with ssl mode or without?

Regards.

**Comment by EliosSs** [comment]
In fact, that was the problem, I uninstalled my Java 11.0.4 and installed Java 8. 
Now I am able to open the webcam in **http://localhost:8080**. 
But, **I am seeing the following error in the screen that says:**

```
Messages:  
WebSocket open error: WebSocket error.
WebSocket register error: WebSocket error.
```

It was the same for you when you upgraded to JAVA 8? or it worked ok for you? I think it has to be with the collider server. I will be trying to solve this and I post here in case that you have the same issue and for future people that can ask it.

Regards

**Comment by EliosSs** [comment]
Ok, to notify on the issue post, I after installing Java 8 I was presenting the error above, and in the browser console was the error **ERR_SSL_PROTOCOL_ERROR**.

I managed this disabling the tls mode on the collider server running the command

` ./bin/collidermain -port=8089 -tls=false`

disabling TLS mode in the turnserver (through no-tls argument)

and running the link **localhost:8080/?wstls=false** with the last part indicating that the tls is disabled.

The apprtc server operated normally in the localhost mode.

With this I will close the issue as **[SOLVED]**

Now the challenge is to enable the https mode and hence the network mode (ouside localhost mode). @AlekRuzic did you manag it to run with ssl mode?

**Comment by AlekRuzic** [comment]
@EliosSs I ran it locally without configuring any collider stuff. I'm currently working on getting an actual deployment running and having some different issues now haha. I'm glad Java 8 at least helped a little.
