### ISSUE TITLE
https://appr.tc SSL certificate expired

### ISSUE THREAD

**Issue by VeprIT** [webrtc/apprtc#688]
Hi guys,

Unfortunately can't use https://appr.tc any more to connect with the iOS demo app. According to the app log, it happens because the site's SSL certificate expired. Is there any chance that it will be updated?

Thanks in advance!

**Comment by ajpedhadiya** [comment]
Hi
I have face same issue! can you help any one?

**Comment by swotsystem** [comment]
I am also facing same problem.  can anyone suggest what can i do now?

**Comment by BomMax** [comment]
Same issue at Android.

**Comment by razakhan22** [comment]
> Hi
> I have face same issue! can you help any one?

I am also facing same issue. You know when they will update SSL CERTIFICATE

**Comment by elharony** [comment]
Any updates on this?

**Comment by elharony** [comment]
@KaptenJansson @kisabaka Please check this

**Comment by elharony** [comment]
@KaptenJansson @kisabaka @fippo @samdutton  Please check this

**Comment by gnik2036** [comment]
any updates ??

**Comment by kanonjz** [comment]
Same problem. Any workaround?

**Comment by fippo** [comment]
This repository contains instructions how to run your own server for your own applications.
If you have not done this so far, now is the time.

**Comment by VeprIT** [comment]
> This repository contains instructions how to run your own server for your own applications.
> If you have not done this so far, now is the time.

Thanks for the workaround!
Does it mean that there are no plans to bring https://appr.tc back to life?

**Comment by BomMax** [comment]
I disable the SSL certificate check before sending http connection request.

Of course this workaround is totally **NOT** recommended,  I did it just for testing purpose,

**Comment by ndo04343** [comment]
> I disable the SSL certificate check before sending http connection request.
> 
> Of course this workaround is totally **NOT** recommended, I did it just for testing purpose,

Execuse me, How to disable the SSL certificate check in android app??

**Comment by razakhan22** [comment]
> This repository contains instructions how to run your own server for your own applications.
> If you have not done this so far, now is the time.

How much it costs to established own server

**Comment by swotsystem** [comment]
> > This repository contains instructions how to run your own server for your own applications.
> > If you have not done this so far, now is the time.
> 
> How much it costs to established own server

Mail swotsystemltd@gmail.com to know details about the establishment cost of own server.
