### ISSUE TITLE
Show selfview on landing page 

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#7]
https://github.com/GoogleChrome/webrtc/issues/425

See the original issue for full comment thread.

This is waiting for designer's input for now.

**Comment by KaptenJansson** [comment]
Is this something we still want to add? @juberti @samdutton WDYT?

**Comment by KaptenJansson** [comment]
Ping

**Comment by samdutton** [comment]
I don't feel strongly either way to be honest.

I'd probably err on the side of 'is it worth it?'

Depends whether we see appr.tc as becoming more of a working video chat
product, or essentially a test/'canonical' app.

**Comment by juberti** [comment]
Chuck and I tried this out and we weren't convinced. So yeah, this isn't where I would spend time at the moment.

**Comment by KaptenJansson** [comment]
Closing this for now.
