### ISSUE TITLE
Need a better way to get Collider log

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#71]
We need a way to get Collider logs without ssh-ing into the VM instance.

**Comment by jiayliu** [comment]
Correction

**Comment by jiayliu** [comment]
Idea: save the log in some cloud storage.

**Comment by metalmarco** [comment]
Try using http://supervisord.org.
You can monitor apprtc, collider and turnserver from the web interface and also get logs without ssh

**Comment by KaptenJansson** [comment]
Closing due to age.
