### ISSUE TITLE
AppRTC (https://appr.tc/) and TestRTC (https://test.webrtc.org/) services turned down

### ISSUE THREAD

**Issue by ranganirakesh** [webrtc/apprtc#719]
AppRTC (https://appr.tc/) and TestRTC (https://test.webrtc.org/) services turned down and not working in browser

**404. That’s an error.
The requested URL was not found on this server.**

**Comment by KaptenJansson** [comment]
PSA for turning it down can be found on [discuss-webrtc](https://groups.google.com/g/discuss-webrtc/c/H7XuZfgkGH0/m/Q0BKTWZICgAJ).
