### ISSUE TITLE
if apprtc can run multiple instances to achieve load balancing

### ISSUE THREAD

**Issue by chenwandong** [webrtc/apprtc#724]
**Browsers and versions affected**

**Description**
When i run google-appengine sdk on my cloud services with apprtc;
I do not know  if apprtc can run multiple instances to achieve load balancing。
Also I wan to know  if google.appengine.api.memcache  can shared key value in Multi process 
**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by KaptenJansson** [comment]
AppRTC is an App engine app originally thus it leveraged whatever App engine provided in terms of load balancing. For collider, the signalling server, it leveraged Google cloud network load balancing + using two VM instances.
