### ISSUE TITLE
Choose a running Collider instance based on prober result

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#81]
We now have a second Collider instance running: apprtc-ws-2.webrtc.org

GAE should track which Collider instances are up and return the url a working instance to the client.

E.g. the prober writes to memcache key "colliderStatus" which has a boolean status for each instance. Join request handler picks a running Collider instance for the room on room creation, and save the instance with the room data in memcache, so that clients in the same room get the same Collider.

**Comment by jiayliu** [comment]
Chuck,

Could you take a look at this when the Chrome App clean up fix is done?

**Comment by chuckhays** [comment]
Yes.

**Comment by milkypostman** [comment]
@chuckhays I am working on #76 as well which will overlap a bit with this work. Basically I am writing a handler to call restart on a prober that is down. Lets talk offline about how we want to handle this.

**Comment by chuckhays** [comment]
Completed in PR #92
