### ISSUE TITLE
Join Button help

### ISSUE THREAD

**Issue by datcomputerguy** [webrtc/apprtc#83]
Hello,
I know this is the wrong place to put this but I'm not sure where to put this.
I was using apprtc.appspot.com/r/### for a project of mine, but now that the Join button has been added it no longer functions for me.  I have created my own local google dev server and have it running with the modified parameter, but https is the issue.  I was wondering if it was possible to clone the apprtc project in the google cloud platform and run it on my own ???.appspot.com.  I know that it is possible, but I have no idea how to go about doing it.

**Comment by jiayliu** [comment]
Sure you can. Besides of deploying your own App Engine server, you need to
build and deploy Collider, the WebSocket signaling server, following the
instructions in README, and replace "apprtc-ws.apprtc.com" in constants.py
with the host of your Collider.

On Wed, Feb 18, 2015 at 7:22 PM, datcomputerguy <notifications@github.com>
wrote:

> Hello,
> I know this is the wrong place to put this but I'm not sure where to put
> this.
> I was using apprtc.appspot.com/r/### <http://apprtc.appspot.com/r/#%23%23>
> for a project of mine, but now that the Join button has been added it no
> longer functions for me. I have created my own local google dev server and
> have it running with the modified parameter, but https is the issue. I was
> wondering if it was possible to clone the apprtc project in the google
> cloud platform and run it on my own ???.appspot.com. I know that it is
> possible, but I have no idea how to go about doing it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/83>.
>



-- 
Jiayang Liu

**Comment by datcomputerguy** [comment]
Thank you!

Stupid Question: Can I do this for free?

**Comment by jiayliu** [comment]
For Collider, GCP VM instances are not free, but you can choose any hosting
solutions.
For GAE, you can checkout https://cloud.google.com/appengine/pricing


On Thu, Feb 19, 2015 at 10:54 AM, datcomputerguy <notifications@github.com>
wrote:

> Thank you!
>
> Stupid Question: Can I do this for free?
>
> On Thu, Feb 19, 2015 at 12:34 PM, Jiayang Liu <notifications@github.com>
> wrote:
>
> > Sure you can. Besides of deploying your own App Engine server, you need
> to
> > build and deploy Collider, the WebSocket signaling server, following the
> > instructions in README, and replace "apprtc-ws.apprtc.com" in
> constants.py
> > with the host of your Collider.
> >
> > On Wed, Feb 18, 2015 at 7:22 PM, datcomputerguy <
> notifications@github.com>
> > wrote:
> >
> > > Hello,
> > > I know this is the wrong place to put this but I'm not sure where to
> put
> > > this.
> > > I was using apprtc.appspot.com/r/###
> <http://apprtc.appspot.com/r/#%23%23>
> > <http://apprtc.appspot.com/r/#%23%23> <
> http://apprtc.appspot.com/r/#%23%23
> > >
> > > for a project of mine, but now that the Join button has been added it
> no
> > > longer functions for me. I have created my own local google dev server
> > and
> > > have it running with the modified parameter, but https is the issue. I
> > was
> > > wondering if it was possible to clone the apprtc project in the google
> > > cloud platform and run it on my own ???.appspot.com. I know that it is
> > > possible, but I have no idea how to go about doing it.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/webrtc/apprtc/issues/83>.
> > >
> >
> >
> >
> > --
> > Jiayang Liu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/webrtc/apprtc/issues/83#issuecomment-75108815>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/83#issuecomment-75112499>.
>



-- 
Jiayang Liu

**Comment by datcomputerguy** [comment]
Thank you, I am not very familiar with GAE and GCP.  When you say that  I
can choose any hosting solution, could you give me an example of one?

**Comment by jiayliu** [comment]
Collider is just a binary that can run on any platform that supported by
Go. So by "hosting solution" I mean whichever machine you choose to run the
binary.

On Thu, Feb 19, 2015 at 1:14 PM, datcomputerguy <notifications@github.com>
wrote:

> Thank you, I am not very familiar with GAE and GCP. When you say that I
> can choose any hosting solution, could you give me an example of one?
>
> On Thu, Feb 19, 2015 at 1:09 PM, Jiayang Liu <notifications@github.com>
> wrote:
>
> > For Collider, GCP VM instances are not free, but you can choose any
> hosting
> > solutions.
> > For GAE, you can checkout https://cloud.google.com/appengine/pricing
> >
> >
> > On Thu, Feb 19, 2015 at 10:54 AM, datcomputerguy <
> notifications@github.com
> > >
> > wrote:
> >
> > > Thank you!
> > >
> > > Stupid Question: Can I do this for free?
> > >
> > > On Thu, Feb 19, 2015 at 12:34 PM, Jiayang Liu <
> notifications@github.com>
> > > wrote:
> > >
> > > > Sure you can. Besides of deploying your own App Engine server, you
> need
> > > to
> > > > build and deploy Collider, the WebSocket signaling server, following
> > the
> > > > instructions in README, and replace "apprtc-ws.apprtc.com" in
> > > constants.py
> > > > with the host of your Collider.
> > > >
> > > > On Wed, Feb 18, 2015 at 7:22 PM, datcomputerguy <
> > > notifications@github.com>
> > > > wrote:
> > > >
> > > > > Hello,
> > > > > I know this is the wrong place to put this but I'm not sure where
> to
> > > put
> > > > > this.
> > > > > I was using apprtc.appspot.com/r/###
> <http://apprtc.appspot.com/r/#%23%23>
> > <http://apprtc.appspot.com/r/#%23%23>
> > > <http://apprtc.appspot.com/r/#%23%23>
> > > > <http://apprtc.appspot.com/r/#%23%23> <
> > > http://apprtc.appspot.com/r/#%23%23
> > > > >
> > > > > for a project of mine, but now that the Join button has been added
> it
> > > no
> > > > > longer functions for me. I have created my own local google dev
> > server
> > > > and
> > > > > have it running with the modified parameter, but https is the
> issue.
> > I
> > > > was
> > > > > wondering if it was possible to clone the apprtc project in the
> > google
> > > > > cloud platform and run it on my own ???.appspot.com. I know that
> it
> > is
> > > > > possible, but I have no idea how to go about doing it.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/webrtc/apprtc/issues/83>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Jiayang Liu
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/webrtc/apprtc/issues/83#issuecomment-75108815>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/webrtc/apprtc/issues/83#issuecomment-75112499>.
> >
> > >
> >
> >
> >
> > --
> > Jiayang Liu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/webrtc/apprtc/issues/83#issuecomment-75115212>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/83#issuecomment-75137402>.
>



-- 
Jiayang Liu

**Comment by datcomputerguy** [comment]
I have the Google Dev server up and running on a machine.  Is this what you
are talking about?

**Comment by datcomputerguy** [comment]
Okay, I got that working I think.  Now I'm having issues with getting a
TURN server working

**Comment by datcomputerguy** [comment]
Would you mind taking a look at: https://watwick.com it is my server
running a turnserver, google dev server with apprtc on it, and collider.

**Comment by jiayliu** [comment]
Our turn server is restricted by domain and your domain is now allowed. You need to build your own turn server.
