### ISSUE TITLE
Add help div to AppRTC to display keyboard shortcuts as an overlay

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#9]
https://github.com/GoogleChrome/webrtc/issues/322

Similar to if you do ? in Gmail or Docs etc:
https://cloud.githubusercontent.com/assets/1821693/5508594/94111cea-8763-11e4-9c14-bd256135b43e.png

**Comment by KaptenJansson** [comment]
Is this still valid?

**Comment by KaptenJansson** [comment]
Closing due to age.
