### ISSUE TITLE
Extract common code from unittests into a base class.

### ISSUE THREAD

**Issue by milkypostman** [webrtc/apprtc#93]
mainly the functions `makePostRequest` and `makeGetRequest` are the same among all unittests.

I don't want to take this too far though. IMO having each test class define its own `setUp` and `tearDown` functions **is** the right approach even if it repeats code.

**Comment by chuckhays** [comment]
Some of this has been done in the apprtc-t branch. We've done a bunch of refactoring there to improve the structure of the app and tests.
