### ISSUE TITLE
Chrome app doesn't send origin header to CEOD

### ISSUE THREAD

**Issue by chuckhays** [webrtc/apprtc#96]
One possible solution is to make the GET request a POST request, then it does send the origin header.

**Comment by juberti** [comment]
That seems like a reasonable solution.

**Comment by chuckhays** [comment]
An issue that @jiayliu and I were discussing is the chrome app extension id, which is what gets sent as part of the origin header. This is the value that is needed to be whitelisted.

When you "install" the unpacked app on your local dev machine during development, a random id is generated in an unpredictable way.

However, if we create an entry in the web store, we can get the permanent value and put it into the manifest so it stays stable during development.

https://developer.chrome.com/apps/manifest/key
https://developer.chrome.com/apps/app_identity#copy_key

**Comment by jiayliu** [comment]
Thanks for the investigation! Can you create the entry in app store?

On Fri, Feb 27, 2015 at 10:52 AM, Chuck Hays <notifications@github.com>
wrote:

> An issue that @jiayliu <https://github.com/jiayliu> and I were discussing
> is the chrome app extension id, which is what gets sent as part of the
> origin header. This is the value that is needed to be whitelisted.
>
> When you "install" the unpacked app on your local dev machine during
> development, a random id is generated in an unpredictable way.
>
> However, if we create an entry in the web store, we can get the permanent
> value and put it into the manifest so it stays stable during development.
>
> https://developer.chrome.com/apps/manifest/key
> https://developer.chrome.com/apps/app_identity#copy_key
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/issues/96#issuecomment-76449870>.
>



-- 
Jiayang Liu
